GENRE_QUERY_BANKS = {
    "rock": [
        "underrated indie rock 2020s",
        "post-punk revival scene",
        "art rock underground",
        "midwest emo scene",
        "noise rock cult following",
        "alternative rock deep cuts",
        "shoegaze revival scene",
        "garage rock underground",
        "psychedelic rock obscure",
        "math rock scene",
        "krautrock influence",
        "post-rock instrumental",
        "indie rock cult classics",
        "lo-fi rock bedroom recordings",
        "slacker rock 90s influenced",
    ],
    "metal": [
        "doom metal underrated",
        "sludge metal cult following",
        "post-metal atmospheric",
        "math metal progressive",
        "black metal underrated scene",
        "death metal cult following",
        "post-hardcore underground",
        "screamo underrated bands",
        "metalcore deep cuts",
        "drone metal experimental",
        "noise metal scene",
        "stoner metal cult",
        "progressive metal underrated",
        "djent underrated",
        "tech death underground",
        "Indian metal scene",
        "Indian progressive metal",
    ],
    "pop": [
        "indie pop 2020s underground",
        "art pop underground scene",
        "dream pop cult following",
        "bedroom pop artists",
        "chamber pop obscure",
        "baroque pop underrated",
        "synth pop cult 80s influenced",
        "sophisti-pop underrated",
        "twee pop artists",
        "hyperpop experimental",
        "art pop female vocals",
        "indie pop guitar jangly",
        "power pop underrated",
        "electropop underground",
        "bubblegum pop underground",
    ],
    "hip-hop": [
        "underground rap scene",
        "boom bap underground",
        "experimental hip hop",
        "conscious rap underrated",
        "jazz rap cult following",
        "lo-fi hip hop artists",
        "abstract hip hop experimental",
        "indie rap scene",
        "underground east coast rap",
        "west coast underground rap",
        "southern rap underground",
        "trap underground",
        "noise rap experimental",
        "lyrical underground rap",
        "avant garde hip hop",
    ],
    "r&b": [
        "neo soul underground",
        "alternative r&b cult",
        "indie r&b artists",
        "lo-fi r&b bedroom",
        "experimental r&b",
        "future soul artists",
        "dark r&b underground",
        "indie soul scene",
        "bedroom r&b lo-fi",
        "art r&b experimental vocals",
        "jazz influenced r&b",
        "soul underground modern",
        "r&b singer songwriter",
        "atmospheric r&b",
        "underground r&b 2020s",
    ],
    "electronic": [
        "underground techno artists",
        "ambient electronic cult",
        "IDM experimental",
        "experimental electronic underrated",
        "modular synthesis artists",
        "lo-fi electronic bedroom",
        "post-dubstep underground",
        "footwork juke scene",
        "drone electronic ambient",
        "glitch art electronic",
        "ambient techno underground",
        "dark electronic experimental",
        "industrial electronic underground",
        "neo-classical electronic crossover",
        "ambient drone soundscapes",
    ],
    "jazz": [
        "jazz underground modern",
        "avant garde jazz experimental",
        "jazz fusion underrated",
        "free jazz cult following",
        "spiritual jazz underrated",
        "jazz rap fusion",
        "modern jazz London scene",
        "jazz funk underrated",
        "post-bop obscure",
        "contemporary jazz piano",
        "neo-bop underground",
        "jazz nu-jazz modern",
        "world jazz fusion",
        "chamber jazz underrated",
        "jazz electronica crossover",
    ],
    "classical": [
        "neoclassical piano underrated",
        "modern classical experimental",
        "contemporary classical composers",
        "minimalist classical artists",
        "ambient classical crossover",
        "post-classical underground",
        "neoclassical piano solo",
        "contemporary chamber music",
        "minimalist orchestral",
        "modern string quartet",
        "solo piano contemporary",
        "orchestral ambient crossover",
        "sacred minimalist classical",
        "late romantic orchestral",
        "film score orchestral underrated",
    ],
    "lofi": [
        "lofi hip hop underrated",
        "lo-fi bedroom producers",
        "chillhop underground",
        "lofi jazz beats",
        "study lofi obscure",
        "lofi soul beats",
        "underground lofi producers",
        "bedroom lo-fi artists underground",
        "lofi hip hop aesthetic 2023 2024",
        "lofi chill instrumental",
        "lo-fi indie bedroom recordings",
        "lofi beats underground",
        "tape music lo-fi",
        "lo-fi ambient chill",
        "lofi beats study focus",
    ],
    "indie": [
        "indie folk underground",
        "indie rock cult 2020s",
        "slowcore sadcore artists",
        "dream pop indie underground",
        "lo-fi indie bedroom",
        "indie singer-songwriter underrated",
        "emo revival underground",
        "midwest emo modern",
        "shoegaze indie 2020s",
        "indie pop guitar jangly",
        "indie folk singer songwriter",
        "lo-fi indie atmospheric",
        "indie chamber pop",
        "indie rock post-punk adjacent",
        "indie bedroom pop underground",
    ],
    "acoustic": [
        "fingerpicking guitar underrated",
        "acoustic folk obscure",
        "singer songwriter bedroom",
        "acoustic indie folk 2020s",
        "neofolk acoustic",
        "acoustic americana underground",
        "fingerstyle guitar solo",
        "acoustic ballad underrated",
        "acoustic indie singer songwriter",
        "acoustic chamber folk",
        "acoustic pop underground",
        "acoustic guitar meditative",
        "classical acoustic guitar crossover",
        "acoustic roots music",
        "acoustic lo-fi recordings",
    ],
    "folk": [
        "freak folk experimental",
        "psychedelic folk obscure",
        "traditional folk revival",
        "folk punk underground",
        "anti-folk cult following",
        "appalachian folk underrated",
        "new weird america folk",
        "British folk revival",
        "Irish folk traditional",
        "harp folk experimental",
        "dark folk underground",
        "folk drone experimental",
        "folk baroque crossover",
        "celtic folk modern",
        "Nordic folk scene",
    ],
    "blues": [
        "delta blues obscure",
        "chicago blues underground",
        "electric blues cult",
        "blues rock underrated",
        "acoustic blues traditional",
        "country blues obscure",
        "young blues rock scene",
        "modern blues underground",
        "blues soul crossover",
        "blues guitar instrumental",
        "southern blues underrated",
        "blues revival modern",
        "blues jazz crossover",
        "British blues rock revival",
        "indie blues underground",
    ],
    "country": [
        "outlaw country underrated",
        "americana underground",
        "alt country obscure",
        "country folk singer songwriter",
        "red dirt country underground",
        "country blues roots",
        "honky tonk traditional",
        "modern country underground",
        "Appalachian country folk",
        "country soul crossover",
        "roots country underrated",
        "country indie crossover",
        "country gospel underground",
        "western folk country",
        "singer songwriter country underground",
    ],
    "reggae": [
        "roots reggae classic",
        "dub experimental",
        "dancehall underground",
        "reggae revival modern",
        "rocksteady ska underground",
        "dub techno crossover",
        "reggae soul crossover",
        "modern reggae conscious",
        "reggae roots spiritual",
        "Jamaican revival roots",
        "neo reggae scene",
        "dub ambient crossover",
        "reggae folk crossover",
        "dancehall alternative",
        "roots dub underground",
    ],
    "latin": [
        "latin jazz obscure",
        "bossa nova cult following",
        "cumbia underground",
        "salsa classic deep cuts",
        "afro-latin experimental",
        "nueva cancion folk latin",
        "reggaeton underground",
        "Brazilian experimental music",
        "Cuban jazz roots",
        "Latin alternative underground",
        "Mexican indie rock",
        "Latin folk singer songwriter",
        "South American experimental",
        "Latin soul crossover",
        "bolero romantic classic",
    ],
    "afrobeats": [
        "afrobeats underground",
        "highlife classic",
        "afrobeat Fela inspired",
        "afropop underrated",
        "juju music Nigeria",
        "afro soul",
        "Nigerian music underground",
        "afrobeats 2020s underground",
        "West African pop underground",
        "afro fusion modern",
        "afropop alternative",
        "East African pop underground",
        "Ghanaian music modern",
        "afrobeats soul crossover",
        "African indie music",
    ],
    "ambient": [
        "dark ambient experimental",
        "drone ambient cult following",
        "ambient classical crossover",
        "field recording ambient",
        "generative ambient music",
        "atmospheric ambient post-rock adjacent",
        "hauntology music",
        "ambient systems music",
        "ambient techno underground",
        "neo-classical ambient",
        "ambient drone soundscapes",
        "dark ambient industrial crossover",
        "ambient nature field recordings",
        "slow ambient meditation",
        "tape ambient lo-fi",
    ],
    "ghazal": [
        "ghazal classical Pakistani",
        "urdu ghazal traditional",
        "hindi ghazal",
        "ghazal vocal classical",
        "ghazal semi-classical",
        "ghazal modern interpretation",
        "Pakistani ghazal underground",
        "Indian ghazal classical",
        "ghazal thumri crossover",
        "contemporary ghazal artists",
    ],
    "qawwali": [
        "qawwali sufi music",
        "qawwali devotional",
        "sufi qawwali Pakistani",
        "qawwali traditional",
        "modern qawwali interpretation",
        "qawwali underground artists",
        "sufi qawwali Indian",
        "qawwali fusion modern",
    ],
    "sufi": [
        "sufi music Hindi",
        "sufi songs Bollywood",
        "sufi rock India",
        "sufi folk India",
        "sufi devotional",
        "Indian sufi underground",
        "sufi pop crossover",
        "sufi classical crossover",
        "sufi fusion modern India",
        "sufi indie India",
    ],
    "carnatic": [
        "carnatic classical vocal",
        "carnatic instrumental",
        "south Indian classical music",
        "carnatic fusion modern",
        "carnatic contemporary artists",
        "carnatic vocal underrated",
        "carnatic violin instrumental",
        "carnatic flute instrumental",
        "carnatic mandolin crossover",
        "carnatic world fusion",
    ],
    "hindustani": [
        "hindustani classical raga",
        "north Indian classical music",
        "sitar classical hindustani",
        "tabla solo hindustani",
        "flute hindustani classical",
        "sarod hindustani classical",
        "kirana gharana vocal",
        "hindustani vocal underrated",
        "hindustani classical contemporary",
        "raga fusion modern",
    ],
    "bhangra": [
        "bhangra Punjabi modern",
        "Punjabi underground indie",
        "Punjabi folk traditional",
        "Punjabi indie music",
        "Punjabi pop underground",
        "bhangra fusion modern",
        "Punjabi singer songwriter",
        "Punjabi music 2020s",
    ],
    "devotional": [
        "bhajan Hindi devotional",
        "devotional songs India",
        "Indian devotional classical crossover",
        "devotional music contemporary",
        "devotional folk India",
        "bhajan classical crossover",
        "devotional indie India",
        "temple music devotional",
    ],
    "indian folk": [
        "Indian folk music traditional",
        "Rajasthani folk music",
        "Baul songs Bengal",
        "folk fusion India",
        "tribal folk India",
        "Indian folk singer songwriter",
        "Indian folk rock crossover",
        "rural folk India traditional",
        "folk songs India regional",
        "Indian roots music",
    ],
}

MOOD_QUERY_BANKS = {
    "sad": [
        "midwest emo sad songs",
        "slowcore sadcore scene",
        "sad indie bedroom pop",
        "emo revival sad 2020s",
        "post-rock melancholy",
        "ambient sad music",
        "shoegaze sad dreamy",
        "singer songwriter sad confessional",
        "sad piano neoclassical",
        "heartbreak indie underground",
        "sad folk songs obscure",
        "sad indie confessional lyrics",
        "grief music indie",
        "melancholy post-rock",
        "sad slowcore underground",
    ],
    "melancholy": [
        "bittersweet indie pop",
        "melancholic dream pop",
        "nostalgic indie folk",
        "wistful ambient music",
        "melancholy neoclassical piano",
        "melancholy orchestral pop",
        "melancholy folk singer songwriter",
        "bittersweet post-rock",
        "melancholy dream pop ethereal",
        "slowcore melancholy",
        "melancholy ambient drone",
        "wistful indie bedroom pop",
        "melancholy film score",
        "orchestral melancholy modern",
        "melancholy chamber music",
    ],
    "dark": [
        "dark atmospheric indie",
        "post-punk dark scene",
        "darkwave underground",
        "gothic rock cult following",
        "industrial dark experimental",
        "noise rock dark",
        "dark experimental underground",
        "dark folk underground",
        "dark ambient industrial",
        "dark post-punk revival",
        "gothic darkwave underground",
        "dark drone atmospheric",
        "dark neo-classical",
        "dark singer songwriter",
        "dark ethereal vocals",
    ],
    "angry": [
        "noise rock angry",
        "hardcore punk underground",
        "post-hardcore aggression",
        "math rock intense",
        "death metal underground",
        "grindcore scene",
        "experimental rap angry",
        "noise rap experimental",
        "hardcore heavy",
        "post-hardcore intense",
        "math metalcore",
        "heavy noise underground",
        "sludge heavy angry",
        "punk political underground",
        "angry indie underground",
    ],
    "nostalgic": [
        "nostalgic indie dream pop",
        "shoegaze 90s revival",
        "jangle pop classic",
        "bedroom pop nostalgic",
        "lo-fi nostalgic tape",
        "shoegaze nostalgic",
        "dreamy nostalgic indie",
        "90s indie nostalgia",
        "jangle pop nostalgic",
        "nostalgic bedroom recordings",
        "nostalgic ambient music",
        "nostalgic dream pop",
        "late 90s indie nostalgia",
        "nostalgic lo-fi",
        "nostalgic folk singer songwriter",
    ],
    "lonely": [
        "lonely ambient music",
        "solitude indie folk",
        "late night sad songs",
        "3am music playlist",
        "isolation ambient",
        "introspective singer songwriter",
        "solitude ambient drone",
        "lonely indie bedroom pop",
        "introspective folk",
        "quiet lonely songs",
        "late night introspective indie",
        "solitude post-rock",
        "lonely slowcore",
        "isolated ambient",
        "solitude acoustic folk",
    ],
    "anxious": [
        "anxious indie music",
        "tense post-punk",
        "nervous energy music",
        "anxious experimental",
        "overwhelming noise music",
        "anxious post-punk revival",
        "tense math rock",
        "anxious indie underground",
        "nervous energy post-punk",
        "restless indie music",
        "uneasy ambient",
        "tense experimental",
        "anxiety indie confessional",
        "unsettling ambient dark",
        "nervous indie bedroom",
    ],
    "happy": [
        "feel good indie pop",
        "jangly indie rock happy",
        "upbeat bedroom pop",
        "indie pop cheerful 2020s",
        "sunshine pop underground",
        "upbeat indie folk",
        "cheerful bedroom pop",
        "feel good indie underground",
        "joyful indie pop",
        "uplifting indie rock",
        "sunny indie pop",
        "cheerful singer songwriter",
        "feel good 2020s indie",
        "happy jangle pop",
        "upbeat indie guitar",
    ],
    "romantic": [
        "romantic indie folk",
        "love songs indie underground",
        "tender dream pop",
        "romantic neoclassical",
        "intimate bedroom pop love",
        "romantic ambient",
        "tender indie folk",
        "intimate love songs underground",
        "romantic dream pop",
        "soft romantic indie",
        "tender acoustic love songs",
        "romantic lo-fi",
        "love songs bedroom pop",
        "romantic singer songwriter",
        "soft romantic pop underground",
    ],
    "hopeful": [
        "uplifting indie folk",
        "hopeful ambient",
        "inspiring post-rock",
        "redemption arc indie",
        "healing music indie",
        "hopeful folk singer songwriter",
        "uplifting post-rock",
        "hopeful indie underground",
        "optimistic indie pop",
        "healing ambient",
        "hopeful orchestral",
        "uplifting chamber music",
        "hopeful bedroom pop",
        "encouraging indie folk",
        "uplifting lo-fi",
    ],
    "chill": [
        "chill indie underground",
        "laid back bedroom pop",
        "mellow indie chill",
        "lo-fi chill beats",
        "ambient chill electronic",
        "chill lo-fi bedroom",
        "mellow indie underground",
        "chill world music",
        "laid back indie rock",
        "chill ambient electronic",
        "mellow soul chill",
        "lo-fi chill instrumental",
        "chill indie folk",
        "mellow bedroom pop",
        "chill electronic ambient",
    ],
    "focused": [
        "focus music instrumental",
        "study music ambient",
        "concentration piano",
        "deep work music",
        "background instrumental indie",
        "lo-fi study beats",
        "focus ambient",
        "concentration instrumental",
        "study piano classical",
        "deep focus ambient",
        "work music instrumental background",
        "focus drone ambient",
        "study electronic ambient",
        "piano focus solo",
        "deep work lo-fi",
    ],
    "dreamy": [
        "dreamy shoegaze",
        "ethereal dream pop",
        "hazy psychedelic indie",
        "surreal ambient music",
        "hypnotic drone music",
        "dreamy ethereal vocals",
        "hazy bedroom dream pop",
        "hypnotic ambient drone",
        "dreamy psychedelic",
        "surreal indie underground",
        "dreamy lo-fi",
        "ethereal ambient",
        "dreamy chamber pop",
        "floating ambient dreamy",
        "dreamy post-rock",
    ],
    "energetic": [
        "energetic underground rock",
        "high energy post-punk",
        "intense math rock",
        "energetic indie underground",
        "pump up underground rap",
        "energetic hardcore",
        "high energy indie rock",
        "intense post-punk revival",
        "energetic dance punk",
        "high energy garage rock",
        "energetic noise rock",
        "intense experimental",
        "energetic punk revival",
        "upbeat energetic indie",
        "high energy underground",
    ],
    "night": [
        "late night indie",
        "night drive music",
        "nocturnal ambient",
        "2am songs underground",
        "midnight indie bedroom",
        "night electronic ambient",
        "nocturnal r&b",
        "late night dream pop",
        "night jazz",
        "nocturnal lo-fi",
        "midnight ambient",
        "night drive electronic",
        "late night trip hop",
        "nocturnal indie",
        "dark night music",
    ],
    "summer": [
        "summer indie pop",
        "beach indie rock",
        "sunshine indie underground",
        "summer bedroom pop",
        "warm jangly indie",
        "summer psychedelic",
        "beach pop underground",
        "summer lo-fi",
        "warm summer indie folk",
        "sunshine garage rock",
        "summer dream pop",
        "warm indie rock",
        "surf rock modern",
        "summer singer songwriter",
        "warm indie acoustic",
    ],
    "rainy": [
        "rainy day indie",
        "rainy ambient music",
        "grey sky music",
        "monsoon music India",
        "rainy bedroom pop",
        "rainy ambient drone",
        "grey day music",
        "rainy lo-fi",
        "overcast ambient",
        "rainy slowcore",
        "rainy dream pop",
        "grey sky folk",
        "rainy neoclassical",
        "overcast indie acoustic",
        "rainy day singer songwriter",
    ],
    "spiritual": [
        "sufi music spiritual",
        "devotional world music",
        "spiritual ambient meditation",
        "sacred music world",
        "spiritual drone music",
        "devotional folk world",
        "sacred choral music",
        "spiritual neoclassical",
        "devotional ambient",
        "sacred minimalist",
        "spiritual world fusion",
        "devotional Indian classical",
        "spiritual folk",
        "sacred ambient music",
        "spiritual post-rock",
    ],
    "confident": [
        "badass swagger rock",
        "empowering female rap",
        "confident underground hip hop",
        "confident strut electronic",
        "unstoppable heavy rock",
        "main character indie pop",
        "winning anthem underground",
        "confident dance electronic",
        "empowering r&b",
        "bold indie pop",
        "confident art pop",
        "swagger underground rap",
        "strong female vocals indie",
        "empowering indie",
        "confident post-punk",
    ],
    "peaceful": [
        "peaceful acoustic fingerpicking",
        "serene ambient drone",
        "tranquil neoclassical",
        "quiet nature field recordings",
        "stillness drone music",
        "gentle classical piano",
        "harmony vocal ambient",
        "peaceful ambient soundscapes",
        "serene minimalist",
        "quiet folk acoustic",
        "peaceful world music",
        "tranquil electronic ambient",
        "serene neoclassical piano",
        "gentle ambient",
        "peaceful meditation music",
    ],
    "playful": [
        "playful indie pop",
        "quirky art pop",
        "bouncy bedroom pop",
        "silly experimental funk",
        "goofy synth pop",
        "cheeky indie rock",
        "playful funk underground",
        "quirky indie underground",
        "playful art pop",
        "fun bedroom pop",
        "whimsical indie",
        "bouncy indie pop",
        "playful electronic",
        "silly indie fun",
        "joyful quirky indie",
    ],
    "sensual": [
        "seductive neo soul",
        "sensual dark r&b",
        "sultry jazz underground",
        "steamy bedroom electronic",
        "late night sensual indie",
        "sensual ambient",
        "dark r&b atmospheric",
        "sultry soul underground",
        "sensual electronic",
        "intimate r&b bedroom",
        "sensual trip hop",
        "dark sensual indie",
        "sultry jazz modern",
        "sensual lo-fi",
        "intimate vocal r&b",
    ],
    "grieving": [
        "grief ambient music",
        "loss slowcore",
        "mourning instrumental",
        "funeral doom ambient",
        "grief indie confessional",
        "mourning acoustic folk",
        "grief post-rock",
        "loss chamber music",
        "goodbye sad indie",
        "bereavement acoustic",
        "grief ambient drone",
        "mourning neoclassical",
        "loss songs indie",
        "grief slowcore",
        "dark grief music",
    ],
    "bored": [
        "slacker rock 90s",
        "monotone post-punk",
        "indifferent bedroom pop",
        "bored shoegaze",
        "slacker indie",
        "lo-fi bored bedroom",
        "indifferent post-punk",
        "slacker garage rock",
        "lo-fi slacker",
        "deadpan indie",
        "flat affect indie",
        "monotonous ambient",
        "slacker folk",
        "bored art pop",
        "understated indie",
    ],
    "overwhelmed": [
        "frantic noise rock",
        "chaotic mathcore",
        "overwhelming drone",
        "hyperpop chaotic",
        "fast breakcore",
        "burnout ambient",
        "overwhelming noise experimental",
        "chaotic hardcore",
        "frantic experimental",
        "sensory overload music",
        "intense chaotic noise",
        "frantic drum machine",
        "overwhelmed indie",
        "anxious chaotic",
        "overwhelming industrial",
    ],
    "trippy": [
        "psychedelic rock underground",
        "trippy space ambient",
        "mind bending IDM",
        "acid house underground",
        "cosmic synth music",
        "psybient trippy",
        "trippy psychedelic pop",
        "space rock psychedelic",
        "mind bending experimental",
        "lysergic folk",
        "psychedelic ambient",
        "trippy drone",
        "cosmic electronic",
        "psychedelic noise",
        "acid jazz trippy",
    ],
    "rebellious": [
        "riot grrrl punk",
        "anarchist punk rock",
        "defiant underground rap",
        "anti system industrial",
        "teen angst pop punk",
        "rebellious punk underground",
        "defiant indie",
        "anti-establishment music",
        "punk revival underground",
        "rebellious hardcore",
        "defiant art pop",
        "political punk rock",
        "rebellious rap underground",
        "outsider music",
        "counter-culture rock",
    ],
    "heartbroken": [
        "heartbreak slowcore",
        "dumped sad acoustic",
        "breakup indie pop",
        "betrayed angry rock",
        "crying over you r&b",
        "heartbreak indie confessional",
        "breakup singer songwriter",
        "heartbreak ambient",
        "sad breakup lo-fi",
        "heartbreak folk",
        "breakup dream pop",
        "heartbreak bedroom pop",
        "devastating indie songs",
        "breakup slowcore",
        "sad love songs indie",
    ],
    "wanderlust": [
        "roadtrip americana",
        "adventure indie folk",
        "explore cinematic post-rock",
        "wild country folk",
        "journey progressive rock",
        "highway indie rock",
        "wanderlust folk",
        "travel world music",
        "adventure ambient",
        "open road music",
        "exploratory post-rock",
        "wanderer folk singer songwriter",
        "roadtrip indie rock",
        "journey ambient",
        "wilderness folk",
    ],
    "mysterious": [
        "mysterious dark jazz",
        "enigmatic trip hop",
        "shadowy dark ambient",
        "spooky dungeon synth",
        "detective noir jazz",
        "mysterious ambient",
        "enigmatic post-rock",
        "dark mysterious electronic",
        "shadowy indie",
        "mysterious experimental",
        "occult folk",
        "enigmatic drone",
        "mysterious noir soundtrack",
        "dark mysterious indie",
        "unsettling ambient",
    ],
}

INDIAN_LANG_QUERY_BANKS = {
    "hindi": {
        "film": [
            "Bollywood melody songs",
            "Hindi film sad songs",
            "AR Rahman Hindi songs",
            "Pritam Bollywood",
            "Bollywood indie film songs",
            "Shankar Ehsaan Loy compositions",
            "Hindi film 2020s songs",
            "Bollywood underground indie",
            "Hindi film melody vocals",
            "Bollywood golden era songs",
            "Bollywood classics 90s",
            "Hindi film romantic songs",
            "Mithoon compositions Hindi",
            "Vishal Bhardwaj film songs",
            "Gulzar penned songs",
        ],
        "indie": [
            "Hindi indie music non-film",
            "Indian Ocean Hindi rock",
            "Hindi indie underground 2020s",
            "Nucleya Hindi electronic",
            "Indian metal Hindi",
            "Hindi indie singer songwriter",
            "indie Hindi pop non-film",
            "Hindi indie underground scene",
        ],
    },
    "telugu": {
        "film": [
            "Telugu melody songs",
            "Tollywood hits emotional",
            "SS Thaman Telugu compositions",
            "Devi Sri Prasad Telugu songs",
            "AR Rahman Telugu songs",
            "MM Keeravani Telugu compositions",
            "Mickey J Meyer Telugu melody",
            "Sid Sriram Telugu songs",
            "Telugu film 2020s songs",
            "Telugu sad songs emotional",
            "Anirudh Telugu songs",
            "Ilayaraja Telugu classics",
            "Telugu romantic songs film",
            "Telugu classical songs old",
            "SP Balasubrahmanyam Telugu",
        ],
        "indie": [
            "Telugu indie non-film music",
            "Telugu independent artists",
            "Telugu underground music",
            "Telugu folk fusion indie",
            "Telugu rock bands underground",
        ],
    },
    "tamil": {
        "film": [
            "Tamil melody songs Kollywood",
            "AR Rahman Tamil compositions",
            "Ilayaraja Tamil classics",
            "Anirudh Tamil songs",
            "GV Prakash Tamil songs",
            "D Imman Tamil melody",
            "Harris Jayaraj Tamil melody",
            "Sid Sriram Tamil",
            "Tamil film 2020s songs",
            "Tamil sad songs emotional",
            "Yuvan Shankar Raja Tamil",
            "Karthik Raja Tamil compositions",
            "Tamil golden era songs",
            "SP Balasubrahmanyam Tamil",
        ],
        "indie": [
            "Tamil indie non-film music",
            "Tamil independent artists",
            "Tamil rock bands indie",
            "Tamil underground music",
            "Tamil folk fusion indie",
        ],
    },
    "kannada": {
        "film": [
            "Kannada melody songs Sandalwood",
            "V Harikrishna Kannada compositions",
            "Arjun Janya Kannada songs",
            "Ravi Basrur Kannada",
            "Ajaneesh Loknath Kannada",
            "Hamsalekha Kannada classic songs",
            "Kannada film 2020s songs",
            "Kannada sad songs emotional",
            "SA Rajkumar Kannada classics",
            "Rajan Nagendra Kannada classic",
        ],
        "indie": [
            "Kannada indie non-film music",
            "Raghu Dixit Kannada indie rock",
            "Kannada underground music",
            "Kannada folk fusion",
        ],
    },
    "malayalam": {
        "film": [
            "Malayalam melody songs Mollywood",
            "Shaan Rahman Malayalam compositions",
            "Gopi Sundar Malayalam",
            "M Jayachandran Malayalam",
            "Bijibal Malayalam songs",
            "Sushin Shyam Malayalam",
            "KJ Yesudas Malayalam classics",
            "AR Rahman Malayalam songs",
            "Malayalam film 2020s songs",
            "Malayalam sad songs emotional",
            "Hesham Abdul Wahab Malayalam",
            "Jakes Bejoy Malayalam",
        ],
        "indie": [
            "Malayalam indie non-film music",
            "Malayalam independent artists",
            "Kerala indie music",
            "Malayalam folk fusion indie",
        ],
    },
    "punjabi": {
        "film": [
            "Punjabi songs hits 2020s",
            "Punjabi pop mainstream",
            "Punjabi bhangra hits",
            "Punjabi sad songs emotional",
            "Punjabi folk traditional",
        ],
        "indie": [
            "Punjabi folk indie singer songwriter",
            "Punjabi independent music",
            "Punjabi underground artists",
        ],
    },
    "bengali": {
        "film": [
            "Bengali film songs",
            "Rabindra Sangeet",
            "Bengali romantic film songs",
            "Bengali classic songs",
        ],
        "indie": [
            "Bengali indie music",
            "Bengali independent artists",
            "Bengali underground music",
        ],
    },
    "marathi": {
        "film": [
            "Marathi film songs",
            "Ajay Atul Marathi compositions",
            "Marathi songs hits",
        ],
        "indie": [
            "Marathi indie music non-film",
            "Marathi underground artists",
        ],
    },
    "gujarati": {
        "film": [
            "Gujarati garba songs",
            "Gujarati dandiya music",
            "Gujarati folk songs",
        ],
        "indie": [
            "Gujarati folk indie",
            "Gujarati underground music",
        ],
    },
}

LANG_GENRE_CROSS_QUERIES = {
    ("korean", "rock"):    ["Korean rock bands underground", "K-rock scene", "Korean indie rock", "Korean post-punk"],
    ("korean", "metal"):   ["Korean metal bands underground", "Korean heavy music", "K-metal scene"],
    ("korean", "indie"):   ["K-indie artists", "Korean indie underground", "Korean bedroom pop", "Korean indie scene"],
    ("korean", "jazz"):    ["Korean jazz artists", "K-jazz modern", "Korean jazz underground"],
    ("korean", "hip-hop"): ["K-hip hop underground", "Korean rap underground", "Korean conscious rap"],
    ("japanese", "rock"):  ["Japanese rock bands underground", "J-rock underground scene", "Japanese indie rock", "Japanese post-rock"],
    ("japanese", "metal"): ["Japanese metal bands underground", "Japanese heavy music", "J-metal scene"],
    ("japanese", "indie"): ["Japanese indie music underground", "J-indie scene", "Japanese bedroom pop", "Japanese singer songwriter"],
    ("japanese", "jazz"):  ["Japanese jazz underground", "Japanese piano jazz", "Japanese jazz modern"],
    ("japanese", "folk"):  ["Japanese folk music traditional", "Japanese acoustic folk", "Japanese folk singer songwriter"],
    ("hindi", "rock"):     ["Hindi rock bands India", "Indian rock Hindi songs", "Hindi indie rock", "Indian rock scene Hindi"],
    ("hindi", "metal"):    ["Indian metal bands Hindi", "Hindi metal underground", "Indian heavy music Hindi"],
    ("hindi", "jazz"):     ["Indian jazz Hindi", "Indian jazz fusion", "Hindustani jazz crossover"],
    ("hindi", "hip-hop"):  ["Hindi rap underground", "Hindi hip hop scene", "Indian rap Hindi lyrics"],
    ("hindi", "electronic"):["Hindi electronic music", "Indian electronic Hindi", "Hindi indie electronic"],
    ("telugu", "rock"):    ["Telugu rock bands underground", "Tollywood rock songs", "Telugu indie rock"],
    ("telugu", "metal"):   ["Telugu metal bands India", "Indian metal Telugu songs"],
    ("tamil", "rock"):     ["Tamil rock bands underground", "Tamil indie rock scene", "Chennai rock bands indie"],
    ("tamil", "metal"):    ["Tamil metal bands underground", "Chennai metal scene"],
    ("tamil", "hip-hop"):  ["Tamil rap underground", "Tamil hip hop 2020s", "Tamil rap scene"],
    ("kannada", "rock"):   ["Kannada rock bands underground", "Bangalore rock bands indie", "Kannada indie rock"],
    ("malayalam", "rock"): ["Malayalam rock bands Kerala", "Kerala rock bands indie", "Malayalam indie rock"],
    ("french", "rock"):    ["French rock bands underground", "French indie rock", "French post-punk"],
    ("french", "jazz"):    ["French jazz underground", "Paris jazz scene", "French jazz modern"],
    ("german", "metal"):   ["German metal bands underground", "German heavy music", "German thrash metal"],
    ("german", "electronic"): ["German electronic Krautrock influenced", "German electronic scene", "German experimental electronic"],
    ("portuguese", "jazz"):["Brazilian jazz bossa nova scene", "Brazilian jazz underground", "Brazilian experimental jazz"],
    ("spanish", "rock"):   ["Spanish rock bands underground", "Spanish indie rock scene"],
    ("arabic", "folk"):    ["Arabic folk music traditional", "Arabic classical music", "Arabic world music"],
    ("turkish", "folk"):   ["Turkish folk music traditional", "Turkish folk underground", "Anatolian folk music"],
}