import { EXTENDED_FIGURES } from './figures/index.js';

// Saint or Sinner, data deck for the blind reputation-judgment game.
//
// Each figure is a REAL public person (historical or present-day, global +
// India-heavy mix). The player reads several DELIBERATELY OBSCURE-but-factual
// traits, the least-famous true things about them, and slides a verdict on the
// Sinner↔Saint spectrum WITHOUT knowing who it is, then guesses the identity
// from three plausible same-field options. The reveal compares their slider to
// `reputation`, a curated, approximate read on how the world *generally* regards
// the person. It is opinion/entertainment, not a moral fact, and every trait is
// drawn from public record (no invented allegations).
//
// Design rules for traits:
//   1. Subtlety first, reach for the side-door details, not the headline fact
//      everyone already knows. The three options give away the *field*, so the
//      traits should make it hard to pick which of the three it is.
//   2. Balance, every figure shows both LITTLE-KNOWN VIRTUES and LITTLE-KNOWN
//      FLAWS, interleaved. Saints get their underrated dark side; sinners get
//      their underrated redeeming side. That tension is the whole game.
//
// Figure shape:
//   id          stable slug
//   name        the correct answer (also present in `options`)
//   era         'Historical' | 'Modern'   (just a flavour tag on the reveal)
//   traits      4–6 short factual lines, understated, good + bad mixed
//   options     exactly 3 candidate names incl. `name`; shuffled at render time
//   reputation  0..100 position on the spectrum (0 = reviled, 100 = beloved)
//   verdict     short chip shown on reveal
//   reveal      one line: who they are + why the score sits where it does

export const SPECTRUM = {
  min: 0,
  max: 100,
  low: 'Sinner',
  high: 'Saint',
};

// How many figures one playthrough serves up (deck is shuffled + sliced
// against the per-account "seen" pool so the player meets fresh strangers
// every round until the full FIGURES list is exhausted).
export const ROUND_COUNT = 15;

// Map a 0..100 score to a band, used for the live slider label and the
// reveal chip. Colours lean on the app's cool palette plus warm/red for the
// low end.
export function repBand(score) {
  if (score >= 85) return { key: 'saint',  label: 'Saint',       color: '#9fd8b4' };
  if (score >= 65) return { key: 'good',   label: 'Good Egg',    color: '#9ab8cc' };
  if (score >= 45) return { key: 'mixed',  label: 'Complicated', color: '#c9c2a6' };
  if (score >= 25) return { key: 'shady',  label: 'Shady',       color: '#d99a5a' };
  return                    { key: 'sinner', label: 'Sinner',     color: '#cf6b6b' };
}

export const FIGURES = [
  {
    id: 'mandela',
    name: 'Nelson Mandela',
    era: 'Modern',
    traits: [
      'As a young man he trained as an amateur heavyweight boxer.',
      'He co-founded and led an armed wing that set off sabotage bombings.',
      'He taught himself his jailers’ language to better understand them.',
      'A schoolteacher handed him the English first name the world now uses.',
      'He stayed loyal to strongmen others shunned, and admitted being a distant father.',
      'He gave away a third of his presidential salary to a children’s fund.',
    ],
    options: ['Desmond Tutu', 'Nelson Mandela', 'Kofi Annan'],
    reputation: 91,
    verdict: 'Beloved',
    reveal: 'Nelson Mandela, from prisoner to president, a near-universal symbol of forgiveness.',
  },
  {
    id: 'gandhi',
    name: 'Mohandas Gandhi',
    era: 'Historical',
    traits: [
      'Crippled by nerves, he fled his very first courtroom unable to speak.',
      'He ran a communal farm he named after a Russian novelist he admired.',
      'Early in life he wrote of local Black Africans in openly racist terms.',
      'He nursed plague and war victims by hand as a young volunteer.',
      'His eldest son grew so estranged he changed faiths to spite him.',
      'In old age he tested his vow of celibacy by sleeping beside young women.',
    ],
    options: ['Bhagat Singh', 'Jawaharlal Nehru', 'Mohandas Gandhi'],
    reputation: 82,
    verdict: 'Revered, with caveats',
    reveal: 'Mohandas (Mahatma) Gandhi, icon of nonviolent independence, though historians debate the man behind the myth.',
  },
  {
    id: 'curie',
    name: 'Marie Curie',
    era: 'Historical',
    traits: [
      'During a world war she drove mobile X-ray vans to the front line.',
      'She refused to patent her discovery, giving it to the world for free.',
      'A love affair with a married colleague became a vicious public scandal.',
      'She handled deadly materials so casually it likely shortened lives, including her own.',
      'Her national academy of sciences still refused her a seat.',
      'A century on, her notebooks are kept in lead-lined boxes.',
    ],
    options: ['Rosalind Franklin', 'Marie Curie', 'Ada Lovelace'],
    reputation: 89,
    verdict: 'Admired',
    reveal: 'Marie Curie, pioneer of radioactivity who gave her health to her work; broadly admired to this day.',
  },
  {
    id: 'teresa',
    name: 'Mother Teresa',
    era: 'Historical',
    traits: [
      'Before her calling she taught geography at a convent school.',
      'Private letters revealed decades of doubt about her own faith.',
      'Her homes were faulted for thin medical care and reused needles.',
      'She lived austerely while her order spread across the globe.',
      'She took, and kept, donations from dictators and convicted fraudsters.',
      'She quietly baptised the dying without their knowledge.',
    ],
    options: ['Florence Nightingale', 'Mother Teresa', 'Princess Diana'],
    reputation: 60,
    verdict: 'Complicated',
    reveal: 'Mother Teresa, sainted by the Church and beloved by millions, yet seriously challenged by some who studied her work.',
  },
  {
    id: 'columbus',
    name: 'Christopher Columbus',
    era: 'Historical',
    traits: [
      'A self-taught navigator, he was turned down repeatedly before a crown funded him.',
      'He kept a second, doctored logbook to mislead his own crew.',
      'As a colonial governor he was so brutal he was arrested and shipped home in chains.',
      'He shipped enslaved islanders back across the ocean by the hundreds.',
      'He died insisting he had reached the far edge of Asia.',
      'Where his bones rest is still disputed between two countries.',
    ],
    options: ['Ferdinand Magellan', 'Christopher Columbus', 'Vasco da Gama'],
    reputation: 27,
    verdict: 'Falling fast',
    reveal: 'Christopher Columbus, once a textbook hero, his reputation has collapsed under the weight of what colonisation wrought.',
  },
  {
    id: 'leopold',
    name: 'King Leopold II of Belgium',
    era: 'Historical',
    traits: [
      'A tall, bearded monarch with a mostly ceremonial role at home.',
      'He sold himself to the world as a humanitarian opening Africa to civilisation.',
      'The wealth he extracted built grand boulevards and monuments in his capital.',
      'That wealth came from forced labour, enforced with severed-hand quotas.',
      'Millions died on the land, and he never once set foot there.',
      'He looted his private empire so badly his own government had to seize it.',
    ],
    options: ['Cecil Rhodes', 'King Leopold II of Belgium', 'King Philip II of Spain'],
    reputation: 5,
    verdict: 'Reviled (and under-known)',
    reveal: 'King Leopold II, his Congo Free State is among history’s deadliest atrocities, still shockingly absent from many classrooms.',
  },
  {
    id: 'musk',
    name: 'Elon Musk',
    era: 'Modern',
    traits: [
      'At twelve he coded a little space game and sold it to a magazine.',
      'As a teenager he tested living on a dollar a day of food.',
      'He joined his best-known car company as an investor, not its founder.',
      'A flippant market post cost him a regulator’s fine and a chairmanship.',
      'Former staff describe brutal hours and abrupt mass firings.',
      'He holds citizenship in three different countries.',
    ],
    options: ['Jeff Bezos', 'Elon Musk', 'Mark Zuckerberg'],
    reputation: 44,
    verdict: 'Deeply polarising',
    reveal: 'Elon Musk, visionary engineer to some, reckless provocateur to others; few opinions land in the middle.',
  },
  {
    id: 'diana',
    name: 'Princess Diana',
    era: 'Modern',
    traits: [
      'Before her famous wedding she worked as an assistant at a kindergarten.',
      'She made secret late-night visits to the homeless and the dying.',
      'She secretly rehearsed a dance and performed it on a London stage as a gift.',
      'She admitted on television to an affair of her own.',
      'She was a shrewd manipulator of the very press she resented.',
      'She is buried on a small island in the middle of a lake.',
    ],
    options: ['Grace Kelly', 'Princess Diana', 'Audrey Hepburn'],
    reputation: 86,
    verdict: 'Beloved',
    reveal: 'Princess Diana, “the people’s princess,” remembered for warmth and a fearless use of her fame.',
  },
  {
    id: 'greta',
    name: 'Greta Thunberg',
    era: 'Modern',
    traits: [
      'She comes from a family of stage actors and an opera singer.',
      'As a child she went through a spell of barely speaking or eating.',
      'She gave away a large cash prize to environmental causes.',
      'Critics dismiss her as an alarmist scold beyond her depth.',
      'She has been detained more than once at protests.',
      'She talked her own family into giving up flying and meat.',
    ],
    options: ['Malala Yousafzai', 'Greta Thunberg', 'Emma Watson'],
    reputation: 54,
    verdict: 'Polarising',
    reveal: 'Greta Thunberg, climate activist hailed as a conscience by some and resented as a scold by others.',
  },
  {
    id: 'messi',
    name: 'Lionel Messi',
    era: 'Modern',
    traits: [
      'His family uprooted to Europe when he was just thirteen.',
      'Famously left-footed, he is very rarely booked for a foul.',
      'He funds children’s hospital wards and youth football quietly.',
      'A court once handed him a suspended sentence for tax fraud.',
      'Critics long accused him of going missing in his country’s biggest games.',
      'He hails from the same Argentine city as Che Guevara.',
    ],
    options: ['Cristiano Ronaldo', 'Lionel Messi', 'Neymar'],
    reputation: 84,
    verdict: 'Beloved',
    reveal: 'Lionel Messi, widely regarded as one of the greatest to ever play, and an unusually uncontroversial superstar.',
  },

  // ── India-heavy additions ───────────────────────────────────────────────────
  {
    id: 'kalam',
    name: 'A. P. J. Abdul Kalam',
    era: 'Modern',
    traits: [
      'As a boy he sold newspapers before dawn to help his family.',
      'He missed becoming a fighter pilot by a single place on the list.',
      'A lifelong bachelor, he gave most of his earnings away and played the veena.',
      'He was the proud public face of his country’s nuclear-weapon tests.',
      'As head of state he left a stack of death-row mercy pleas undecided.',
      'He collapsed doing what he loved most, lecturing to students.',
    ],
    options: ['A. P. J. Abdul Kalam', 'Vikram Sarabhai', 'Homi Bhabha'],
    reputation: 90,
    verdict: 'Beloved',
    reveal: 'A. P. J. Abdul Kalam, the rocket scientist who became India’s beloved “People’s President.”',
  },
  {
    id: 'ambedkar',
    name: 'B. R. Ambedkar',
    era: 'Historical',
    traits: [
      'He earned doctorates from universities on two different continents.',
      'He helped win the eight-hour working day for his country’s labourers.',
      'He publicly burned an ancient law-book he called a charter of oppression.',
      'His personal library ran to tens of thousands of books.',
      'He resigned from the cabinet when a women’s-rights bill stalled.',
      'Late in life he led hundreds of thousands away from the faith he was born into.',
    ],
    options: ['B. R. Ambedkar', 'Jawaharlal Nehru', 'Sardar Patel'],
    reputation: 85,
    verdict: 'Revered',
    reveal: 'B. R. Ambedkar, jurist, economist and reformer who shaped the founding document of modern India.',
  },
  {
    id: 'lata',
    name: 'Lata Mangeshkar',
    era: 'Modern',
    traits: [
      'Her father died when she was thirteen, and she acted in films to feed her siblings.',
      'She built a hospital in her late father’s name.',
      'Rivals accused her of using her clout to freeze out newer voices.',
      'An obsessive cricket fan, she held honorary memberships at famous grounds.',
      'A long rift with her own singer-sister played out for years.',
      'Her voice carried across film for some seven decades.',
    ],
    options: ['Lata Mangeshkar', 'Asha Bhosle', 'Noor Jehan'],
    reputation: 87,
    verdict: 'Beloved',
    reveal: 'Lata Mangeshkar, the “Nightingale of India,” whose playback voice defined Hindi cinema for generations.',
  },
  {
    id: 'indira',
    name: 'Indira Gandhi',
    era: 'Modern',
    traits: [
      'The only child of a founding prime minister, she grew up inside the freedom struggle.',
      'As a girl she organised a children’s volunteer brigade.',
      'She led her nation to a decisive war that birthed a new country.',
      'She once suspended civil liberties and jailed her rivals for nearly two years.',
      'A mass-sterilisation drive on her watch scarred the poor.',
      'She sent troops into a faith’s holiest shrine, with bloody consequences.',
    ],
    options: ['Indira Gandhi', 'Sonia Gandhi', 'Benazir Bhutto'],
    reputation: 46,
    verdict: 'Complicated',
    reveal: 'Indira Gandhi, India’s only woman prime minister, admired for her steel and condemned for the Emergency.',
  },
  {
    id: 'bose',
    name: 'Subhas Chandra Bose',
    era: 'Historical',
    traits: [
      'He cracked the empire’s elite civil-service exam, then resigned to fight it.',
      'He raised a liberation army abroad, complete with a women’s regiment.',
      'A spellbinding orator, he split bitterly from the movement’s moderate wing.',
      'He sought wartime backing from his rulers’ enemies, and met their dictators.',
      'He once mused his country might need a dictator for twenty years.',
      'Many still refuse to believe he died in that plane crash.',
    ],
    options: ['Subhas Chandra Bose', 'Bhagat Singh', 'Chandra Shekhar Azad'],
    reputation: 73,
    verdict: 'Revered, debated',
    reveal: 'Subhas Chandra Bose, the firebrand “Netaji” whose wartime alliances and unexplained disappearance still spark debate.',
  },

  // ── Less-famous-but-real additions ───────────────────────────────────────
  // Recognisable to history readers, not household names. Each entry mixes
  // genuine virtues, genuine wrongs, and ordinary human details — the spec is
  // good traits + bad traits + normal traits + best and worst moments.
  {
    id: 'petrov',
    name: 'Stanislav Petrov',
    era: 'Historical',
    traits: [
      'A mid-rank duty officer in a Cold War missile-warning bunker, not a general.',
      'His own father had been a fighter pilot in the Second World War.',
      'One night the system told him five enemy missiles were inbound and he had minutes.',
      'He chose to call it a glitch — and refused to pass the warning up the chain.',
      'His own bosses reprimanded him afterward for sloppy paperwork.',
      'He drank heavily in retirement and died alone in a small flat outside Moscow.',
    ],
    options: ['Vasili Arkhipov', 'Stanislav Petrov', 'Oleg Gordievsky'],
    reputation: 92,
    verdict: 'Quiet hero',
    reveal: 'Stanislav Petrov, the Soviet officer who, in 1983, almost certainly prevented an accidental nuclear war by trusting his gut over his computer.',
  },
  {
    id: 'haber',
    name: 'Fritz Haber',
    era: 'Historical',
    traits: [
      'He grew up middle-class in a Prussian town and trained as a chemist.',
      'He worked out how to pull nitrogen from thin air to make fertiliser.',
      'That process now feeds an estimated half of everyone alive.',
      'In wartime he personally directed the first mass chlorine-gas attacks at the front.',
      'His own wife, also a chemist, shot herself with his service pistol soon after.',
      'A decade later the regime he served chased him out for being Jewish.',
    ],
    options: ['Fritz Haber', 'Otto Hahn', 'Werner Heisenberg'],
    reputation: 38,
    verdict: 'Saviour and poisoner',
    reveal: 'Fritz Haber, whose nitrogen fixation feeds billions today — and whose chemical-weapons work in the First World War haunts the same legacy.',
  },
  {
    id: 'lamarr',
    name: 'Hedy Lamarr',
    era: 'Historical',
    traits: [
      'A Hollywood leading lady marketed as “the most beautiful woman in film.”',
      'In her teens she had eloped into a marriage with a fascist-arms tycoon.',
      'She fled that marriage by reportedly drugging her maid and slipping away in disguise.',
      'In her spare time she invented a frequency-hopping signal that underpins Wi-Fi today.',
      'The US navy filed her patent away and ignored it for two decades.',
      'She died near-bankrupt, with shoplifting charges on her late record.',
    ],
    options: ['Hedy Lamarr', 'Veronica Lake', 'Greta Garbo'],
    reputation: 80,
    verdict: 'Underestimated',
    reveal: 'Hedy Lamarr, glamour star and self-taught inventor whose wartime patent helped pave the way for modern wireless.',
  },
  {
    id: 'kurien',
    name: 'Verghese Kurien',
    era: 'Modern',
    traits: [
      'A Kerala-born engineer posted, unwillingly, to a tiny dairy in Gujarat.',
      'He stayed, and turned that dairy into a national farmer-owned movement.',
      'He could be sharp-tongued and bureaucratic enemies were legion.',
      'He insisted on running the brand without a single celebrity on the packet.',
      'He helped India go from milk-importer to the largest milk-producing country on earth.',
      'He once refused a cabinet job, calling himself “not a politician.”',
    ],
    options: ['M. S. Swaminathan', 'Verghese Kurien', 'Sam Pitroda'],
    reputation: 88,
    verdict: 'Quietly transformative',
    reveal: 'Verghese Kurien, the “Milkman of India” who built Amul and the cooperative model that lifted millions of rural families.',
  },
  {
    id: 'phoolan',
    name: 'Phoolan Devi',
    era: 'Modern',
    traits: [
      'Married off as a child to a man decades older, she fled abuse to the ravines.',
      'She joined a bandit gang and, after her own kidnap and rape, took it over.',
      'She is said to have led the massacre of twenty-two upper-caste men in one village.',
      'After eleven years in prison she walked out and won a seat in parliament twice.',
      'Lower-caste women in her region painted her face on temple walls as a goddess.',
      'She was shot dead at her own front door at the age of thirty-seven.',
    ],
    options: ['Phoolan Devi', 'Sampat Pal', 'Irom Sharmila'],
    reputation: 41,
    verdict: 'Avenger or murderer',
    reveal: 'Phoolan Devi, the “Bandit Queen” turned MP — revered by some as caste-rebel symbol, condemned by others as a killer.',
  },
  {
    id: 'lacks',
    name: 'Henrietta Lacks',
    era: 'Historical',
    traits: [
      'A Black tobacco farmer and mother of five in segregation-era America.',
      'She walked into a colored ward complaining of a knot inside her.',
      'A doctor took a slice of her tumour without ever asking her permission.',
      'Those cells became the first human line that wouldn’t stop dividing.',
      'They have flown into space, taught us polio vaccines, and earned others fortunes.',
      'She died poor, and her family was not told for another twenty-five years.',
    ],
    options: ['Henrietta Lacks', 'Rosa Parks', 'Mamie Till'],
    reputation: 84,
    verdict: 'Wronged, then beloved',
    reveal: 'Henrietta Lacks, whose unconsented cells (the “HeLa” line) seeded modern medicine while her own family was kept in the dark for decades.',
  },
  {
    id: 'borlaug',
    name: 'Norman Borlaug',
    era: 'Modern',
    traits: [
      'A farm boy from depression-era Iowa who studied plant pathology on a scholarship.',
      'He spent decades crossing wheat strains by hand in dusty Mexican fields.',
      'His high-yield wheat is credited with averting famine for hundreds of millions.',
      'Environmentalists accused his methods of leaning too hard on chemicals and water.',
      'He pushed his work into India and Pakistan as the two were on the brink of war.',
      'He won the Nobel Peace Prize and almost no one in his own country knows his name.',
    ],
    options: ['Norman Borlaug', 'M. S. Swaminathan', 'Jonas Salk'],
    reputation: 87,
    verdict: 'Saved a billion, barely remembered',
    reveal: 'Norman Borlaug, father of the Green Revolution, whose wheat is credited with saving an estimated billion lives.',
  },

  // ── Drastic expansion: figures recognisable to history readers but not
  //    household names. Mix of historical + modern, global + India-heavy,
  //    each with good + bad + ordinary traits so the verdict isn't obvious.
  {
    id: 'turing',
    name: 'Alan Turing',
    era: 'Historical',
    traits: [
      'A long-distance runner who trained at near-Olympic times in his spare hours.',
      'He laid the formal groundwork for the machine in front of you now.',
      'In wartime he led the team that cracked an "unbreakable" enemy cipher.',
      'Convicted of "gross indecency" for being gay, he was chemically castrated.',
      'He was barred from his country\'s secret intelligence work after the trial.',
      'He died, aged forty-one, of cyanide poisoning beside a half-eaten apple.',
    ],
    options: ['Alan Turing', 'John von Neumann', 'Claude Shannon'],
    reputation: 90,
    verdict: 'Tragic genius',
    reveal: 'Alan Turing, the founder of theoretical computer science, hounded to death by the state he had helped save.',
  },
  {
    id: 'kahlo',
    name: 'Frida Kahlo',
    era: 'Modern',
    traits: [
      'A bus crash at eighteen left her in lifelong pain and a body cast.',
      'She painted herself again and again, more than fifty times in oil.',
      'She married a famous muralist twice, and cheated on him with men and women.',
      'A committed communist, she hosted Trotsky as a houseguest and lover.',
      'Doctors amputated her gangrenous leg the year before she died.',
      'Her last diary entry reads, "I hope the exit is joyful — and I hope never to return."',
    ],
    options: ['Frida Kahlo', 'Tamara de Lempicka', 'Georgia O’Keeffe'],
    reputation: 88,
    verdict: 'Defiant icon',
    reveal: 'Frida Kahlo, the Mexican painter whose self-portraits turned a lifetime of pain into modern art\'s most quoted face.',
  },
  {
    id: 'chanel',
    name: 'Coco Chanel',
    era: 'Historical',
    traits: [
      'Orphaned young, she sang in a cabaret before she ever picked up a needle.',
      'She freed women from corsets with a jersey suit and a little black dress.',
      'Her perfume became, and remains, one of the best-selling scents on earth.',
      'During the occupation she lived with a Nazi intelligence officer at the Ritz.',
      'Declassified files show she carried out at least one wartime mission for them.',
      'She fled to Switzerland for a decade to dodge the post-war reckoning.',
    ],
    options: ['Coco Chanel', 'Elsa Schiaparelli', 'Madeleine Vionnet'],
    reputation: 52,
    verdict: 'Brilliant, compromised',
    reveal: 'Coco Chanel, who liberated women\'s fashion in the morning and worked for the occupying regime by night.',
  },
  {
    id: 'suu-kyi',
    name: 'Aung San Suu Kyi',
    era: 'Modern',
    traits: [
      'The daughter of an assassinated independence leader, she grew up between New Delhi and Oxford.',
      'She spent the better part of fifteen years under house arrest by a junta.',
      'She won the Nobel Peace Prize while still detained, her sons accepting on her behalf.',
      'Once freed, her government dismissed the Rohingya as illegal immigrants.',
      'She personally defended her military at the International Court of Justice.',
      'A coup later put her, in her late seventies, back in prison again.',
    ],
    options: ['Aung San Suu Kyi', 'Benazir Bhutto', 'Sheikh Hasina'],
    reputation: 36,
    verdict: 'Fallen icon',
    reveal: 'Aung San Suu Kyi, once the world\'s favourite political prisoner, whose handling of the Rohingya crisis collapsed her halo.',
  },
  {
    id: 'allende',
    name: 'Salvador Allende',
    era: 'Historical',
    traits: [
      'A medical doctor who specialised in the public-health needs of the poor.',
      'He became the first openly Marxist leader freely elected anywhere in the Americas.',
      'He nationalised the copper mines that foreign companies had built fortunes on.',
      'Food shortages and runaway inflation soured much of his middle class against him.',
      'A US-backed coup bombed his presidential palace eleven days into spring.',
      'He died inside it, by his own gifted rifle, refusing to surrender on air.',
    ],
    options: ['Salvador Allende', 'Fidel Castro', 'Che Guevara'],
    reputation: 68,
    verdict: 'Martyred reformer',
    reveal: 'Salvador Allende, Chile\'s democratically elected socialist president, killed in the Pinochet-led coup of 1973.',
  },
  {
    id: 'angelou',
    name: 'Maya Angelou',
    era: 'Modern',
    traits: [
      'She worked, in her youth, as a streetcar conductor and a calypso dancer.',
      'After a childhood trauma she went mute for almost five years.',
      'She paid the rent for a while by managing a small brothel in San Francisco.',
      'Her first memoir became required reading in schools across her country.',
      'She helped Malcolm X build an organisation, then helped Dr. King with another.',
      'She was the first Black woman whose face appeared on her country\'s coinage.',
    ],
    options: ['Maya Angelou', 'Toni Morrison', 'Alice Walker'],
    reputation: 89,
    verdict: 'Beloved',
    reveal: 'Maya Angelou, poet, memoirist, civil-rights organiser, and a voice that defined a generation of American letters.',
  },
  {
    id: 'ela-bhatt',
    name: 'Ela Bhatt',
    era: 'Modern',
    traits: [
      'A Gujarati lawyer raised in a household that hosted Gandhi\'s movement.',
      'She organised street-vendors, head-loaders and rag-pickers into a union of their own.',
      'She helped found the world\'s first bank for and by self-employed women.',
      'She quietly took a seat in her country\'s upper house, then left without fanfare.',
      'Critics called her organisation\'s growth slow and its politics cautious.',
      'She mentored Nelson Mandela\'s Elders panel in her last working years.',
    ],
    options: ['Ela Bhatt', 'Medha Patkar', 'Aruna Roy'],
    reputation: 88,
    verdict: 'Quietly transformative',
    reveal: 'Ela Bhatt, founder of SEWA, who built one of the world\'s largest unions of poor self-employed women.',
  },
  {
    id: 'bhagat',
    name: 'Bhagat Singh',
    era: 'Historical',
    traits: [
      'A Sikh boy from a small Punjab village raised on tales of armed rebellion.',
      'He gave up the family-arranged marriage to throw himself into the freedom movement.',
      'He shot a British police officer dead in revenge for a beaten elder leader.',
      'He set off two harmless bombs inside the colonial assembly, then waited to be arrested.',
      'In jail he wrote a short essay defending atheism and read voraciously.',
      'They hanged him at twenty-three, then dragged his body out a back wall to dodge a crowd.',
    ],
    options: ['Bhagat Singh', 'Chandra Shekhar Azad', 'Sukhdev Thapar'],
    reputation: 86,
    verdict: 'Revered martyr',
    reveal: 'Bhagat Singh, the young revolutionary whose hanging at 23 made him perhaps independent India\'s most enduring icon of defiance.',
  },
  {
    id: 'savitribai',
    name: 'Savitribai Phule',
    era: 'Historical',
    traits: [
      'Married off illiterate at the age of nine, she learned to read from her husband.',
      'She and he opened the first school for girls in their region of India.',
      'High-caste neighbours threw cow dung and stones at her as she walked to teach.',
      'She kept a spare sari in her bag every day to change on arrival.',
      'She also ran a shelter where pregnant high-caste widows could give birth in safety.',
      'She died nursing the poor through a plague she eventually caught herself.',
    ],
    options: ['Savitribai Phule', 'Pandita Ramabai', 'Sarojini Naidu'],
    reputation: 91,
    verdict: 'Quietly revolutionary',
    reveal: 'Savitribai Phule, India\'s first woman teacher and a foundational figure in the country\'s anti-caste and women\'s-education movements.',
  },
  {
    id: 'ramanujan',
    name: 'Srinivasa Ramanujan',
    era: 'Historical',
    traits: [
      'A clerk in a Madras port office who scribbled equations on temple floors.',
      'He wrote to a Cambridge professor with results no one had seen in print.',
      'That professor brought him to England, where the cold and rationing wrecked him.',
      'Devoutly Hindu, he refused the canteen food and almost starved by mistake.',
      'His notebooks, found after his death, kept mathematicians busy for the next century.',
      'He died of tuberculosis-like illness at thirty-two, almost back home in India.',
    ],
    options: ['Srinivasa Ramanujan', 'Satyendra Nath Bose', 'P. C. Mahalanobis'],
    reputation: 89,
    verdict: 'Singular genius',
    reveal: 'Srinivasa Ramanujan, the self-taught Indian mathematician whose intuited identities are still being unpacked a century on.',
  },
  {
    id: 'vinoba',
    name: 'Vinoba Bhave',
    era: 'Historical',
    traits: [
      'Gandhi\'s first satyagrahi, picked from a small Maharashtrian village.',
      'For thirteen years he walked across India asking landowners to donate land.',
      'Roughly four million acres were given away into his Bhoodan movement.',
      'Critics said the gifts were often the worst land, given for tax breaks.',
      'He publicly backed Indira Gandhi\'s controversial Emergency, calling it "a festival of discipline."',
      'He died, refusing food and medicine, after a brief illness in his ashram.',
    ],
    options: ['Vinoba Bhave', 'Jayaprakash Narayan', 'Acharya Kripalani'],
    reputation: 64,
    verdict: 'Revered, debated',
    reveal: 'Vinoba Bhave, Gandhi\'s spiritual heir, whose land-gift movement and Emergency-era endorsement still divide opinion.',
  },
  {
    id: 'galileo',
    name: 'Galileo Galilei',
    era: 'Historical',
    traits: [
      'A lute-player\'s son who entered medical school and dropped out for mathematics.',
      'He improved the telescope and turned it on the heavens, sketching what he saw.',
      'He cosied up to a powerful pope, then mocked him in print as a simpleton.',
      'A church court forced him to "abjure, curse and detest" the moving Earth.',
      'He fathered three children with his unmarried partner of many years.',
      'He spent his last decade blind, under house arrest in a small Tuscan villa.',
    ],
    options: ['Galileo Galilei', 'Johannes Kepler', 'Tycho Brahe'],
    reputation: 88,
    verdict: 'Father of modern science',
    reveal: 'Galileo Galilei, whose telescope and stubbornness moved Europe a step closer to evidence-based science, at heavy personal cost.',
  },

  // ── Bollywood / Tollywood / Hollywood film + TV figures with publicly
  //    documented mixed traits. Every line draws on the public record —
  //    court judgements, on-record interviews, charitable trusts, well-
  //    covered tabloid threads — so the deck stays factual even when the
  //    figures themselves are tabloid-magnetic.
  {
    id: 'salman',
    name: 'Salman Khan',
    era: 'Modern',
    traits: [
      'A bodybuilder son of a Bollywood screenwriter who broke out as a romantic lead.',
      'He runs a charity that funds surgeries for under-privileged children.',
      'A late-night SUV crash on a Mumbai bakery pavement killed a homeless man asleep there.',
      'He was acquitted of culpable homicide on appeal after a thirteen-year case.',
      'A separate court found him guilty of poaching a protected antelope on a film shoot.',
      'Public figures, female co-stars and ex-partners have called his temper frightening.',
    ],
    options: ['Salman Khan', 'Sanjay Dutt', 'Aamir Khan'],
    reputation: 48,
    verdict: 'Adored and accused',
    reveal: 'Salman Khan, one of Bollywood\'s biggest box-office draws, whose decades-long legal cases coexist with a massive philanthropic operation.',
  },
  {
    id: 'sanjay-dutt',
    name: 'Sanjay Dutt',
    era: 'Modern',
    traits: [
      'The son of two superstar actors, he lost his mother to cancer as a teenager.',
      'He battled a heroin addiction in his twenties and went public about rehab.',
      'He was caught with an illegal automatic rifle linked to the 1993 Mumbai blasts.',
      'A special TADA court convicted him on the arms charge, not on terror.',
      'He served roughly five years across multiple stints in Pune\'s Yerwada jail.',
      'Behind bars he taught fellow inmates yoga and helped fund a school for their kids.',
    ],
    options: ['Sanjay Dutt', 'Salman Khan', 'Shah Rukh Khan'],
    reputation: 56,
    verdict: 'Fallen, redeemed, debated',
    reveal: 'Sanjay Dutt, the "Munnabhai" star whose jail time over an illegal weapons cache turned his second act into a comeback story.',
  },
  {
    id: 'srk',
    name: 'Shah Rukh Khan',
    era: 'Modern',
    traits: [
      'An outsider from Delhi who broke into Bombay cinema with no film family backing.',
      'He still gives time, once a year, to fans who line up at his home gate.',
      'A high-profile customs case at Mumbai airport put him in a holding cell overnight.',
      'His teenage son was arrested in a cruise-ship narcotics raid, then released uncharged.',
      'He runs a foundation funding acid-attack survivors and paediatric surgery.',
      'He has been famously self-deprecating about his height, his bad films and his luck.',
    ],
    options: ['Shah Rukh Khan', 'Aamir Khan', 'Salman Khan'],
    reputation: 84,
    verdict: 'Beloved across borders',
    reveal: 'Shah Rukh Khan, "King Khan," one of the most-recognised actors on earth and an unusually durable hero of mainstream Hindi cinema.',
  },
  {
    id: 'amitabh',
    name: 'Amitabh Bachchan',
    era: 'Modern',
    traits: [
      'His father was a celebrated Hindi poet; he himself once worked at a freight company.',
      'A near-fatal stunt accident on a film set kept him on a ventilator for weeks.',
      'He was a sitting MP whose name surfaced in the Bofors scandal, never charged.',
      'His business empire collapsed in the late nineties, leaving him deep in debt.',
      'He repaid every rupee, returned to television hosting and refused bankruptcy protection.',
      'His name appeared in the Panama Papers leak as a director of offshore firms.',
    ],
    options: ['Amitabh Bachchan', 'Dharmendra', 'Dilip Kumar'],
    reputation: 79,
    verdict: 'Revered, complicated',
    reveal: 'Amitabh Bachchan, the "angry young man" turned grand patriarch of Indian cinema, a comeback story shadowed by old controversies.',
  },
  {
    id: 'sridevi',
    name: 'Sridevi',
    era: 'Modern',
    traits: [
      'She acted in her first film aged four and worked through her entire childhood.',
      'Fluent across five film industries, she shot Tamil, Telugu and Hindi films in parallel.',
      'She quietly married a married producer, which scandalised the gossip press at the time.',
      'She walked away from acting for fifteen years to raise her daughters.',
      'Her late-career return drew some of the best reviews of her life.',
      'She drowned in a hotel bathtub in Dubai, aged fifty-four, on a family wedding trip.',
    ],
    options: ['Sridevi', 'Madhuri Dixit', 'Rekha'],
    reputation: 86,
    verdict: 'Beloved, mourned',
    reveal: 'Sridevi, India\'s first female superstar, whose sudden death in 2018 plunged South Asian cinema into a week of public grief.',
  },
  {
    id: 'sushant',
    name: 'Sushant Singh Rajput',
    era: 'Modern',
    traits: [
      'An engineering topper who ditched college a year before graduation for theatre.',
      'He came up through Indian television dance shows and a daily soap.',
      'He bought a piece of land on the moon and spoke openly about science and meditation.',
      'Behind the scenes he struggled with severe anxiety and clinical depression.',
      'A police raid on his death-day flat dragged his housemate into a months-long media trial.',
      'He was found hanged at thirty-four, a death the CBI ultimately ruled a suicide.',
    ],
    options: ['Sushant Singh Rajput', 'Siddharth Malhotra', 'Varun Dhawan'],
    reputation: 78,
    verdict: 'Loved, mourned',
    reveal: 'Sushant Singh Rajput, the small-town engineer-turned-actor whose 2020 death sparked a media frenzy in India that ran for months.',
  },
  {
    id: 'chiranjeevi',
    name: 'Chiranjeevi',
    era: 'Modern',
    traits: [
      'The eldest son of a Telugu policeman, born in a small village in Andhra Pradesh.',
      'He runs the Chiranjeevi Charitable Trust and built one of India\'s largest voluntary blood banks.',
      'He founded a political party that managed only a handful of seats, and merged it away.',
      'Critics in his short cabinet tenure called him often-absent and disengaged.',
      'He stepped away from acting for almost a decade and lost his box-office aura.',
      'He has been quietly supporting families of Telugu film workers across two pandemics.',
    ],
    options: ['Chiranjeevi', 'Mohan Babu', 'Nagarjuna'],
    reputation: 81,
    verdict: 'Beloved Megastar',
    reveal: 'Chiranjeevi, Tollywood\'s "Megastar" and a long-running force in Telugu philanthropy, even after a bumpy turn into politics.',
  },
  {
    id: 'ntr-sr',
    name: 'N. T. Rama Rao',
    era: 'Historical',
    traits: [
      'A dairy farmer\'s son who started on stage and went on to act in hundreds of films.',
      'He played Lord Krishna and Lord Rama so often that fans treated him as divine.',
      'He founded a new state-level party and became chief minister within nine months.',
      'In office he scrapped the colonial Patel-Patwari system and rolled out two-rupee rice.',
      'His own son-in-law engineered a palace coup that toppled him from his own party.',
      'He died of a heart attack a year later, broken-hearted, in his own home.',
    ],
    options: ['N. T. Rama Rao', 'Akkineni Nageswara Rao', 'Sivaji Ganesan'],
    reputation: 84,
    verdict: 'Beloved star and statesman',
    reveal: 'N. T. Rama Rao, the Telugu superstar who became Andhra Pradesh\'s three-time chief minister and a folk-hero in the Telugu diaspora.',
  },
  {
    id: 'rdj',
    name: 'Robert Downey Jr.',
    era: 'Modern',
    traits: [
      'He grew up on his father\'s film sets, smoking marijuana with him as an eight-year-old.',
      'He was arrested again and again on drug charges across the late nineties.',
      'A California court eventually sentenced him to three years in a state prison.',
      'A studio fired him from a hit TV show while he was still in rehab.',
      'He spent a decade clean before being cast as a metal-suited billionaire in 2008.',
      'He quietly funds science fellowships and an environmental venture-fund of his own.',
    ],
    options: ['Robert Downey Jr.', 'Brad Pitt', 'Johnny Depp'],
    reputation: 83,
    verdict: 'Comeback kid',
    reveal: 'Robert Downey Jr., whose Iron Man comeback after a decade of addiction and prison time became one of Hollywood\'s most-cited redemption arcs.',
  },
  {
    id: 'keanu',
    name: 'Keanu Reeves',
    era: 'Modern',
    traits: [
      'A Beirut-born Canadian who flunked out of high school and worked as an ice-rink sweeper.',
      'Tabloids picked him as their go-to "lonely man on a park bench" photograph.',
      'He has reportedly given away tens of millions of his "Matrix" earnings to support staff and crew.',
      'His baby daughter was stillborn and his partner died in a car crash soon after.',
      'He rides the subway in New York with no security and gives strangers his seat.',
      'A young woman once broke into his home and he made her tea and called the police calmly.',
    ],
    options: ['Keanu Reeves', 'Brendan Fraser', 'Jeff Bridges'],
    reputation: 92,
    verdict: 'The internet\'s favourite human',
    reveal: 'Keanu Reeves, an action star whose quietly generous off-camera life has made him a folk-hero of internet culture.',
  },
  {
    id: 'britney',
    name: 'Britney Spears',
    era: 'Modern',
    traits: [
      'A Louisiana child performer who anchored a major pop-star factory by sixteen.',
      'She publicly broke down in 2007, shaved her head and attacked a paparazzo car.',
      'A Los Angeles court placed her under a conservatorship run by her own father.',
      'For thirteen years she could not spend her own money or remove an IUD without permission.',
      'A grassroots fan campaign helped force a court review that finally ended it.',
      'She still tours stadiums and has sold more than a hundred million records worldwide.',
    ],
    options: ['Britney Spears', 'Christina Aguilera', 'Jessica Simpson'],
    reputation: 72,
    verdict: 'Survivor, finally free',
    reveal: 'Britney Spears, whose thirteen-year conservatorship became a global case study in how the music industry handled a young star\'s breakdown.',
  },
  {
    id: 'will-smith',
    name: 'Will Smith',
    era: 'Modern',
    traits: [
      'A West Philadelphia rapper who paid the IRS most of his early hip-hop earnings in back-tax.',
      'A TV sitcom and a string of action films made him one of Hollywood\'s most bankable leads.',
      'He has spoken openly about his marriage\'s "entanglements" on his wife\'s talk show.',
      'On live Oscars television he slapped a comedian for joking about his wife\'s alopecia.',
      'The Academy banned him from attending its ceremony for ten years.',
      'His charity has built schools and funded cancer research in West Philly and beyond.',
    ],
    options: ['Will Smith', 'Eddie Murphy', 'Denzel Washington'],
    reputation: 58,
    verdict: 'Brilliant, polarising',
    reveal: 'Will Smith, the global movie star whose 2022 Oscars slap reset, perhaps permanently, the way Hollywood and audiences read him.',
  },
  {
    id: 'johnny-depp',
    name: 'Johnny Depp',
    era: 'Modern',
    traits: [
      'A Kentucky high-school dropout who broke through as a teen TV cop in the eighties.',
      'He has played the same eccentric pirate captain in five blockbuster sequels.',
      'A UK judge ruled it was "substantially true" that he had assaulted his ex-wife.',
      'A Virginia jury later found his ex-wife had defamed him in a newspaper essay.',
      'He has paid medical bills for a girl he met as a child cancer patient for decades.',
      'A small studio dropped him from a major franchise during the height of the dispute.',
    ],
    options: ['Johnny Depp', 'Jared Leto', 'Bradley Cooper'],
    reputation: 49,
    verdict: 'Adored and disputed',
    reveal: 'Johnny Depp, the franchise star whose internationally televised defamation trial with Amber Heard became the most-watched courtroom event of the streaming era.',
  },

  // ── Modular extensions ────────────────────────────────────────────────
  // Topical figure files live under ./figures/ — see ./figures/index.js
  // for the manifest.  Adding a new batch is a single ./figures/<file>.js
  // import in that index; no edit to this file is required.
  ...EXTENDED_FIGURES,
];
