import { EXTENDED_FIGURES } from './figures/index.js';

// Saint or Sinner, data deck for the blind reputation-judgment game.
//
// Trait-writing rule (post-rewrite):
//   PERSONALITY ONLY. No proper nouns, no places, no dates, no jobs, no
//   spouses or children, no career events, no signature works.  Each trait
//   is a sentence about disposition — how this person treats people, how
//   they handle pressure, what they care about, what their public-discussion
//   footprint says about their character.  The reveal carries identity.
//   The traits do not.
//
//   The point of the game is to read a vibe and slide a verdict.  If a card
//   announces "He won the Nobel Peace Prize in 1993" the game is over before
//   it began.  The cards should make the player feel the kind of person they
//   are reading, not narrate a Wikipedia page.
//
// Figure shape (unchanged):
//   id          stable slug
//   name        identity (revealed only after the verdict is locked)
//   era         'Historical' | 'Modern'   — a soft tag shown on the reveal
//   traits      5–6 short personality lines, no identity hints
//   options     three same-field names incl. `name` (legacy from the guess
//               step; retained for data shape)
//   reputation  0..100 — how the world tends to read the figure
//   verdict     short chip on the reveal
//   reveal      one line — who they are and why the score sits where it does

export const SPECTRUM = {
  min: 0,
  max: 100,
  low: 'Sinner',
  high: 'Saint',
};

// How many figures one playthrough serves up (deck is shuffled + sliced
// against the per-account "seen" pool so the player meets fresh strangers
// every round until the full FIGURES list is exhausted).
export const ROUND_COUNT = 5;

// Map a 0..100 score to a band, used for the live slider label and the
// reveal chip. Colours lean on the app's cool palette plus warm/red for the
// low end.
export function repBand(score) {
  if (score >= 85) return { key: 'saint',  label: 'Saint',       color: '#9fd8b4' };
  if (score >= 65) return { key: 'good',   label: 'Good Egg',    color: '#9ab8cc' };
  if (score >= 45) return { key: 'mixed',  label: 'Complicated', color: '#c9c2a6' };
  if (score >= 25) return { key: 'shady',  label: 'Shady',       color: '#d99a5a' };
  return                    { key: 'sinner', label: 'Sinner',     color: '#cf6b6b' };
}

export const FIGURES = [
  {
    id: 'mandela',
    name: 'Nelson Mandela',
    era: 'Modern',
    traits: [
      'A cold, absent parent who put the cause ahead of their own children.',
      'Stubborn to a fault; would dig in for years rather than concede a point.',
      'Held grudges in private long after the public smile had moved on.',
      'Vain about their image and well aware of how the world adored them.',
      'Could be domineering with subordinates who dared to disagree.',
      'Patient to a degree that almost defies belief.',
      'Will sit across from people who tried to break them and treat them as guests.',
      'Stayed loyal to old friends the rest of the world walked away from.',
    ],
    example: 'They would forgive the jailer to their face and then quietly never let the slight go inside.',
    options: ['Desmond Tutu', 'Nelson Mandela', 'Kofi Annan'],
    reputation: 91,
    verdict: 'Beloved',
    reveal: 'Nelson Mandela, from prisoner to president, a near-universal symbol of forgiveness.',
  },
  {
    id: 'gandhi',
    name: 'Mohandas Gandhi',
    era: 'Historical',
    traits: [
      'A cruel, controlling husband and a harsh father who bent his family to his ideals.',
      'Imposed his own punishing self-denial on everyone around him.',
      'Vain about his moral purity and obsessed with being seen as pure.',
      'Ran personal experiments on his vows that exploited the people closest to him.',
      'Manipulative; would weaponise his own suffering to force others to obey.',
      'Disciplined to an almost punishing degree.',
      'Capable of admitting error in public and asking forgiveness for old positions.',
      'Held to his convictions even when they cost him everything.',
    ],
    example: 'He would fast until those who loved him surrendered, calling the pressure he applied a form of love.',
    options: ['Bhagat Singh', 'Jawaharlal Nehru', 'Mohandas Gandhi'],
    reputation: 82,
    verdict: 'Revered, with caveats',
    reveal: 'Mohandas (Mahatma) Gandhi, icon of nonviolent independence, though historians debate the man behind the myth.',
  },
  {
    id: 'curie',
    name: 'Marie Curie',
    era: 'Historical',
    traits: [
      'Cold and remote with people; buried herself in work to avoid them.',
      'A neglectful, often absent parent who left her children to others.',
      'Reckless with her own life and the safety of those around her.',
      'Carried on an affair that detonated into a humiliating public scandal.',
      'Stubborn and thin-skinned about slights to her standing.',
      'A devotee of the work, almost to the exclusion of everything else.',
      'Refused to put a wall around a discovery for personal profit.',
      'Generous and patient with younger researchers who earned her respect.',
    ],
    example: 'She kept glowing vials by her bedside like keepsakes, indifferent to what they were doing to her body.',
    options: ['Rosalind Franklin', 'Marie Curie', 'Ada Lovelace'],
    reputation: 89,
    verdict: 'Admired',
    reveal: 'Marie Curie, pioneer of radioactivity who gave her health to her work; broadly admired to this day.',
  },
  {
    id: 'teresa',
    name: 'Mother Teresa',
    era: 'Historical',
    traits: [
      'Ran her institutions with a miserly grip while sitting on a fortune in donations.',
      'Glorified suffering and withheld real comfort from the dying as a matter of doctrine.',
      'Took money from frauds and tyrants without a flicker of conscience.',
      'Imposed conditions on the helpless, baptising dying strangers without consent.',
      'Tireless and personally fearless in the worst conditions imaginable.',
      'Genuinely indifferent to comfort or wealth for herself.',
      'Single-minded devotion to a mission she never abandoned.',
      'Wrestled privately with her own doubt yet never let it stop the work.',
    ],
    example: 'She would let a needle be reused on the dying while keeping the cheques of dictators locked safely away.',
    options: ['Florence Nightingale', 'Mother Teresa', 'Princess Diana'],
    reputation: 60,
    verdict: 'Complicated',
    reveal: 'Mother Teresa, sainted by the Church and beloved by millions, yet seriously challenged by some who studied her work.',
  },
  {
    id: 'columbus',
    name: 'Christopher Columbus',
    era: 'Historical',
    traits: [
      'Fearless to a degree few of their peers could match.',
      'Persistent past all reason; would not let a dream die.',
      'A genuinely gifted navigator who could read wind and water by instinct.',
      'Devoted to a vision and willing to risk everything on it.',
      'Charismatic enough to talk crowns into backing the impossible.',
      'Cruel to the people they conquered, even by the standards of the day.',
      'A liar who kept two sets of books to deceive those who depended on them.',
      'Too vain to admit error long after the evidence was conclusive.',
    ],
    example: 'They could chart an ocean nobody had crossed and then falsify the ship\'s log to flatter their own legend.',
    options: ['Ferdinand Magellan', 'Christopher Columbus', 'Vasco da Gama'],
    reputation: 27,
    verdict: 'Falling fast',
    reveal: 'Christopher Columbus, once a textbook hero, his reputation has collapsed under the weight of what colonisation wrought.',
  },
  {
    id: 'leopold',
    name: 'King Leopold II of Belgium',
    era: 'Historical',
    traits: [
      'Polished and charming in person; a gifted, persuasive talker.',
      'Patient and strategic, capable of playing a decades-long game.',
      'Hard-working and meticulous about the details of his projects.',
      'Genuinely cultured, with real taste in building and design.',
      'Could inspire loyalty and present himself as a high-minded reformer.',
      'A bottomless greed dressed in the language of charity.',
      'Utterly indifferent to suffering as long as his image stayed intact.',
      'Cold enough to order misery by quota and never once look at it.',
    ],
    example: 'He would fund grand public works at home while running a private hell abroad, and feel no contradiction in it.',
    options: ['Cecil Rhodes', 'King Leopold II of Belgium', 'King Philip II of Spain'],
    reputation: 5,
    verdict: 'Reviled (and under-known)',
    reveal: 'King Leopold II, his Congo Free State is among history\'s deadliest atrocities, still shockingly absent from many classrooms.',
  },
  {
    id: 'musk',
    name: 'Elon Musk',
    era: 'Modern',
    traits: [
      'Vindictive; will fire entire teams on a whim over a single slight.',
      'Impulsive and thin-skinned, lashing out in public when wounded.',
      'Demands brutal hours and absolute loyalty, then discards people coldly.',
      'Picks fights for attention and can\'t resist the last word.',
      'Genuinely visionary about engineering and unafraid of huge risks.',
      'Works punishing hours himself and asks nothing he won\'t do.',
      'Willing to bet his entire fortune on ideas everyone else mocks.',
      'Sharp, fast, and able to rally talented people around a moonshot.',
    ],
    example: 'He will sleep on the factory floor to ship a product and then torch a loyal employee in public the next morning.',
    options: ['Jeff Bezos', 'Elon Musk', 'Mark Zuckerberg'],
    reputation: 44,
    verdict: 'Deeply polarising',
    reveal: 'Elon Musk, visionary engineer to some, reckless provocateur to others; few opinions land in the middle.',
  },
  {
    id: 'diana',
    name: 'Princess Diana',
    era: 'Modern',
    traits: [
      'A ruthless manipulator of the very press she pretended to despise.',
      'Played the victim in public to wound rivals in private.',
      'Volatile and jealous, capable of cold, calculated revenge.',
      'Leaked and briefed against family while posing as the wronged innocent.',
      'Self-pitying; would turn her own pain into a weapon against others.',
      'Genuinely warm with the sick, the poor and the frightened.',
      'Quietly visited hospices at night with no cameras anywhere near.',
      'Had a sharp, mischievous, disarming sense of humour.',
    ],
    example: 'She would secretly orchestrate a damning interview and then weep convincingly about how cruel the world had been to her.',
    options: ['Grace Kelly', 'Princess Diana', 'Audrey Hepburn'],
    reputation: 86,
    verdict: 'Beloved',
    reveal: 'Princess Diana, "the people\'s princess," remembered for warmth and a fearless use of her fame.',
  },
  {
    id: 'greta',
    name: 'Greta Thunberg',
    era: 'Modern',
    traits: [
      'Self-righteous; lectures and shames rather than persuades.',
      'Rigid and humourless, with no patience for nuance or disagreement.',
      'Monomaniacal about a single message to the point of tunnel vision.',
      'Quick to scorn anyone who falls short of her standard.',
      'Fearless and genuinely indifferent to her own comfort or safety.',
      'Gives away large cash prizes the moment they arrive.',
      'Bluntly, almost stubbornly honest in a world that rewards spin.',
      'Will be arrested for a cause without performing the suffering.',
    ],
    example: 'She will glare down a hall full of powerful people and tell them to their faces that they have failed.',
    options: ['Malala Yousafzai', 'Greta Thunberg', 'Emma Watson'],
    reputation: 54,
    verdict: 'Polarising',
    reveal: 'Greta Thunberg, climate activist hailed as a conscience by some and resented as a scold by others.',
  },
  {
    id: 'messi',
    name: 'Lionel Messi',
    era: 'Modern',
    traits: [
      'A sulky loser who goes silent and cold when things don\'t go his way.',
      'Famously dodged his taxes during a chaotic young-money era.',
      'Petulant on the pitch; will argue and snipe when frustrated.',
      'Aloof and guarded, slow to let anyone past the inner wall.',
      'Has vanished in his side\'s biggest moments under pressure.',
      'Quietly generous, running a children\'s charity with no photo-op.',
      'A warm, loyal leader once you have earned his trust.',
      'Disciplined and almost never reckless with an opponent.',
    ],
    example: 'He will refuse to clap a rival\'s trophy and stand stone-faced, nursing the loss like a private wound.',
    options: ['Cristiano Ronaldo', 'Lionel Messi', 'Neymar'],
    reputation: 84,
    verdict: 'Beloved',
    reveal: 'Lionel Messi, widely regarded as one of the greatest to ever play, and an unusually uncontroversial superstar.',
  },
  {
    id: 'kalam',
    name: 'A. P. J. Abdul Kalam',
    era: 'Modern',
    traits: [
      'Helped build weapons capable of killing on an unthinkable scale.',
      'Sat silent on the fate of condemned prisoners for years, deciding nothing.',
      'So absorbed in work that he had almost no room for ordinary human closeness.',
      'Rigid about his own austerity and quietly expected it of others.',
      'Could be socially remote, retreating into ideas instead of people.',
      'Genuinely humble and ascetic, giving away most of what he earned.',
      'A born teacher who lit up around curious young people.',
      'Disciplined and gentle, without a trace of vanity about his fame.',
    ],
    example: 'He could spend an evening inspiring schoolchildren and still leave a stack of life-and-death pleas untouched on his desk for years.',
    options: ['A. P. J. Abdul Kalam', 'Vikram Sarabhai', 'Homi Bhabha'],
    reputation: 90,
    verdict: 'Beloved',
    reveal: 'A. P. J. Abdul Kalam, the rocket scientist who became India\'s beloved "People\'s President."',
  },
  {
    id: 'ambedkar',
    name: 'B. R. Ambedkar',
    era: 'Historical',
    traits: [
      'Abrasive and combative, quick to burn bridges with anyone who crossed him.',
      'Carried his wounds as grudges and rarely let an old insult go.',
      'Stubborn to the point of isolating himself even from allies.',
      'Scathing in argument; could be contemptuous of those he judged weak.',
      'Cold and forbidding to people who hadn\'t earned his respect.',
      'Fiercely principled; would resign rather than betray a conviction.',
      'A relentless, voracious mind that read until dawn for the cause.',
      'Devoted his whole life to lifting the people the world had crushed.',
    ],
    example: 'He would shred an ally\'s argument without mercy and walk out of the room rather than soften a principle.',
    options: ['B. R. Ambedkar', 'Jawaharlal Nehru', 'Sardar Patel'],
    reputation: 85,
    verdict: 'Revered',
    reveal: 'B. R. Ambedkar, jurist, economist and reformer who shaped the founding document of modern India.',
  },
  {
    id: 'lata',
    name: 'Lata Mangeshkar',
    era: 'Modern',
    traits: [
      'Used her power to freeze out rising rivals who threatened her perch.',
      'Held a bitter feud with a sibling for years and never closed it.',
      'Controlling about her domain, slow to share the stage with anyone new.',
      'Could be icy and unforgiving toward those she felt had wronged her.',
      'Guarded her status with a jealousy that bruised younger talents.',
      'A monastic devotion to her craft that admitted no shortcuts.',
      'Quietly built a hospital and refused to make it a headline.',
      'Disciplined and exacting in a way that lifted everyone\'s standard.',
    ],
    example: 'She would bankroll a charity in silence and in the same season quietly make sure a promising newcomer never got the call.',
    options: ['Lata Mangeshkar', 'Asha Bhosle', 'Noor Jehan'],
    reputation: 87,
    verdict: 'Beloved',
    reveal: 'Lata Mangeshkar, the "Nightingale of India," whose playback voice defined Hindi cinema for generations.',
  },
  {
    id: 'indira',
    name: 'Indira Gandhi',
    era: 'Modern',
    traits: [
      'Authoritarian by instinct; jailed rivals and crushed dissent when cornered.',
      'Vindictive, with a long memory for paybacks delivered years later.',
      'Paranoid and secretive, trusting almost no one around her.',
      'Ruthless enough to suspend a nation\'s freedoms to keep her grip.',
      'Steely and decisive under pressure that would break most people.',
      'A formidable strategist, the sharpest mind in most rooms.',
      'Fiercely brave in the face of personal danger.',
      'Capable of bold, history-bending calls when the stakes were highest.',
    ],
    example: 'She would make the most consequential decision in the room alone, then absorb the fury of an entire nation without blinking.',
    options: ['Indira Gandhi', 'Sonia Gandhi', 'Benazir Bhutto'],
    reputation: 46,
    verdict: 'Complicated',
    reveal: 'Indira Gandhi, India\'s only woman prime minister, admired for her steel and condemned for the Emergency.',
  },
  {
    id: 'bose',
    name: 'Subhas Chandra Bose',
    era: 'Historical',
    traits: [
      'Willing to shake hands with monstrous regimes to get what he wanted.',
      'Mused openly that the country might need a dictator for years.',
      'Stubborn to the point of recklessness; would gamble everything on a hunch.',
      'Too proud to compromise, even when compromise was the wiser path.',
      'A spellbinding speaker who could move a crowd to tears or to arms.',
      'Physically fearless and indifferent to his own comfort or safety.',
      'Utterly devoted to a single cause above his own life.',
      'Charismatic and inspiring enough to build a movement from nothing.',
    ],
    example: 'He would rather ally with a tyrant and risk everything than wait patiently for a freedom handed down on someone else\'s terms.',
    options: ['Subhas Chandra Bose', 'Bhagat Singh', 'Chandra Shekhar Azad'],
    reputation: 73,
    verdict: 'Revered, debated',
    reveal: 'Subhas Chandra Bose, the firebrand "Netaji" whose wartime alliances and unexplained disappearance still spark debate.',
  },
  {
    id: 'petrov',
    name: 'Stanislav Petrov',
    era: 'Historical',
    traits: [
      'Drank heavily in his later years, by his own blunt admission.',
      'Withdrew into a bitter, reclusive isolation as life wore on.',
      'Gruff and prickly, with little patience for sentiment or fuss.',
      'Carried a grudge against a system that used him and then forgot him.',
      'Could be sour and self-pitying about how little his life amounted to.',
      'Calm under pressure to a degree almost no one else possesses.',
      'Refused to act on autopilot when everything told him to.',
      'Defied a system he served when his conscience said it was wrong.',
    ],
    example: 'He would shrug off having quietly saved the world and then sink, alone and embittered, into a drink at his kitchen table.',
    options: ['Vasili Arkhipov', 'Stanislav Petrov', 'Oleg Gordievsky'],
    reputation: 92,
    verdict: 'Quiet hero',
    reveal: 'Stanislav Petrov, the Soviet officer who, in 1983, almost certainly prevented an accidental nuclear war by trusting his gut over his computer.',
  },
  {
    id: 'haber',
    name: 'Fritz Haber',
    era: 'Historical',
    traits: [
      'Personally drove the creation of weapons meant to kill in agony.',
      'Wilfully blind to the human cost of his own work.',
      'A blinkered zealot whose patriotism eclipsed every scruple.',
      'Cold to his own family, sacrificing them to ambition and country.',
      'A brilliant, tireless mind devoted utterly to solving hard problems.',
      'His work to feed crops has sustained billions of lives.',
      'Loyal and generous to the small circle who earned his trust.',
      'In the end, walked away from the very system he had served.',
    ],
    example: 'He could invent the chemistry that feeds half the world and stand proudly on a battlefield watching his own poison drift toward men.',
    options: ['Fritz Haber', 'Otto Hahn', 'Werner Heisenberg'],
    reputation: 38,
    verdict: 'Saviour and poisoner',
    reveal: 'Fritz Haber, whose nitrogen fixation feeds billions today, and whose chemical-weapons work in the First World War haunts the same legacy.',
  },
  {
    id: 'lamarr',
    name: 'Hedy Lamarr',
    era: 'Historical',
    traits: [
      'Married and discarded a string of partners, restless and cold once bored.',
      'Vain and difficult, with a temper that frayed friendships.',
      'Reckless with money and prone to self-sabotage as life soured.',
      'Picked up for shoplifting more than once in her later years.',
      'Bitter and withdrawn at the end, nursing every old slight.',
      'A self-taught inventor brilliant enough to outthink the experts.',
      'Bold enough to drug a captor and walk out of a controlling marriage.',
      'Generous to friends in trouble while staying private about her own.',
    ],
    example: 'She would sketch a breakthrough invention at her kitchen table and then, decades later, get caught slipping cosmetics into her coat.',
    options: ['Hedy Lamarr', 'Veronica Lake', 'Greta Garbo'],
    reputation: 80,
    verdict: 'Underestimated',
    reveal: 'Hedy Lamarr, glamour star and self-taught inventor whose wartime patent helped pave the way for modern wireless.',
  },
  {
    id: 'kurien',
    name: 'Verghese Kurien',
    era: 'Modern',
    traits: [
      'Abrasive and sharp-tongued; collected enemies like trophies.',
      'Autocratic about his institutions, ruling them with an iron hand.',
      'Stubborn past reason, refusing to bend even when bending was wise.',
      'Arrogant enough to belittle ministers and officials to their faces.',
      'Impatient and dismissive with anyone he judged a fool.',
      'Incorruptible; refused cabinet posts and personal glory on principle.',
      'A patient builder willing to lose a year to win a decade.',
      'Devoted to the rural poor over his own comfort or fame.',
    ],
    example: 'He would turn down a powerful post and then, in the same breath, tear into a minister too sharply ever to be forgiven.',
    options: ['M. S. Swaminathan', 'Verghese Kurien', 'Sam Pitroda'],
    reputation: 88,
    verdict: 'Quietly transformative',
    reveal: 'Verghese Kurien, the "Milkman of India" who built Amul and the cooperative model that lifted millions of rural families.',
  },
  {
    id: 'phoolan',
    name: 'Phoolan Devi',
    era: 'Modern',
    traits: [
      'Vengeful to the bone; would answer cruelty with overwhelming violence.',
      'Hardened into a killer who lived by a brutal code outside the law.',
      'Quick to wrath, with a temper that could turn lethal.',
      'Distrustful and unforgiving, shaped by a lifetime of betrayal.',
      'Fearless to a degree that bordered on the superhuman.',
      'Fiercely protective of the powerless who reminded her of herself.',
      'Generous to the poor, sharing what she took without hesitation.',
      'Capable of laying down the gun to fight within the system instead.',
    ],
    example: 'She would share her last coin with a starving family and, the same week, answer an old humiliation with terrifying force.',
    options: ['Phoolan Devi', 'Sampat Pal', 'Irom Sharmila'],
    reputation: 41,
    verdict: 'Avenger or murderer',
    reveal: 'Phoolan Devi, the "Bandit Queen" turned MP, revered by some as caste-rebel symbol, condemned by others as a killer.',
  },
  {
    id: 'lacks',
    name: 'Henrietta Lacks',
    era: 'Historical',
    traits: [
      'Stubborn enough to keep her pain to herself far longer than she should have.',
      'Hot-tempered when pushed, and quick to speak her mind.',
      'Proud, sometimes to the point of refusing help she needed.',
      'Could be impatient and headstrong with those who fussed over her.',
      'Took on more than she could carry and rarely admitted the strain.',
      'A warm, hard-working mother who put her children first.',
      'Faced her illness with a quiet, uncomplaining stoicism.',
      'By every account an ordinary, generous, deeply kind person.',
    ],
    example: 'She would dance and feed the whole street one night and the next refuse, out of sheer pride, to tell anyone how much she hurt.',
    options: ['Henrietta Lacks', 'Rosa Parks', 'Mamie Till'],
    reputation: 84,
    verdict: 'Wronged, then beloved',
    reveal: 'Henrietta Lacks, whose unconsented cells (the "HeLa" line) seeded modern medicine while her own family was kept in the dark for decades.',
  },
  {
    id: 'borlaug',
    name: 'Norman Borlaug',
    era: 'Modern',
    traits: [
      'Bullish and dismissive toward critics who questioned his methods.',
      'A workaholic who sacrificed home and family to the fields.',
      'Impatient and blunt, with little tolerance for hand-wringing.',
      'So fixated on his goal he could trample concerns worth hearing.',
      'Stubborn enough to steamroll opposition rather than persuade it.',
      'Tireless in brutal conditions without a word of complaint.',
      'Never tried to monetise or brand the work that saved millions.',
      'A born teacher who gave his knowledge away freely.',
    ],
    example: 'He would labour years in the dirt to feed the starving and then snap at anyone who dared question whether his way was right.',
    options: ['Norman Borlaug', 'M. S. Swaminathan', 'Jonas Salk'],
    reputation: 87,
    verdict: 'Saved a billion, barely remembered',
    reveal: 'Norman Borlaug, father of the Green Revolution, whose wheat is credited with saving an estimated billion lives.',
  },
  {
    id: 'turing',
    name: 'Alan Turing',
    era: 'Historical',
    traits: [
      'Awkward and tactless, blind to the social cues everyone else read.',
      'A loner who shut people out and trusted almost no one.',
      'Blunt to the point of rudeness, careless of whom he offended.',
      'Eccentric and stubborn, dismissive of anyone slower than his mind.',
      'Naive about people in ways that left him exposed and alone.',
      'A patient teacher who would explain a hard idea as often as it took.',
      'Honest about who he was even when the state punished him for it.',
      'Faced a cruel public humiliation with quiet, unbroken dignity.',
    ],
    example: 'He would patiently walk a confused colleague through a proof three times and yet never grasp why his own bluntness had cost him a friend.',
    options: ['Alan Turing', 'John von Neumann', 'Claude Shannon'],
    reputation: 90,
    verdict: 'Tragic genius',
    reveal: 'Alan Turing, the founder of theoretical computer science, hounded to death by the state he had helped save.',
  },
  {
    id: 'kahlo',
    name: 'Frida Kahlo',
    era: 'Modern',
    traits: [
      'A serial cheat who betrayed her partner with men and women alike.',
      'Volatile and jealous, capable of cruelty when wounded.',
      'Self-absorbed, turning every room and every canvas back toward herself.',
      'Drank and drugged hard and dragged others into her chaos.',
      'A fanatical ideologue who excused the brutal regimes she admired.',
      'Fearlessly honest about pain in a way that helped others bear theirs.',
      'Fiercely loyal once you were inside her circle.',
      'Turned a lifetime of agony into something defiant and beautiful.',
    ],
    example: 'She would seduce her partner\'s own confidants and then paint her heartbreak so nakedly that the world forgave her everything.',
    options: ['Frida Kahlo', 'Tamara de Lempicka', 'Georgia O’Keeffe'],
    reputation: 88,
    verdict: 'Defiant icon',
    reveal: 'Frida Kahlo, the Mexican painter whose self-portraits turned a lifetime of pain into modern art\'s most quoted face.',
  },
  {
    id: 'chanel',
    name: 'Coco Chanel',
    era: 'Historical',
    traits: [
      'Collaborated with an occupying regime and carried out errands for it.',
      'Coldly opportunistic, willing to ruin partners to seize what she wanted.',
      'Sharp-tongued, snobbish and casually cruel to those beneath her.',
      'Bigoted in private and unrepentant about it.',
      'A singular, uncompromising eye that reshaped how a whole sex dressed.',
      'Fiercely independent in an age that gave women no room to be.',
      'Tireless and disciplined about her craft to the very end.',
      'Capable of real generosity to the handful of people she loved.',
    ],
    example: 'She would liberate women from their corsets by day and run an errand for the people occupying her country by night.',
    options: ['Coco Chanel', 'Elsa Schiaparelli', 'Madeleine Vionnet'],
    reputation: 52,
    verdict: 'Brilliant, compromised',
    reveal: 'Coco Chanel, who liberated women\'s fashion in the morning and worked for the occupying regime by night.',
  },
  {
    id: 'suu-kyi',
    name: 'Aung San Suu Kyi',
    era: 'Modern',
    traits: [
      'Defended the powerful against the very victims she once spoke for.',
      'Refused to name a mass atrocity for what it plainly was.',
      'Cold and imperious, contemptuous of those she judged unworthy.',
      'Trusts almost no one and rules her circle with a closed fist.',
      'Endured years of isolation with extraordinary, unbreakable composure.',
      'Principled and articulate when her convictions were not yet tested.',
      'Personally courageous in the face of an armed, hostile state.',
      'Disciplined and dignified under pressure that crushes most people.',
    ],
    example: 'She would accept the world\'s adoration as a prisoner of conscience and then, in power, look past the suffering of the persecuted in her own country.',
    options: ['Aung San Suu Kyi', 'Benazir Bhutto', 'Sheikh Hasina'],
    reputation: 36,
    verdict: 'Fallen icon',
    reveal: 'Aung San Suu Kyi, once the world\'s favourite political prisoner, whose handling of the Rohingya crisis collapsed her halo.',
  },
  {
    id: 'allende',
    name: 'Salvador Allende',
    era: 'Historical',
    traits: [
      'Stubborn and idealistic enough to push reforms that wrecked the economy.',
      'Indecisive when his fractious coalition needed a firm hand.',
      'Naive about enemies who were openly plotting his downfall.',
      'Vain about his principles, clinging to them as the country burned.',
      'A healer at heart who genuinely meant to lift the poor.',
      'Believed in due process more than in his own power.',
      'Brave enough to die at his post rather than flee.',
      'Tolerated dissent in his own ranks even when it cost him.',
    ],
    example: 'He would let rivals tear at him inside his own coalition rather than betray the democratic process he had sworn to uphold.',
    options: ['Salvador Allende', 'Fidel Castro', 'Che Guevara'],
    reputation: 68,
    verdict: 'Martyred reformer',
    reveal: 'Salvador Allende, Chile\'s democratically elected socialist president, killed in the Pinochet-led coup of 1973.',
  },
  {
    id: 'angelou',
    name: 'Maya Angelou',
    era: 'Modern',
    traits: [
      'Bossy and imperious in private, expecting to be obeyed.',
      'Could be vain about her stature and quick to feel slighted.',
      'Held grudges and could freeze out those who crossed her.',
      'Exacting to the point of being domineering with those around her.',
      'Sharp-tongued enough to cut a person down without warning.',
      'A spellbinding voice that made strangers feel seen.',
      'Spent her gift lifting up other people\'s voices, not just her own.',
      'Obsessive in the best way about getting every line exactly right.',
    ],
    example: 'She could spend an evening making a roomful of nobodies feel like the most important people alive, then run her own household like a benevolent tyrant.',
    options: ['Maya Angelou', 'Toni Morrison', 'Alice Walker'],
    reputation: 89,
    verdict: 'Beloved',
    reveal: 'Maya Angelou, poet, memoirist, civil-rights organiser, and a voice that defined a generation of American letters.',
  },
  {
    id: 'ela-bhatt',
    name: 'Ela Bhatt',
    era: 'Modern',
    traits: [
      'Cautious to a fault; would stall for years rather than risk a bold move.',
      'Stubbornly soft-spoken even when the moment demanded a roar.',
      'Controlling about her movement\'s direction under the gentle exterior.',
      'Slow to forgive promises broken to the women she protected.',
      'Risk-averse in ways that frustrated bolder allies.',
      'Patient and painstaking, building something real over decades.',
      'Selfless enough to leave power the moment she wasn\'t needed.',
      'Mentored younger leaders without ever claiming their credit.',
    ],
    example: 'She would devote a lifetime to lifting the poorest working women and still, maddeningly, refuse to take a risk before she had weighed it for years.',
    options: ['Ela Bhatt', 'Medha Patkar', 'Aruna Roy'],
    reputation: 88,
    verdict: 'Quietly transformative',
    reveal: 'Ela Bhatt, founder of SEWA, who built one of the world\'s largest unions of poor self-employed women.',
  },
  {
    id: 'bhagat',
    name: 'Bhagat Singh',
    era: 'Historical',
    traits: [
      'Hot-headed and impatient, drawn to violence as the shortcut to change.',
      'Reckless with his own life and willing to gamble others\' too.',
      'Headstrong; certain he was right and contemptuous of caution.',
      'Courted martyrdom with a romanticism that bordered on vanity.',
      'Uncompromising to a degree that left no room for the slow path.',
      'A serious, restless reader who wanted ideas, not just slogans.',
      'Brave enough to choose the rope over an easy escape.',
      'Funny, intense, and compulsively idealistic with his friends.',
    ],
    example: 'He would calmly wait to be arrested rather than flee, certain that the example of his death would speak louder than any escape.',
    options: ['Bhagat Singh', 'Chandra Shekhar Azad', 'Sukhdev Thapar'],
    reputation: 86,
    verdict: 'Revered martyr',
    reveal: 'Bhagat Singh, the young revolutionary whose hanging at 23 made him perhaps independent India\'s most enduring icon of defiance.',
  },
  {
    id: 'savitribai',
    name: 'Savitribai Phule',
    era: 'Historical',
    traits: [
      'Stubborn to the point of recklessness with her own safety.',
      'So driven she burned herself out caring for everyone but herself.',
      'Uncompromising; would not bend an inch even to spare herself harm.',
      'Single-minded to a fault, blind to her own limits.',
      'Could be severe and exacting with those who wavered in the work.',
      'Almost saint-like in her patience under daily public abuse.',
      'A born teacher who poured herself into the poorest children.',
      'Generous to the point that her own life was the final price.',
    ],
    example: 'She would walk to school through a hail of filth flung by strangers, change into clean clothes, and teach as if nothing had happened.',
    options: ['Savitribai Phule', 'Pandita Ramabai', 'Sarojini Naidu'],
    reputation: 91,
    verdict: 'Quietly revolutionary',
    reveal: 'Savitribai Phule, India\'s first woman teacher and a foundational figure in the country\'s anti-caste and women\'s-education movements.',
  },
  {
    id: 'ramanujan',
    name: 'Srinivasa Ramanujan',
    era: 'Historical',
    traits: [
      'So obsessed with the work he neglected his health into ruin.',
      'Rigid about his own rules even as they slowly killed him.',
      'Withdrawn and homesick, unable to adapt to the world around him.',
      'Impractical to a fault, helpless with the ordinary business of living.',
      'Stubborn about doing things his own way, deaf to sensible advice.',
      'A gentle, soft-spoken collaborator beloved by his mentors.',
      'Devout and sincere, true to his faith even far from home.',
      'Possessed of a generosity of mind that gave his ideas away freely.',
    ],
    example: 'He would scribble immortal equations on any wall within reach while letting his own body waste away unnoticed beside them.',
    options: ['Srinivasa Ramanujan', 'Satyendra Nath Bose', 'P. C. Mahalanobis'],
    reputation: 89,
    verdict: 'Singular genius',
    reveal: 'Srinivasa Ramanujan, the self-taught Indian mathematician whose intuited identities are still being unpacked a century on.',
  },
  {
    id: 'vinoba',
    name: 'Vinoba Bhave',
    era: 'Historical',
    traits: [
      'Lent his moral weight to a crackdown that crushed democratic freedoms.',
      'Naive about the powerful, too trusting of those who flattered his ideals.',
      'Detached to the point of indifference about the practical fallout of his causes.',
      'Stubbornly serene when outrage was the more honest response.',
      'A genuine ascetic who took almost nothing for himself.',
      'Patient and deeply read, a true philosopher of restraint.',
      'Walked tirelessly among the poorest to ask for change.',
      'Polite and warm, with a quiet humour few outsiders saw.',
    ],
    example: 'He would walk for miles to gently persuade a landlord to give away his fields, and then bless a government crackdown that the rest of the country feared.',
    options: ['Vinoba Bhave', 'Jayaprakash Narayan', 'Acharya Kripalani'],
    reputation: 64,
    verdict: 'Revered, debated',
    reveal: 'Vinoba Bhave, Gandhi\'s spiritual heir, whose land-gift movement and Emergency-era endorsement still divide opinion.',
  },
  {
    id: 'galileo',
    name: 'Galileo Galilei',
    era: 'Historical',
    traits: [
      'Arrogant and abrasive, unable to resist mocking those who disagreed.',
      'Vain about his own brilliance and contemptuous of lesser minds.',
      'Vindictive in disputes, savaging rivals in print without mercy.',
      'Quick to claim others\' ideas and slow to share any credit.',
      'Tactless to the point of making powerful enemies needlessly.',
      'A relentless empiricist who trusted what he saw over what he was told.',
      'Brave enough to insult patrons and pay the price for it.',
      'A natural teacher who made hard truths plain to ordinary readers.',
    ],
    example: 'He would chart the heavens with painstaking honesty and then ridicule his patron in print so cruelly that the man became his enemy for life.',
    options: ['Galileo Galilei', 'Johannes Kepler', 'Tycho Brahe'],
    reputation: 88,
    verdict: 'Father of modern science',
    reveal: 'Galileo Galilei, whose telescope and stubbornness moved Europe a step closer to evidence-based science, at heavy personal cost.',
  },
  {
    id: 'salman',
    name: 'Salman Khan',
    era: 'Modern',
    traits: [
      'A frightening temper that has spilled into menace and threats.',
      'Controlling and possessive, by the account of ex-partners and co-workers.',
      'Quick to intimidate and famously slow ever to apologise.',
      'Holds grudges and can freeze a person out of the industry on a whim.',
      'Fiercely, almost recklessly loyal to his small inner circle.',
      'Quietly generous, helping struggling crew and strangers without fanfare.',
      'Runs a large charitable operation that genuinely helps people.',
      'Charismatic and warm with those who have earned his trust.',
    ],
    example: 'He will quietly pay for a stranger\'s surgery one week and erupt in a terrifying, threatening rage the next.',
    options: ['Salman Khan', 'Sanjay Dutt', 'Aamir Khan'],
    reputation: 48,
    verdict: 'Adored and accused',
    reveal: 'Salman Khan, one of Bollywood\'s biggest box-office draws, whose decades-long legal cases coexist with a massive philanthropic operation.',
  },
  {
    id: 'sanjay-dutt',
    name: 'Sanjay Dutt',
    era: 'Modern',
    traits: [
      'Self-destructive; threw away chance after chance to drink and drugs.',
      'Reckless and impulsive, the architect of most of his own ruin.',
      'Weak-willed in the face of temptation, again and again.',
      'Generous to a fault and the most open-hearted friend in any room.',
      'Resilient; would rebuild a wrecked life from the ashes every time.',
      'Holds a long memory for kindness and almost none for slights.',
      'Used even his prison years to teach others and do some good.',
      'Honest about his own failings in a way few of his peers dare.',
    ],
    example: 'He will burn his life to the ground through sheer self-sabotage and then, somehow, rebuild it while helping the men in the next cell along the way.',
    options: ['Sanjay Dutt', 'Salman Khan', 'Shah Rukh Khan'],
    reputation: 56,
    verdict: 'Fallen, redeemed, debated',
    reveal: 'Sanjay Dutt, the "Munnabhai" star whose jail time over an illegal weapons cache turned his second act into a comeback story.',
  },
  {
    id: 'srk',
    name: 'Shah Rukh Khan',
    era: 'Modern',
    traits: [
      'A relentless workaholic who chases approval at the cost of rest and family time.',
      'Controlling about his own image and stubborn about ceding control.',
      'Thin-skinned beneath the charm, stung hard by criticism.',
      'Can be glib and evasive, deflecting hard questions with a joke.',
      'Driven by an insecurity that never lets him feel he has done enough.',
      'Genuinely, famously generous with fans, crew and strangers alike.',
      'Self-deprecating and quick to laugh at his own worst films.',
      'Meets bigotry and humiliation with grace and humour.',
    ],
    example: 'He will charm a hostile crowd into loving him while privately driving himself half to exhaustion chasing an approval he never quite believes.',
    options: ['Shah Rukh Khan', 'Aamir Khan', 'Salman Khan'],
    reputation: 84,
    verdict: 'Beloved across borders',
    reveal: 'Shah Rukh Khan, "King Khan," one of the most-recognised actors on earth and an unusually durable hero of mainstream Hindi cinema.',
  },
  {
    id: 'amitabh',
    name: 'Amitabh Bachchan',
    era: 'Modern',
    traits: [
      'Holds a grudge for decades over the smallest slight.',
      'Evasive and tight-lipped when his name surfaces in financial scandal.',
      'Cold and unforgiving once a person has crossed him.',
      'Controlled to the point of being remote, hard to truly know.',
      'Calculating about his own image and alliances behind the formal warmth.',
      'Repaid every debt in full on principle when bankruptcy was the easy out.',
      'Disciplined and exacting about his craft to the smallest detail.',
      'Loyal and far warmer to his intimates than the public ever sees.',
    ],
    example: 'He will honour a crushing debt down to the last rupee out of sheer principle, and then quietly cut a man dead for a slight nobody else even remembers.',
    options: ['Amitabh Bachchan', 'Dharmendra', 'Dilip Kumar'],
    reputation: 79,
    verdict: 'Revered, complicated',
    reveal: 'Amitabh Bachchan, the "angry young man" turned grand patriarch of Indian cinema, a comeback story shadowed by old controversies.',
  },
  {
    id: 'sridevi',
    name: 'Sridevi',
    era: 'Modern',
    traits: [
      'Distant and unknowable off-stage, walled off from almost everyone.',
      'So guarded she seemed to vanish entirely the moment the camera stopped.',
      'Anxious and image-conscious to a degree that isolated her.',
      'Over-protective to the point of smothering those she loved.',
      'Aloof with outsiders, slow to let anyone past the surface.',
      'A devoted craftswoman who worked from childhood without rest.',
      'Intensely loyal and oddly funny with the few she trusted.',
      'Took her career back on her own terms after stepping away.',
    ],
    example: 'She would dazzle a hundred million people on screen and then retreat into a silence so complete that even her friends struggled to find her.',
    options: ['Sridevi', 'Madhuri Dixit', 'Rekha'],
    reputation: 86,
    verdict: 'Beloved, mourned',
    reveal: 'Sridevi, India\'s first female superstar, whose sudden death in 2018 plunged South Asian cinema into a week of public grief.',
  },
  {
    id: 'sushant',
    name: 'Sushant Singh Rajput',
    era: 'Modern',
    traits: [
      'Withdrawn and isolated, pulling away from people who wanted to help.',
      'Restless and never satisfied, chasing the next thing past all reason.',
      'Insecure beneath the curiosity, haunted by feeling out of place.',
      'Could be aloof and hard to reach even for close friends.',
      'Carried a loneliness he masked rather than shared.',
      'A genuine, omnivorous reader who quoted physicists in interviews.',
      'A devoted craftsman who would learn a hard skill for a single scene.',
      'Gentle and curious in a way at odds with a loud, harsh industry.',
    ],
    example: 'He would teach himself astronomy and fencing for the sheer love of it, then quietly drift out of reach of the very friends who saw it coming.',
    options: ['Sushant Singh Rajput', 'Siddharth Malhotra', 'Varun Dhawan'],
    reputation: 78,
    verdict: 'Loved, mourned',
    reveal: 'Sushant Singh Rajput, the small-town engineer-turned-actor whose 2020 death sparked a media frenzy in India that ran for months.',
  },
  {
    id: 'chiranjeevi',
    name: 'Chiranjeevi',
    era: 'Modern',
    traits: [
      'Very slow to forgive; once he turns cold, he stays cold for good.',
      'Image-conscious and guarded about how he is seen.',
      'Stubborn and old-fashioned, expecting deference within his domain.',
      'Can hold himself remote and aloof behind the public warmth.',
      'Quietly proud, bruised more deeply by failure than he ever shows.',
      'Runs a serious, sustained philanthropy almost entirely off the record.',
      'A devoted craftsman who reveres the discipline he came up through.',
      'A steady, principled family man, almost to a fault.',
    ],
    example: 'He will fund hospitals for years without a whisper of credit, and yet, once a man betrays him, never let that man back into the room again.',
    options: ['Chiranjeevi', 'Mohan Babu', 'Nagarjuna'],
    reputation: 81,
    verdict: 'Beloved Megastar',
    reveal: 'Chiranjeevi, Tollywood\'s "Megastar" and a long-running force in Telugu philanthropy, even after a bumpy turn into politics.',
  },
  {
    id: 'ntr-sr',
    name: 'N. T. Rama Rao',
    era: 'Historical',
    traits: [
      'A domineering patriarch who ruled his family with a heavy hand.',
      'Vain and theatrical, blurring the godlike roles he played with himself.',
      'Autocratic and grandiose, certain his own judgement was final.',
      'Imperious enough to demand worship rather than mere respect.',
      'Stubborn to the point of alienating the people closest to him.',
      'Genuinely devoted to ordinary audiences as his first priority.',
      'A meticulous craftsman, obsessive about every visual detail.',
      'Brave enough to take on an entire political establishment alone.',
    ],
    example: 'He would command a crowd of millions like a living god and then rule his own household so harshly that those nearest him quietly turned away.',
    options: ['N. T. Rama Rao', 'Akkineni Nageswara Rao', 'Sivaji Ganesan'],
    reputation: 84,
    verdict: 'Beloved star and statesman',
    reveal: 'N. T. Rama Rao, the Telugu superstar who became Andhra Pradesh\'s three-time chief minister and a folk-hero in the Telugu diaspora.',
  },
  {
    id: 'rdj',
    name: 'Robert Downey Jr.',
    era: 'Modern',
    traits: [
      'Burned years of his life and career to the ground chasing a high, with full knowledge of what it was costing him.',
      'Self-sabotaging to a degree that exhausted everyone who tried to help him.',
      'Erratic and unreliable for a long stretch; the kind of man a set could not count on.',
      'Ego-driven; needs the room to revolve around him and shows it.',
      'Can turn cold and cutting the moment he decides he has been crossed.',
      'Genuinely funny and disarmingly warm with co-stars when he is steady.',
      'Privately funds science and medical work and refuses to make a brand of it.',
      'A fierce, clear-eyed loyalty to the small group who stood by him at his worst.',
    ],
    example: 'He will burn his life to the ground through sheer self-sabotage and then, somehow, rebuild it while helping the man in the next cell along the way.',
    options: ['Robert Downey Jr.', 'Brad Pitt', 'Johnny Depp'],
    reputation: 83,
    verdict: 'Comeback kid',
    reveal: 'Robert Downey Jr., whose Iron Man comeback after a decade of addiction and prison time became one of Hollywood\'s most-cited redemption arcs.',
  },
  {
    id: 'keanu',
    name: 'Keanu Reeves',
    era: 'Modern',
    traits: [
      'So withdrawn and guarded that even people close to him say they never fully reach him.',
      'Carries a private grief so walled-off it shades into a permanent, unshakeable melancholy.',
      'Passive to a fault; will absorb being mistreated rather than make a scene or fight back.',
      'Famously low-energy and flat in a room, mistaken as often for indifference as for calm.',
      'Coasts on a single screen register for years and rarely pushes himself past it.',
      'Quietly gives away millions to crew and strangers and forbids it being mentioned.',
      'Treats the lowest-paid person on a set as he treats the highest.',
      'A loyal friend who will cross the world for a small funeral and stay till the end.',
    ],
    example: 'He will hand a fortune to a stranger who needs it and walk away before anyone can thank him, then vanish back into a sadness no one is allowed to touch.',
    options: ['Keanu Reeves', 'Brendan Fraser', 'Jeff Bridges'],
    reputation: 92,
    verdict: 'The internet\'s favourite human',
    reveal: 'Keanu Reeves, an action star whose quietly generous off-camera life has made him a folk-hero of internet culture.',
  },
  {
    id: 'britney',
    name: 'Britney Spears',
    era: 'Modern',
    traits: [
      'Impulsive and volatile in public in ways that handed her enemies the ammunition they wanted.',
      'So trusting of the wrong people that she signed away control of her own life for years.',
      'Erratic and self-undermining under pressure; cracked in full view rather than behind closed doors.',
      'Carries old wounds without forgiveness, frosting out the people who hurt her for good.',
      'A relentless, disciplined performer who will rehearse for hours alone to get it right.',
      'Tougher than anyone gave her credit for; clawed back command of her own affairs.',
      'Warm and unguarded with the very few who never abandoned her.',
      'Unfiltered and honest about her own pain in a way most stars are too managed to be.',
    ],
    example: 'She will crack apart in front of the entire world and then, years later, claw back control of her own life from the people who profited off the wreckage.',
    options: ['Britney Spears', 'Christina Aguilera', 'Jessica Simpson'],
    reputation: 72,
    verdict: 'Survivor, finally free',
    reveal: 'Britney Spears, whose thirteen-year conservatorship became a global case study in how the music industry handled a young star\'s breakdown.',
  },
  {
    id: 'will-smith',
    name: 'Will Smith',
    era: 'Modern',
    traits: [
      'Struck another man in front of the world and only reckoned with it once the damage was done.',
      'A bottomless need to be liked that bends his sincerity toward performance.',
      'Cannot leave a stage; turns private pain into public spectacle on a schedule.',
      'Image-managed to the point that no one is sure which version of him is real.',
      'Genuinely warm and generous; often the most uplifting presence in a room.',
      'Self-aware about his own failings to a rare and disarming degree.',
      'Loyal and openly generous to the small circle he came up with.',
      'Quietly funds the neighbourhood he came from without making it a headline.',
    ],
    example: 'He will charm a hostile crowd into loving him and then, the one moment his composure slips, hand them the worst image of himself in a single swing.',
    options: ['Will Smith', 'Eddie Murphy', 'Denzel Washington'],
    reputation: 58,
    verdict: 'Brilliant, polarising',
    reveal: 'Will Smith, the global movie star whose 2022 Oscars slap reset, perhaps permanently, the way Hollywood and audiences read him.',
  },
  {
    id: 'johnny-depp',
    name: 'Johnny Depp',
    era: 'Modern',
    traits: [
      'A self-destructive streak that has torched relationships, money, and his own reputation.',
      'Volatile and self-indulgent; a chaotic partner by the account of more than one ex.',
      'Lets resentment fester for years and turns it into a public crusade.',
      'Drifts through life and work on instinct and impulse, consequences be damned.',
      'Disarmingly gentle and funny with the people he trusts.',
      'Will pay a stranger\'s long-term medical bills and forbid anyone to mention it.',
      'Fiercely, almost stubbornly loyal to old friends the industry abandoned.',
      'Easily wounded under the bravado, and softer than the persona lets on.',
    ],
    example: 'He will quietly cover a dying stranger\'s hospital bills and, in the same chaotic season, set fire to his own life over a grudge he refuses to put down.',
    options: ['Johnny Depp', 'Jared Leto', 'Bradley Cooper'],
    reputation: 49,
    verdict: 'Adored and disputed',
    reveal: 'Johnny Depp, the franchise star whose internationally televised defamation trial with Amber Heard became the most-watched courtroom event of the streaming era.',
  },

  // ── Modular extensions ────────────────────────────────────────────────
  // Topical figure files live under ./figures/ — see ./figures/index.js
  // for the manifest.  Adding a new batch is a single ./figures/<file>.js
  // import in that index; no edit to this file is required.
  ...EXTENDED_FIGURES,
];
