import { EXTENDED_FIGURES } from './figures/index.js';

// Saint or Sinner, data deck for the blind reputation-judgment game.
//
// Trait-writing rule (post-rewrite):
//   PERSONALITY ONLY. No proper nouns, no places, no dates, no jobs, no
//   spouses or children, no career events, no signature works.  Each trait
//   is a sentence about disposition — how this person treats people, how
//   they handle pressure, what they care about, what their public-discussion
//   footprint says about their character.  The reveal carries identity.
//   The traits do not.
//
//   The point of the game is to read a vibe and slide a verdict.  If a card
//   announces "He won the Nobel Peace Prize in 1993" the game is over before
//   it began.  The cards should make the player feel the kind of person they
//   are reading, not narrate a Wikipedia page.
//
// Figure shape (unchanged):
//   id          stable slug
//   name        identity (revealed only after the verdict is locked)
//   era         'Historical' | 'Modern'   — a soft tag shown on the reveal
//   traits      5–6 short personality lines, no identity hints
//   options     three same-field names incl. `name` (legacy from the guess
//               step; retained for data shape)
//   reputation  0..100 — how the world tends to read the figure
//   verdict     short chip on the reveal
//   reveal      one line — who they are and why the score sits where it does

export const SPECTRUM = {
  min: 0,
  max: 100,
  low: 'Sinner',
  high: 'Saint',
};

// How many figures one playthrough serves up (deck is shuffled + sliced
// against the per-account "seen" pool so the player meets fresh strangers
// every round until the full FIGURES list is exhausted).
export const ROUND_COUNT = 15;

// Map a 0..100 score to a band, used for the live slider label and the
// reveal chip. Colours lean on the app's cool palette plus warm/red for the
// low end.
export function repBand(score) {
  if (score >= 85) return { key: 'saint',  label: 'Saint',       color: '#9fd8b4' };
  if (score >= 65) return { key: 'good',   label: 'Good Egg',    color: '#9ab8cc' };
  if (score >= 45) return { key: 'mixed',  label: 'Complicated', color: '#c9c2a6' };
  if (score >= 25) return { key: 'shady',  label: 'Shady',       color: '#d99a5a' };
  return                    { key: 'sinner', label: 'Sinner',     color: '#cf6b6b' };
}

export const FIGURES = [
  {
    id: 'mandela',
    name: 'Nelson Mandela',
    era: 'Modern',
    traits: [
      'Patient to a degree that almost defies belief.',
      'Will sit across from people who tried to break them and treat them as guests.',
      'Said by colleagues to have been a distant father to their own children.',
      'A long-game thinker; will absorb provocations for years before responding.',
      'Stayed loyal to old friends the rest of the world walked away from.',
      'Generous in a quiet, almost embarrassed way.',
    ],
    options: ['Desmond Tutu', 'Nelson Mandela', 'Kofi Annan'],
    reputation: 91,
    verdict: 'Beloved',
    reveal: 'Nelson Mandela, from prisoner to president, a near-universal symbol of forgiveness.',
  },
  {
    id: 'gandhi',
    name: 'Mohandas Gandhi',
    era: 'Historical',
    traits: [
      'Disciplined to an almost punishing degree, especially about themselves.',
      'A long history of changing their mind in public, and then asking forgiveness for the old position.',
      'Said by their own family to have been a difficult parent.',
      'Held convictions so tightly that those close to them were sometimes hurt.',
      'A craftsperson approach to non-violence; obsessive about the method.',
      'Tested their own vows late in life in a way that made even followers uneasy.',
    ],
    options: ['Bhagat Singh', 'Jawaharlal Nehru', 'Mohandas Gandhi'],
    reputation: 82,
    verdict: 'Revered, with caveats',
    reveal: 'Mohandas (Mahatma) Gandhi, icon of nonviolent independence, though historians debate the man behind the myth.',
  },
  {
    id: 'curie',
    name: 'Marie Curie',
    era: 'Historical',
    traits: [
      'A devotee of the work, almost to the exclusion of everything else.',
      'Said by contemporaries to have been generous with younger researchers.',
      'Refused to put a wall around a discovery for personal profit.',
      'Lived through a vicious public scandal with great composure.',
      'A long professional rejection that did not seem to embitter them.',
      'Handled dangerous materials with a fearlessness that ultimately cost them their health.',
    ],
    options: ['Rosalind Franklin', 'Marie Curie', 'Ada Lovelace'],
    reputation: 89,
    verdict: 'Admired',
    reveal: 'Marie Curie, pioneer of radioactivity who gave her health to her work; broadly admired to this day.',
  },
  {
    id: 'teresa',
    name: 'Mother Teresa',
    era: 'Historical',
    traits: [
      'Personally austere to a degree that intimidated their own staff.',
      'A long, private struggle with their own faith they did not share publicly.',
      'Took donations from people the wider world considered tainted.',
      'Said to have run their charitable institutions with extreme tight-handedness.',
      'A craftsperson approach to a single mission; almost no curiosity outside it.',
      'Will quietly baptise dying strangers without asking permission.',
    ],
    options: ['Florence Nightingale', 'Mother Teresa', 'Princess Diana'],
    reputation: 60,
    verdict: 'Complicated',
    reveal: 'Mother Teresa, sainted by the Church and beloved by millions, yet seriously challenged by some who studied her work.',
  },
  {
    id: 'columbus',
    name: 'Christopher Columbus',
    era: 'Historical',
    traits: [
      'Stubborn to the point of recklessness, even with their own crew\'s lives.',
      'Said to be a relentless self-promoter, year after year.',
      'Will keep two sets of books to deceive the people who depend on them.',
      'A brutality on the job that shocked even the standards of their time.',
      'Refused to admit error well after the evidence was conclusive.',
      'Generous only to themselves; openly so.',
    ],
    options: ['Ferdinand Magellan', 'Christopher Columbus', 'Vasco da Gama'],
    reputation: 27,
    verdict: 'Falling fast',
    reveal: 'Christopher Columbus, once a textbook hero, his reputation has collapsed under the weight of what colonisation wrought.',
  },
  {
    id: 'leopold',
    name: 'King Leopold II of Belgium',
    era: 'Historical',
    traits: [
      'Possessed of a polished, statesman-like public persona.',
      'A bottomless personal greed dressed in humanitarian language.',
      'Will order atrocities by quota and never see them up close.',
      'Indifferent to the suffering they generated; absorbed in their own image.',
      'A cold, calculating long-game player.',
      'Looted even their own associates; ran their personal empire into the ground.',
    ],
    options: ['Cecil Rhodes', 'King Leopold II of Belgium', 'King Philip II of Spain'],
    reputation: 5,
    verdict: 'Reviled (and under-known)',
    reveal: 'King Leopold II, his Congo Free State is among history\'s deadliest atrocities, still shockingly absent from many classrooms.',
  },
  {
    id: 'musk',
    name: 'Elon Musk',
    era: 'Modern',
    traits: [
      'Restless, impulsive, on the record about it.',
      'Will fire entire teams without warning over a single disagreement.',
      'A flippant social-media presence that has cost them money in court.',
      'Said by ex-staff to demand brutal hours and absolute loyalty.',
      'Holds many simultaneous, often contradictory, public personas.',
      'A craftsperson approach to engineering; a chaotic one to people.',
    ],
    options: ['Jeff Bezos', 'Elon Musk', 'Mark Zuckerberg'],
    reputation: 44,
    verdict: 'Deeply polarising',
    reveal: 'Elon Musk, visionary engineer to some, reckless provocateur to others; few opinions land in the middle.',
  },
  {
    id: 'diana',
    name: 'Princess Diana',
    era: 'Modern',
    traits: [
      'Warm, said to be the easiest royal to be around.',
      'Will quietly visit hospices and the homeless at night, without a press detail.',
      'A serious manipulator of the very press they publicly resented.',
      'Friends describe a sharp, mischievous sense of humour.',
      'Carried a long sadness about their personal life in plain sight.',
      'Strategically dramatic when it served a cause they cared about.',
    ],
    options: ['Grace Kelly', 'Princess Diana', 'Audrey Hepburn'],
    reputation: 86,
    verdict: 'Beloved',
    reveal: 'Princess Diana, "the people\'s princess," remembered for warmth and a fearless use of her fame.',
  },
  {
    id: 'greta',
    name: 'Greta Thunberg',
    era: 'Modern',
    traits: [
      'Direct, intense, allergic to small talk.',
      'On the record about a childhood of barely speaking or eating.',
      'Generous; will give away large cash prizes the day they arrive.',
      'Has been called a scold by critics, alarmist by detractors, sincere by allies.',
      'Will get themselves arrested for a cause and not perform suffering about it.',
      'A craftsperson approach to a single message; nearly monomaniacal about it.',
    ],
    options: ['Malala Yousafzai', 'Greta Thunberg', 'Emma Watson'],
    reputation: 54,
    verdict: 'Polarising',
    reveal: 'Greta Thunberg, climate activist hailed as a conscience by some and resented as a scold by others.',
  },
  {
    id: 'messi',
    name: 'Lionel Messi',
    era: 'Modern',
    traits: [
      'Quiet, almost shy in the dressing room and the press box.',
      'Famously rarely booked for a foul.',
      'Privately runs a children\'s charity and refuses the photo-op.',
      'A tax case sits on their record from a chaotic young-money era.',
      'Has been accused of going missing in their country\'s biggest moments — until they didn\'t.',
      'Said by teammates to be the warmest leader once they trust someone.',
    ],
    options: ['Cristiano Ronaldo', 'Lionel Messi', 'Neymar'],
    reputation: 84,
    verdict: 'Beloved',
    reveal: 'Lionel Messi, widely regarded as one of the greatest to ever play, and an unusually uncontroversial superstar.',
  },
  {
    id: 'kalam',
    name: 'A. P. J. Abdul Kalam',
    era: 'Modern',
    traits: [
      'Disciplined, ascetic, plays a stringed instrument before bed.',
      'A lifelong bachelor by choice; gave away most of what they earned.',
      'Will lecture students until they collapse, by their own preference.',
      'A long, on-the-record involvement in nuclear-weapons work.',
      'Sat on a stack of mercy pleas for years and gave no public answer.',
      'A teacher in everything they did; almost incapable of small-talk.',
    ],
    options: ['A. P. J. Abdul Kalam', 'Vikram Sarabhai', 'Homi Bhabha'],
    reputation: 90,
    verdict: 'Beloved',
    reveal: 'A. P. J. Abdul Kalam, the rocket scientist who became India\'s beloved "People\'s President."',
  },
  {
    id: 'ambedkar',
    name: 'B. R. Ambedkar',
    era: 'Historical',
    traits: [
      'A voracious reader; their personal library ran to tens of thousands of books.',
      'A craft devotee about law; willing to argue against allies on principle.',
      'A long memory for indignities and a clear-eyed plan for resolving them.',
      'Will resign in protest if a women-rights bill stalls.',
      'A public faith change that took hundreds of thousands with them.',
      'Stubborn, brilliant, occasionally lonely in their convictions.',
    ],
    options: ['B. R. Ambedkar', 'Jawaharlal Nehru', 'Sardar Patel'],
    reputation: 85,
    verdict: 'Revered',
    reveal: 'B. R. Ambedkar, jurist, economist and reformer who shaped the founding document of modern India.',
  },
  {
    id: 'lata',
    name: 'Lata Mangeshkar',
    era: 'Modern',
    traits: [
      'A craft devotee almost to the exclusion of a private life.',
      'Built a hospital quietly and never made it the headline.',
      'Accused by rivals of using their power to freeze out newer voices.',
      'An obsessive lifelong cricket fan with honorary memberships at famous grounds.',
      'A long, very public rift with a sibling that they never closed.',
      'Almost monastic about their own discipline.',
    ],
    options: ['Lata Mangeshkar', 'Asha Bhosle', 'Noor Jehan'],
    reputation: 87,
    verdict: 'Beloved',
    reveal: 'Lata Mangeshkar, the "Nightingale of India," whose playback voice defined Hindi cinema for generations.',
  },
  {
    id: 'indira',
    name: 'Indira Gandhi',
    era: 'Modern',
    traits: [
      'Steely. Slow to forgive. Quick to act on instinct.',
      'Will jail rivals when they feel the country needs it.',
      'A long memory; will deliver a payback years later.',
      'A craftsperson approach to power; described by allies as the best strategist in the room.',
      'Comfortable making the most consequential calls in private and absorbing the public cost.',
      'A loner in a crowd of advisors; trusts very few.',
    ],
    options: ['Indira Gandhi', 'Sonia Gandhi', 'Benazir Bhutto'],
    reputation: 46,
    verdict: 'Complicated',
    reveal: 'Indira Gandhi, India\'s only woman prime minister, admired for her steel and condemned for the Emergency.',
  },
  {
    id: 'bose',
    name: 'Subhas Chandra Bose',
    era: 'Historical',
    traits: [
      'A spellbinding speaker. A reluctant compromiser.',
      'Will resign from a movement they helped build rather than back down.',
      'Sought help from people the rest of the world considered enemies.',
      'On the record musing that the country might need a dictator for a long stretch.',
      'A long-game patience that occasionally hardened into recklessness.',
      'A folk-hero in life; a half-myth after it.',
    ],
    options: ['Subhas Chandra Bose', 'Bhagat Singh', 'Chandra Shekhar Azad'],
    reputation: 73,
    verdict: 'Revered, debated',
    reveal: 'Subhas Chandra Bose, the firebrand "Netaji" whose wartime alliances and unexplained disappearance still spark debate.',
  },
  {
    id: 'petrov',
    name: 'Stanislav Petrov',
    era: 'Historical',
    traits: [
      'Calm under pressure to an unusual degree.',
      'A craftsperson approach to a single decision and a refusal to make it on autopilot.',
      'Will defy the rules of a system they trust when it is wrong.',
      'A quiet, low-affect demeanour, even after doing something enormous.',
      'Said to be deeply private, almost reclusive, in later years.',
      'A drinker in retirement, by their own admission.',
    ],
    options: ['Vasili Arkhipov', 'Stanislav Petrov', 'Oleg Gordievsky'],
    reputation: 92,
    verdict: 'Quiet hero',
    reveal: 'Stanislav Petrov, the Soviet officer who, in 1983, almost certainly prevented an accidental nuclear war by trusting his gut over his computer.',
  },
  {
    id: 'haber',
    name: 'Fritz Haber',
    era: 'Historical',
    traits: [
      'A craft devotee; obsessive about the lab to the cost of the home.',
      'Personally directed work that hurt vast numbers of people.',
      'A patriotic fervour that exceeded that of most of their peers.',
      'Said to have been blind to the human cost in front of them.',
      'A long, slow rehabilitation of their reputation never quite caught up to their crimes.',
      'Walked, at the end, from the very system they had served.',
    ],
    options: ['Fritz Haber', 'Otto Hahn', 'Werner Heisenberg'],
    reputation: 38,
    verdict: 'Saviour and poisoner',
    reveal: 'Fritz Haber, whose nitrogen fixation feeds billions today — and whose chemical-weapons work in the First World War haunts the same legacy.',
  },
  {
    id: 'lamarr',
    name: 'Hedy Lamarr',
    era: 'Historical',
    traits: [
      'Reduced by their own industry to a face on a poster; quietly furious about it.',
      'A self-taught inventor in their spare hours.',
      'Will drug a chaperone and disappear from a controlling marriage.',
      'Late-life arrests for shoplifting on their record.',
      'Almost completely uninterested in the persona the public assigned them.',
      'Generous to friends in trouble; private about their own.',
    ],
    options: ['Hedy Lamarr', 'Veronica Lake', 'Greta Garbo'],
    reputation: 80,
    verdict: 'Underestimated',
    reveal: 'Hedy Lamarr, glamour star and self-taught inventor whose wartime patent helped pave the way for modern wireless.',
  },
  {
    id: 'kurien',
    name: 'Verghese Kurien',
    era: 'Modern',
    traits: [
      'Stubborn to a productive degree; will refuse a cabinet post on principle.',
      'A craftsperson approach to institutions; will take decades to get one right.',
      'Sharp-tongued; their enemies in government were many.',
      'Will refuse to put a celebrity face on the brand they built.',
      'A long-game thinker; will lose a year of profits to win a decade.',
      'On the record describing themselves as not a politician.',
    ],
    options: ['M. S. Swaminathan', 'Verghese Kurien', 'Sam Pitroda'],
    reputation: 88,
    verdict: 'Quietly transformative',
    reveal: 'Verghese Kurien, the "Milkman of India" who built Amul and the cooperative model that lifted millions of rural families.',
  },
  {
    id: 'phoolan',
    name: 'Phoolan Devi',
    era: 'Modern',
    traits: [
      'Fearless to the point of being feared.',
      'A long, brutal early life that shaped a moral code outside the law.',
      'Said by villagers to have been almost saint-like in their generosity; said by victims to be a killer.',
      'Will switch from the gun to the parliament without losing their core posture.',
      'Painted on temple walls in some villages; cursed in others.',
      'Carried the cost of every decision they had made on their face.',
    ],
    options: ['Phoolan Devi', 'Sampat Pal', 'Irom Sharmila'],
    reputation: 41,
    verdict: 'Avenger or murderer',
    reveal: 'Phoolan Devi, the "Bandit Queen" turned MP — revered by some as caste-rebel symbol, condemned by others as a killer.',
  },
  {
    id: 'lacks',
    name: 'Henrietta Lacks',
    era: 'Historical',
    traits: [
      'A quiet, hard-working mother with very few public traces.',
      'Treated their illness with stoicism, as their family later described it.',
      'Was, by every account, an ordinary kind person.',
      'Did not know that something taken from them would change the world.',
      'A family who did not know either, for an entire generation after.',
      'A name almost no one knew until the work and the wrong were made public.',
    ],
    options: ['Henrietta Lacks', 'Rosa Parks', 'Mamie Till'],
    reputation: 84,
    verdict: 'Wronged, then beloved',
    reveal: 'Henrietta Lacks, whose unconsented cells (the "HeLa" line) seeded modern medicine while her own family was kept in the dark for decades.',
  },
  {
    id: 'borlaug',
    name: 'Norman Borlaug',
    era: 'Modern',
    traits: [
      'A craft devotee about a single quiet problem for decades.',
      'Will work in dusty fields under impossible conditions and not complain.',
      'Almost nobody in their home country could name them.',
      'A long, on-record dispute with environmentalists about their methods.',
      'Pushed their work through borders of countries about to go to war.',
      'A teacher in everything; never tried to monetise the brand.',
    ],
    options: ['Norman Borlaug', 'M. S. Swaminathan', 'Jonas Salk'],
    reputation: 87,
    verdict: 'Saved a billion, barely remembered',
    reveal: 'Norman Borlaug, father of the Green Revolution, whose wheat is credited with saving an estimated billion lives.',
  },
  {
    id: 'turing',
    name: 'Alan Turing',
    era: 'Historical',
    traits: [
      'A loner; said to have been almost incapable of office politics.',
      'A craftsperson approach to logic; would explain things several times patiently.',
      'A long-distance runner who liked being alone.',
      'Honest about their own sexuality at a time when the state punished them for it.',
      'Endured a public conviction and chemical castration with great composure.',
      'Said by those close to them to be funny in a very dry way.',
    ],
    options: ['Alan Turing', 'John von Neumann', 'Claude Shannon'],
    reputation: 90,
    verdict: 'Tragic genius',
    reveal: 'Alan Turing, the founder of theoretical computer science, hounded to death by the state he had helped save.',
  },
  {
    id: 'kahlo',
    name: 'Frida Kahlo',
    era: 'Modern',
    traits: [
      'Fierce. Open about their pain and politics in a way few of their peers were.',
      'A serial unfaithful partner, on the record, with both men and women.',
      'A committed political ideologue; hosted radicals as houseguests.',
      'Will paint themselves again and again, refusing to look away.',
      'Said by friends to have been intensely loyal once you were inside the circle.',
      'A long, lifelong physical pain that bled into the work.',
    ],
    options: ['Frida Kahlo', 'Tamara de Lempicka', 'Georgia O’Keeffe'],
    reputation: 88,
    verdict: 'Defiant icon',
    reveal: 'Frida Kahlo, the Mexican painter whose self-portraits turned a lifetime of pain into modern art\'s most quoted face.',
  },
  {
    id: 'chanel',
    name: 'Coco Chanel',
    era: 'Historical',
    traits: [
      'A craftsperson approach to taste; almost dictatorial about it.',
      'Sharp-tongued and openly anti-social.',
      'A wartime relationship that they did not bother to hide.',
      'On the record carrying out a small mission for the occupiers.',
      'Will absorb the post-war reckoning by leaving the country for a decade.',
      'Generous with very few people; cool with everyone else.',
    ],
    options: ['Coco Chanel', 'Elsa Schiaparelli', 'Madeleine Vionnet'],
    reputation: 52,
    verdict: 'Brilliant, compromised',
    reveal: 'Coco Chanel, who liberated women\'s fashion in the morning and worked for the occupying regime by night.',
  },
  {
    id: 'suu-kyi',
    name: 'Aung San Suu Kyi',
    era: 'Modern',
    traits: [
      'Polished, principled, very careful with words.',
      'Endured long detention with a composure the press treated as saint-like.',
      'In power, defended their military against international monitors.',
      'A long, public failure to call a major atrocity by its name.',
      'A long memory; trusts almost nobody outside a very small circle.',
      'Said by colleagues to be cold to those they consider unserious.',
    ],
    options: ['Aung San Suu Kyi', 'Benazir Bhutto', 'Sheikh Hasina'],
    reputation: 36,
    verdict: 'Fallen icon',
    reveal: 'Aung San Suu Kyi, once the world\'s favourite political prisoner, whose handling of the Rohingya crisis collapsed her halo.',
  },
  {
    id: 'allende',
    name: 'Salvador Allende',
    era: 'Historical',
    traits: [
      'A craftsperson approach to social reform; will spend years tightening one mechanism.',
      'A doctor at heart; the soft-spoken kind.',
      'Allowed dissent in their own coalition, often to their cost.',
      'Will refuse to abandon a public office under fire.',
      'Believed in process more than personalities.',
      'Said by colleagues to be obsessively well-prepared.',
    ],
    options: ['Salvador Allende', 'Fidel Castro', 'Che Guevara'],
    reputation: 68,
    verdict: 'Martyred reformer',
    reveal: 'Salvador Allende, Chile\'s democratically elected socialist president, killed in the Pinochet-led coup of 1973.',
  },
  {
    id: 'angelou',
    name: 'Maya Angelou',
    era: 'Modern',
    traits: [
      'A voice that carries. A serious wit, on the record about it.',
      'Spent stretches of their life almost mute.',
      'Will help build several political movements without needing the centre seat.',
      'A craftsperson approach to language; obsessive about getting the line right.',
      'A long, public commitment to making other people heard.',
      'Friends describe a sharply maternal, slightly bossy private personality.',
    ],
    options: ['Maya Angelou', 'Toni Morrison', 'Alice Walker'],
    reputation: 89,
    verdict: 'Beloved',
    reveal: 'Maya Angelou, poet, memoirist, civil-rights organiser, and a voice that defined a generation of American letters.',
  },
  {
    id: 'ela-bhatt',
    name: 'Ela Bhatt',
    era: 'Modern',
    traits: [
      'Soft-spoken; almost stubbornly so even in public roles.',
      'A craftsperson approach to a single quiet movement, sustained for decades.',
      'A long memory for promises broken to ordinary working women.',
      'Will take a seat in a legislature and leave it quietly when not needed.',
      'Critics call them cautious; allies call them painstaking.',
      'Mentored younger leaders without putting their own name on the work.',
    ],
    options: ['Ela Bhatt', 'Medha Patkar', 'Aruna Roy'],
    reputation: 88,
    verdict: 'Quietly transformative',
    reveal: 'Ela Bhatt, founder of SEWA, who built one of the world\'s largest unions of poor self-employed women.',
  },
  {
    id: 'bhagat',
    name: 'Bhagat Singh',
    era: 'Historical',
    traits: [
      'Young, restless, on the record about wanting more than slogans.',
      'A serious reader; would carry books to and from jail.',
      'Wrote a clear defence of atheism late at night.',
      'Will set off devices in a public chamber and then wait calmly to be arrested.',
      'Held convictions tight enough to choose the rope over the back door.',
      'Said by friends to have been funny, intense, and almost compulsively idealistic.',
    ],
    options: ['Bhagat Singh', 'Chandra Shekhar Azad', 'Sukhdev Thapar'],
    reputation: 86,
    verdict: 'Revered martyr',
    reveal: 'Bhagat Singh, the young revolutionary whose hanging at 23 made him perhaps independent India\'s most enduring icon of defiance.',
  },
  {
    id: 'savitribai',
    name: 'Savitribai Phule',
    era: 'Historical',
    traits: [
      'Patient, almost saint-like, in the face of public abuse.',
      'A teacher in everything they did.',
      'Will carry a clean change of clothes to walk to school under attack.',
      'A long, on-the-ground engagement with the poorest neighbours.',
      'Tireless; ran a shelter and a school and a clinic at once.',
      'Generous to a point that finally cost them their life.',
    ],
    options: ['Savitribai Phule', 'Pandita Ramabai', 'Sarojini Naidu'],
    reputation: 91,
    verdict: 'Quietly revolutionary',
    reveal: 'Savitribai Phule, India\'s first woman teacher and a foundational figure in the country\'s anti-caste and women\'s-education movements.',
  },
  {
    id: 'ramanujan',
    name: 'Srinivasa Ramanujan',
    era: 'Historical',
    traits: [
      'Almost monastically obsessed with the work.',
      'Will scribble equations on floors, walls, anything to hand.',
      'Soft, reserved, said by mentors to be the gentlest collaborator in the room.',
      'A devout follower of their own religion; the food rules cost them their health.',
      'A short life and a long, posthumous influence.',
      'Said by close friends to have been chronically homesick.',
    ],
    options: ['Srinivasa Ramanujan', 'Satyendra Nath Bose', 'P. C. Mahalanobis'],
    reputation: 89,
    verdict: 'Singular genius',
    reveal: 'Srinivasa Ramanujan, the self-taught Indian mathematician whose intuited identities are still being unpacked a century on.',
  },
  {
    id: 'vinoba',
    name: 'Vinoba Bhave',
    era: 'Historical',
    traits: [
      'A walker; a long-game philosopher of patience.',
      'Will accept land from people who would later regret it.',
      'A long, public endorsement of a major democratic crackdown.',
      'Said to be deeply read and almost stubbornly polite.',
      'Will accept very little for themselves; lived spartan even by their standards.',
      'Friends describe a sense of humour the press rarely surfaced.',
    ],
    options: ['Vinoba Bhave', 'Jayaprakash Narayan', 'Acharya Kripalani'],
    reputation: 64,
    verdict: 'Revered, debated',
    reveal: 'Vinoba Bhave, Gandhi\'s spiritual heir, whose land-gift movement and Emergency-era endorsement still divide opinion.',
  },
  {
    id: 'galileo',
    name: 'Galileo Galilei',
    era: 'Historical',
    traits: [
      'Sharp-tongued. Almost unable to resist mocking the powerful.',
      'A craftsperson approach to evidence; would sketch every night sky themselves.',
      'A long, unmarried partnership; on the record about being a father.',
      'Will recant a public position under threat and continue writing in private.',
      'Confident enough to call patrons fools and absorb the cost.',
      'A teacher in everything they wrote.',
    ],
    options: ['Galileo Galilei', 'Johannes Kepler', 'Tycho Brahe'],
    reputation: 88,
    verdict: 'Father of modern science',
    reveal: 'Galileo Galilei, whose telescope and stubbornness moved Europe a step closer to evidence-based science, at heavy personal cost.',
  },
  {
    id: 'salman',
    name: 'Salman Khan',
    era: 'Modern',
    traits: [
      'Loud, charismatic, said by family and friends to have a frightening temper.',
      'Generous in big public ways with crew and small private ones with charity.',
      'A long, on-the-record legal trail across nearly two decades.',
      'Said by ex-partners and co-workers to be controlling.',
      'Loyal almost to a fault with the very small inner circle.',
      'Famously slow to apologise. Famously quick to threaten.',
    ],
    options: ['Salman Khan', 'Sanjay Dutt', 'Aamir Khan'],
    reputation: 48,
    verdict: 'Adored and accused',
    reveal: 'Salman Khan, one of Bollywood\'s biggest box-office draws, whose decades-long legal cases coexist with a massive philanthropic operation.',
  },
  {
    id: 'sanjay-dutt',
    name: 'Sanjay Dutt',
    era: 'Modern',
    traits: [
      'A long, on-the-record history of addiction; spoken about openly.',
      'Said to be the most generous friend in a green room.',
      'A long jail term that they used to teach yoga and run a school.',
      'A serial restart; will rebuild a life after each fall.',
      'Said to be a soft touch with strangers and a tough one with confidants.',
      'A long memory for kindnesses; almost no memory for slights.',
    ],
    options: ['Sanjay Dutt', 'Salman Khan', 'Shah Rukh Khan'],
    reputation: 56,
    verdict: 'Fallen, redeemed, debated',
    reveal: 'Sanjay Dutt, the "Munnabhai" star whose jail time over an illegal weapons cache turned his second act into a comeback story.',
  },
  {
    id: 'srk',
    name: 'Shah Rukh Khan',
    era: 'Modern',
    traits: [
      'Self-deprecating; will joke about their own bad films at length.',
      'Famously generous with fans, crew and even strangers at the gate.',
      'A serious philanthropy quietly behind the scenes.',
      'Has endured airport detentions and on-the-record bigotry with humour.',
      'Said to be a soft-touch parent and a workaholic boss.',
      'A long, public marriage that has stayed mostly out of the press.',
    ],
    options: ['Shah Rukh Khan', 'Aamir Khan', 'Salman Khan'],
    reputation: 84,
    verdict: 'Beloved across borders',
    reveal: 'Shah Rukh Khan, "King Khan," one of the most-recognised actors on earth and an unusually durable hero of mainstream Hindi cinema.',
  },
  {
    id: 'amitabh',
    name: 'Amitabh Bachchan',
    era: 'Modern',
    traits: [
      'Formal, almost old-school in public; described as much softer in private.',
      'A long memory; will hold a small slight for decades.',
      'Will repay debts in full, on principle, even when bankruptcy was the easier path.',
      'A long-running, very loyal relationship with the press.',
      'A name surfaced in major financial leaks that they have largely refused to discuss.',
      'A craftsperson approach to language; obsessive about diction.',
    ],
    options: ['Amitabh Bachchan', 'Dharmendra', 'Dilip Kumar'],
    reputation: 79,
    verdict: 'Revered, complicated',
    reveal: 'Amitabh Bachchan, the "angry young man" turned grand patriarch of Indian cinema, a comeback story shadowed by old controversies.',
  },
  {
    id: 'sridevi',
    name: 'Sridevi',
    era: 'Modern',
    traits: [
      'Reserved off-stage; said to come to life only when a camera was rolling.',
      'A craft devotee from childhood; almost no break in their working hours.',
      'A long, private love that scandalised gossip columns for a decade.',
      'Walked away from work to raise their family; took back the work on their own terms.',
      'Said by close friends to be intensely shy and oddly funny.',
      'A protective, almost over-protective parent.',
    ],
    options: ['Sridevi', 'Madhuri Dixit', 'Rekha'],
    reputation: 86,
    verdict: 'Beloved, mourned',
    reveal: 'Sridevi, India\'s first female superstar, whose sudden death in 2018 plunged South Asian cinema into a week of public grief.',
  },
  {
    id: 'sushant',
    name: 'Sushant Singh Rajput',
    era: 'Modern',
    traits: [
      'A reader; said to be the rare actor who quoted physicists in interviews.',
      'Open about therapy, about anxiety, about a feeling of being out of place.',
      'A craft devotee; would learn fencing or hip-hop for a single scene.',
      'Said by close friends to be lonelier than the public image allowed.',
      'A long, on-the-record curiosity about astronomy and meditation.',
      'A gentleness to them, almost out of step with the loud industry around them.',
    ],
    options: ['Sushant Singh Rajput', 'Siddharth Malhotra', 'Varun Dhawan'],
    reputation: 78,
    verdict: 'Loved, mourned',
    reveal: 'Sushant Singh Rajput, the small-town engineer-turned-actor whose 2020 death sparked a media frenzy in India that ran for months.',
  },
  {
    id: 'chiranjeevi',
    name: 'Chiranjeevi',
    era: 'Modern',
    traits: [
      'A craft devotee about dance; obsessive about the craft they came up through.',
      'A long, serious philanthropy in their home region, almost off the record.',
      'A bumpy turn into politics that bruised them.',
      'A serious family figure; almost old-fashioned about it.',
      'Said to be slow to lose their temper and very slow to forgive when they do.',
      'A quiet retreat from the public eye for a long stretch, then a return.',
    ],
    options: ['Chiranjeevi', 'Mohan Babu', 'Nagarjuna'],
    reputation: 81,
    verdict: 'Beloved Megastar',
    reveal: 'Chiranjeevi, Tollywood\'s "Megastar" and a long-running force in Telugu philanthropy, even after a bumpy turn into politics.',
  },
  {
    id: 'ntr-sr',
    name: 'N. T. Rama Rao',
    era: 'Historical',
    traits: [
      'Theatrical to the bone; will play a god in fiction and the part in politics.',
      'A craftsperson approach to staging; obsessive about every visual.',
      'Confident enough to take on the entire political establishment of their region.',
      'A long, public belief that the audience was the priority.',
      'Said by family to have been a difficult patriarch.',
      'Betrayed by people they had trusted and never quite recovered.',
    ],
    options: ['N. T. Rama Rao', 'Akkineni Nageswara Rao', 'Sivaji Ganesan'],
    reputation: 84,
    verdict: 'Beloved star and statesman',
    reveal: 'N. T. Rama Rao, the Telugu superstar who became Andhra Pradesh\'s three-time chief minister and a folk-hero in the Telugu diaspora.',
  },
  {
    id: 'rdj',
    name: 'Robert Downey Jr.',
    era: 'Modern',
    traits: [
      'Funny, restless, on the record about a long battle with addiction.',
      'Said to be one of the warmest co-stars in their industry.',
      'A long history of self-sabotage; a longer history of climbing back.',
      'Privately funds science work without making a brand of it.',
      'A craft devotee about the work; almost a different person on the days the work is on.',
      'A loyal friend to a small group; clear about who that group is.',
    ],
    options: ['Robert Downey Jr.', 'Brad Pitt', 'Johnny Depp'],
    reputation: 83,
    verdict: 'Comeback kid',
    reveal: 'Robert Downey Jr., whose Iron Man comeback after a decade of addiction and prison time became one of Hollywood\'s most-cited redemption arcs.',
  },
  {
    id: 'keanu',
    name: 'Keanu Reeves',
    era: 'Modern',
    traits: [
      'Reserved, polite, said to be the easiest person on a film set to share a bench with.',
      'Quietly generous to crew and to support staff to the tune of millions.',
      'Will ride public transit and give up a seat.',
      'A long, private grief that they have rarely discussed.',
      'A loyal friend; will travel anywhere for a small funeral.',
      'Said by long-time co-workers to be allergic to anything performative.',
    ],
    options: ['Keanu Reeves', 'Brendan Fraser', 'Jeff Bridges'],
    reputation: 92,
    verdict: 'The internet\'s favourite human',
    reveal: 'Keanu Reeves, an action star whose quietly generous off-camera life has made him a folk-hero of internet culture.',
  },
  {
    id: 'britney',
    name: 'Britney Spears',
    era: 'Modern',
    traits: [
      'A relentless performer from very early in their life.',
      'A long, on-the-record breakdown that the press covered without restraint.',
      'A craft devotee at heart; will rehearse for hours alone.',
      'Said to be deeply private about the people who hurt them.',
      'A long fight to regain control over their own affairs.',
      'A loyal friend to the very few who stayed.',
    ],
    options: ['Britney Spears', 'Christina Aguilera', 'Jessica Simpson'],
    reputation: 72,
    verdict: 'Survivor, finally free',
    reveal: 'Britney Spears, whose thirteen-year conservatorship became a global case study in how the music industry handled a young star\'s breakdown.',
  },
  {
    id: 'will-smith',
    name: 'Will Smith',
    era: 'Modern',
    traits: [
      'Charismatic, sunny, said to be the warmest person in most rooms.',
      'A long, on-the-record openness about their own marriage that did them no favours.',
      'A flash of public violence that they then apologised for.',
      'Generous to the small inner circle; on the record about it.',
      'A long-running philanthropy in the neighbourhood they came from.',
      'Said by friends to be deeply self-aware and just as deeply unable to leave a stage.',
    ],
    options: ['Will Smith', 'Eddie Murphy', 'Denzel Washington'],
    reputation: 58,
    verdict: 'Brilliant, polarising',
    reveal: 'Will Smith, the global movie star whose 2022 Oscars slap reset, perhaps permanently, the way Hollywood and audiences read him.',
  },
  {
    id: 'johnny-depp',
    name: 'Johnny Depp',
    era: 'Modern',
    traits: [
      'Bohemian, on the record, almost stubbornly so.',
      'A long, very public marriage that ended in violence allegations on both sides.',
      'Will pay a stranger\'s long-term medical bills without making a brand of it.',
      'A long, deeply contested split with public opinion.',
      'Said by close friends to be funny, gentle, and easily wounded.',
      'A loyal fan-base that they themselves have called complicated.',
    ],
    options: ['Johnny Depp', 'Jared Leto', 'Bradley Cooper'],
    reputation: 49,
    verdict: 'Adored and disputed',
    reveal: 'Johnny Depp, the franchise star whose internationally televised defamation trial with Amber Heard became the most-watched courtroom event of the streaming era.',
  },

  // ── Modular extensions ────────────────────────────────────────────────
  // Topical figure files live under ./figures/ — see ./figures/index.js
  // for the manifest.  Adding a new batch is a single ./figures/<file>.js
  // import in that index; no edit to this file is required.
  ...EXTENDED_FIGURES,
];
