// Music figures across genres — pop, rock, hip-hop, classical, playback.
// Traits draw on r/popheads, r/hiphopheads, r/Music and r/IndianMusic
// discussion threads plus the news cycles those threads orbit.

export const MUSIC_FIGURES = [
  {
    id: 'taylor-swift',
    name: 'Taylor Swift',
    era: 'Modern',
    traits: [
      'A Pennsylvania country-singer who moved to Nashville at fourteen to chase a deal.',
      'She left her label after they sold off the master tapes of her first six records.',
      'She re-recorded all six albums herself, sold them as "Taylor\'s Versions" and topped charts again.',
      'Her private-jet emissions are one of the most-cited in celebrity climate data.',
      'Her concert tour single-handedly lifted a small-city US economy figure on the news.',
      'She has been criticised for staying neutral during the US presidential election cycle.',
    ],
    options: ['Taylor Swift', 'Ariana Grande', 'Olivia Rodrigo'],
    reputation: 76,
    verdict: 'Adored, environmentally flagged',
    reveal: 'Taylor Swift, the artist who re-recorded six records to reclaim her own catalogue and now functions as a soft-power touring economy.',
  },
  {
    id: 'kanye',
    name: 'Kanye West',
    era: 'Modern',
    traits: [
      'A Chicago college dropout who sold beats out of his mother\'s basement.',
      'He produced and rapped one of the most influential debut hip-hop records of the 2000s.',
      'He interrupted Taylor Swift at the VMAs to award a video to someone else.',
      'He ran for US president on a platform of "love" and pulled half a million votes.',
      'He has made anti-Semitic comments on national radio and lost a billion in deals overnight.',
      'He has a long, on-and-off-record diagnosis of bipolar disorder he discusses publicly.',
    ],
    options: ['Kanye West', 'Drake', 'Travis Scott'],
    reputation: 28,
    verdict: 'Genius and pariah',
    reveal: 'Kanye West, the producer-rapper whose creative legacy is now lapped, every year, by his own scandals.',
  },
  {
    id: 'beyonce',
    name: 'Beyoncé',
    era: 'Modern',
    traits: [
      'A Houston-born teenager whose father managed her group with iron-fisted control.',
      'She has the most Grammy wins in history — male or female, any genre.',
      'A surprise visual album she dropped in 2013 changed how the music industry releases music.',
      'Her father has been accused on the record of mismanaging her child-stardom finances.',
      'Her husband, Jay-Z, has been accused in lyrics, books and tabloids of long infidelity.',
      'She runs a women-of-colour scholarship and a Black-American voter-mobilisation foundation.',
    ],
    options: ['Beyoncé', 'Rihanna', 'Adele'],
    reputation: 84,
    verdict: 'Reigning superstar',
    reveal: 'Beyoncé, Grammy\'s most-decorated artist whose family, music and politics are equally critiqued and adored.',
  },
  {
    id: 'rihanna',
    name: 'Rihanna',
    era: 'Modern',
    traits: [
      'A Barbadian teenager scouted by a US producer on the way home from school.',
      'She survived a high-profile assault by then-boyfriend Chris Brown.',
      'She founded a fashion-and-beauty brand explicitly for darker skin tones, now worth billions.',
      'She has not released a studio album in nearly a decade by her own choice.',
      'Her Super Bowl halftime show drew six-million-strong viewing records globally.',
      'Her Clara Lionel Foundation funds climate-resilience work across the Caribbean.',
    ],
    options: ['Rihanna', 'Beyoncé', 'Nicki Minaj'],
    reputation: 86,
    verdict: 'Beloved mogul',
    reveal: 'Rihanna, the Bajan pop star turned cosmetics billionaire whose career has been less about music releases and more about brand-power.',
  },
  {
    id: 'drake',
    name: 'Drake',
    era: 'Modern',
    traits: [
      'A Canadian Jewish child actor on a popular teen TV show before he ever rapped.',
      'He has, by streaming volume, sold more music than the entire genre of country.',
      'He has been called out for using a network of co-writers to ghost-write his hooks.',
      'A diss-track war with Kendrick Lamar revealed serious public-record allegations against him.',
      'He has been accused of texting underage women, including Millie Bobby Brown.',
      'He runs a Toronto charity that quietly funds music classrooms in low-income schools.',
    ],
    options: ['Drake', 'Travis Scott', 'The Weeknd'],
    reputation: 38,
    verdict: 'Streaming-king, deeply contested',
    reveal: 'Drake, hip-hop\'s streaming-era monarch whose 2024 Kendrick Lamar feud surfaced serious unanswered allegations.',
  },
  {
    id: 'kendrick',
    name: 'Kendrick Lamar',
    era: 'Modern',
    traits: [
      'A Compton kid who grew up watching his mother work two jobs to feed five children.',
      'He is the only rap artist ever to win the Pulitzer Prize for music.',
      'His verses get studied as poetry by US college English departments.',
      'He has been criticised for what some call performative engagement with Black politics.',
      'A diss-track campaign against Drake produced one of the biggest songs of the decade.',
      'He runs a creative collective in Watts that gives studio time to local kids for free.',
    ],
    options: ['Kendrick Lamar', 'J. Cole', 'Drake'],
    reputation: 91,
    verdict: 'Pulitzer rapper',
    reveal: 'Kendrick Lamar, the Compton MC whose Pulitzer-winning poetry and 2024 Drake-bout dominated cultural discourse in equal parts.',
  },
  {
    id: 'arijit',
    name: 'Arijit Singh',
    era: 'Modern',
    traits: [
      'A reality-TV finalist who left the show without winning to study classical music.',
      'He has sung in over twenty languages, including languages he does not speak.',
      'He insists his fee be split with the lesser-paid technical crew on each track.',
      'He has clashed publicly with Salman Khan over an awards-show seating row.',
      'He runs a residential music school for orphaned children in his Bengali hometown.',
      'He largely refuses live concerts in India to avoid travel and pollution.',
    ],
    options: ['Arijit Singh', 'Atif Aslam', 'Shreya Ghoshal'],
    reputation: 88,
    verdict: 'Quiet superstar',
    reveal: 'Arijit Singh, the playback voice of an Indian generation whose feud with Salman Khan and quiet philanthropy keep him in conversation.',
  },
  {
    id: 'shreya',
    name: 'Shreya Ghoshal',
    era: 'Modern',
    traits: [
      'A Bengali-born child of a nuclear engineer who learnt music from her mother.',
      'She has recorded over two thousand songs in twenty Indian languages.',
      'She paused her career midway to take a multi-year sabbatical for her family.',
      'She has been criticised for staying largely apolitical in a polarised industry.',
      'She is the only Indian artist with multiple wax statues on multiple continents.',
      'She runs a small-budget foundation that supports new women composers in India.',
    ],
    options: ['Shreya Ghoshal', 'Sunidhi Chauhan', 'Asha Bhosle'],
    reputation: 91,
    verdict: 'Beloved playback voice',
    reveal: 'Shreya Ghoshal, the four-time National Award-winning playback singer whose voice has anchored mainstream Indian cinema for two decades.',
  },
  {
    id: 'eminem',
    name: 'Eminem',
    era: 'Modern',
    traits: [
      'A Detroit trailer-park kid who failed ninth grade three times before dropping out.',
      'He has rapped about killing his then-wife Kim on multiple records.',
      'He has, on record, apologised for some of those lyrics and the harm they did.',
      'He has been clean from his prescription-pill addiction for over a decade.',
      'He runs a Detroit foundation that funds neighbourhood music schools.',
      'A diss-track he released against Trump in 2017 went unanswered, to widespread comment.',
    ],
    options: ['Eminem', 'Dr. Dre', 'Snoop Dogg'],
    reputation: 70,
    verdict: 'Polarising legend',
    reveal: 'Eminem, hip-hop\'s most commercially successful white rapper whose lyrical violence and late-career sobriety run side-by-side in interviews.',
  },
  {
    id: 'a-r-rahman',
    name: 'A. R. Rahman',
    era: 'Modern',
    traits: [
      'A Tamil child of a film composer who began session work after his father died young.',
      'He converted from Hinduism to Islam in his early twenties and has spoken about it.',
      'He has won two Academy Awards in a single night for the same film.',
      'His use of multiple synthesisers and digital sampling redefined Indian film music.',
      'He runs a music school in Chennai that offers full scholarships across India.',
      'His daughter has chosen to dress in a niqab in public, sparking long debates online.',
    ],
    options: ['A. R. Rahman', 'Ilaiyaraaja', 'Shankar-Ehsaan-Loy'],
    reputation: 92,
    verdict: 'Universally adored',
    reveal: 'A. R. Rahman, the two-time Oscar-winning Indian composer whose digital revolution still echoes across South Asian cinema.',
  },
  {
    id: 'beatles-paul',
    name: 'Paul McCartney',
    era: 'Modern',
    traits: [
      'A Liverpool boy who wrote "When I\'m Sixty-Four" at age fifteen.',
      'He has been a strict vegetarian since the 1970s and campaigns for animal rights.',
      'His Beatles-era taxes once nearly bankrupted him through bad business management.',
      'He has been part of a long feud with the estate of John Lennon over song credits.',
      'He held the world\'s longest run of solo number-one singles for a quarter-century.',
      'A divorce from his second wife was publicly bitter and cost him close to forty million pounds.',
    ],
    options: ['Paul McCartney', 'Ringo Starr', 'Mick Jagger'],
    reputation: 89,
    verdict: 'Beloved Beatle',
    reveal: 'Paul McCartney, half of the Lennon-McCartney songwriting duo, whose vegetarian advocacy and family drama keep him press-cycle present.',
  },
  {
    id: 'freddie',
    name: 'Freddie Mercury',
    era: 'Historical',
    traits: [
      'A Parsi child born in Zanzibar to a colonial-treasury clerk family.',
      'He kept his sexuality private for almost his entire public-facing career.',
      'He hid his AIDS diagnosis from the public for over four years.',
      'He confirmed it the day before he died of bronchopneumonia caused by it.',
      'A Wembley benefit tribute concert raised millions and funded AIDS research.',
      'His last live show with Queen at Knebworth had a sold-out crowd of 120,000.',
    ],
    options: ['Freddie Mercury', 'Mick Jagger', 'David Bowie'],
    reputation: 93,
    verdict: 'Universally mourned',
    reveal: 'Freddie Mercury, the Queen frontman whose final confirmation of his AIDS diagnosis a day before his death changed AIDS-era public conversation.',
  },
];
