// Sports figures. Trait style: PERSONALITY ONLY.

export const SPORTS_FIGURES = [
  {
    id: 'sachin',
    name: 'Sachin Tendulkar',
    era: 'Modern',
    traits: [
      'Goes silent the moment anything controversial touches them.',
      'Avoids taking a side, even when staying neutral is itself a choice.',
      'Conflict-averse to the point of letting wrongs slide.',
      'Cultivates the saintly image and never lets it crack in public.',
      'Withholds opinions that might cost them anything.',
      'Polite to a degree that keeps everyone at arm\'s length.',
      'Obsessive, controlling, exacting about their own preparation.',
      'Privately mischievous and funny with the few they trust.',
    ],
    example: 'When the room turns ugly, they study their shoes and say nothing.',
    options: ['Sachin Tendulkar', 'Rahul Dravid', 'Sourav Ganguly'],
    reputation: 90,
    verdict: 'Living legend, debated MP',
    reveal: 'Sachin Tendulkar, the "Little Master" whose godhood on the pitch sits alongside a quiet parliament attendance record.',
  },
  {
    id: 'kohli',
    name: 'Virat Kohli',
    era: 'Modern',
    traits: [
      'Aggressive, confrontational, always spoiling for a fight.',
      'Snaps at anyone who crosses them and shows it openly.',
      'Holds grudges and lets them fester for years.',
      'Cold to people he hasn\'t decided to like.',
      'His ego needs constant feeding and everyone knows it.',
      'Fiercely loyal to the handful he genuinely trusts.',
      'Disciplined to the point of self-denial about his own habits.',
      'Blunt and direct, never softens a single word.',
    ],
    example: 'A bad call sets him off and he lets the whole stadium hear it.',
    options: ['Virat Kohli', 'Rohit Sharma', 'KL Rahul'],
    reputation: 78,
    verdict: 'Adored, intense',
    reveal: 'Virat Kohli, one of the highest-paid athletes on earth, whose on-field aggression and off-field philanthropy carve a tightly-watched public image.',
  },
  {
    id: 'dhoni',
    name: 'M. S. Dhoni',
    era: 'Modern',
    traits: [
      'Withholds himself so completely that no one really knows him.',
      'Distant and unreadable even to people who work beside him daily.',
      'Shuts down questions and gives away nothing.',
      'Detached to the point of seeming cold under pressure.',
      'Guards his private life like a fortress and resents intrusion.',
      'Unshakably calm when everyone around him is falling apart.',
      'Quietly generous in his home region without announcing it.',
      'Genuinely uninterested in defending or explaining himself.',
    ],
    example: 'Asked a pointed question, he answers in five flat words and moves on.',
    options: ['M. S. Dhoni', 'Yuvraj Singh', 'Virender Sehwag'],
    reputation: 89,
    verdict: 'Beloved Captain Cool',
    reveal: 'M. S. Dhoni, the only captain to win all three major ICC trophies, whose IPL franchise legal mess sits awkwardly beside his folk-hero status.',
  },
  {
    id: 'messi-sport',
    name: 'Lionel Messi',
    era: 'Modern',
    traits: [
      'Withdraws from attention to the point of seeming aloof.',
      'Slow to trust and keeps almost everyone at a distance.',
      'Lets things slide rather than confront anyone.',
      'Avoids the spotlight even when speaking up would matter.',
      'Goes quiet and unreachable when things get tense.',
      'Soft-spoken off the pitch and ferocious on it.',
      'Intensely loyal once someone earns their way in.',
      'Steady and scandal-free across a relentless public life.',
    ],
    example: 'Handed the microphone, they shrink and pass it to someone else.',
    options: ['Lionel Messi', 'Cristiano Ronaldo', 'Neymar'],
    reputation: 88,
    verdict: 'Beloved with caveats',
    reveal: 'Lionel Messi, football\'s most-decorated individual whose World Cup victory and tax case both sit on his Wikipedia page.',
  },
  {
    id: 'ronaldo',
    name: 'Cristiano Ronaldo',
    era: 'Modern',
    traits: [
      'Vain to a degree he makes no effort to hide.',
      'Resents any teammate who steals his spotlight.',
      'His insecurity drives a constant hunger for validation.',
      'Sulks and turns cold when he isn\'t the centre of things.',
      'Disciplined to an almost inhuman degree about his craft.',
      'A serious and committed giver to children\'s causes.',
      'Punctual and dependable to a fault.',
      'Warmer in private than the polished public image lets on.',
    ],
    example: 'A younger player gets the headline and he stops passing him the ball.',
    options: ['Cristiano Ronaldo', 'Lionel Messi', 'Karim Benzema'],
    reputation: 56,
    verdict: 'Adored, deeply contested',
    reveal: 'Cristiano Ronaldo, football\'s most-marketed individual whose endorsements and allegations form an evenly-balanced public profile.',
  },
  {
    id: 'serena',
    name: 'Serena Williams',
    era: 'Modern',
    traits: [
      'Explosive temper that detonates on court when she feels wronged.',
      'Refuses to back down once she\'s decided she\'s been slighted.',
      'No patience for false modesty and lets it show.',
      'Negotiates hard and walks away cold if it suits her.',
      'Fiercely combative the instant her pride is touched.',
      'Names racism and injustice flatly, without softening it.',
      'Privately warm, funny, and fiercely devoted as a mother.',
      'Exacting and tireless about her own fitness and craft.',
    ],
    example: 'A line call goes against her and she unloads on the umpire on the spot.',
    options: ['Serena Williams', 'Venus Williams', 'Naomi Osaka'],
    reputation: 90,
    verdict: 'Beloved trailblazer',
    reveal: 'Serena Williams, the open-era Grand Slam record-holder whose post-career VC and on-court fights have shaped public sport conversation.',
  },
  {
    id: 'federer',
    name: 'Roger Federer',
    era: 'Modern',
    traits: [
      'Stays silent on hard issues to protect his clean image.',
      'Far more ruthless behind the polished, gracious surface.',
      'Avoids anything that might tarnish the saintly reputation.',
      'Calculating about which causes are safe to be seen with.',
      'Keeps his real edges hidden where the cameras can\'t reach.',
      'Carries himself with effortless dignity even in defeat.',
      'Genuinely courteous to ball kids, officials, and press alike.',
      'Precise and disciplined to watchmaker exactness.',
    ],
    example: 'A cause needs a loud voice and he offers a careful, noncommittal smile.',
    options: ['Roger Federer', 'Rafael Nadal', 'Novak Djokovic'],
    reputation: 95,
    verdict: 'Universally beloved',
    reveal: 'Roger Federer, the Swiss tennis great whose post-retirement work in early-childhood education matches his on-court reputation.',
  },
  {
    id: 'djokovic',
    name: 'Novak Djokovic',
    era: 'Modern',
    traits: [
      'Antagonistic and comfortable cast as the villain of the room.',
      'Digs in on unpopular views and refuses to budge an inch.',
      'Takes every defeat as a personal wound and broods on it.',
      'Reads as cold and remote to almost everyone outside his circle.',
      'Fiercely loyal to the small group he lets close.',
      'Disciplined and exacting about his own body and routine.',
      'Quietly generous in his home region without fanfare.',
      'Driven by a relentless need to prove the doubters wrong.',
    ],
    example: 'Booed by the whole crowd, he soaks it up and plays harder.',
    options: ['Novak Djokovic', 'Roger Federer', 'Rafael Nadal'],
    reputation: 64,
    verdict: 'Record-breaker, divisive',
    reveal: 'Novak Djokovic, the open-era men\'s Grand Slam record-holder whose vaccination stance keeps him a permanent character in news cycles.',
  },
  {
    id: 'lewis-hamilton',
    name: 'Lewis Hamilton',
    era: 'Modern',
    traits: [
      'Turns press conferences into self-styled keynote lectures.',
      'Wears his causes loudly and expects the room to follow.',
      'Thin-skinned beneath the cool, composed exterior.',
      'Moody and volatile when results don\'t go his way.',
      'Can come across as preachy and self-righteous.',
      'Deeply loyal to the small team he keeps around him.',
      'Gives away enormous sums quietly and never mentions it.',
      'Sincere and committed to fairness in his sport.',
    ],
    example: 'Asked about a race, he delivers a ten-minute sermon on injustice instead.',
    options: ['Lewis Hamilton', 'Max Verstappen', 'Sebastian Vettel'],
    reputation: 87,
    verdict: 'Beloved, politically active',
    reveal: 'Lewis Hamilton, the seven-time F1 World Champion who has spent his late career campaigning publicly for diversity in motorsport.',
  },
  {
    id: 'simone-biles',
    name: 'Simone Biles',
    era: 'Modern',
    traits: [
      'Walks away from the big moment when she won\'t fake being okay.',
      'Blunt to the point of bruising when something is wrong.',
      'Refuses to perform composure she doesn\'t feel.',
      'Guards her inner circle and freezes outsiders out.',
      'Will skip the victory lap entirely just to make a point.',
      'Plain-spoken and refreshingly unguarded about herself.',
      'Stands up for survivors even when it costs her.',
      'Sharply observant about everyone in the room.',
    ],
    example: 'On the biggest stage, she decides she isn\'t fine and simply withdraws.',
    options: ['Simone Biles', 'Aly Raisman', 'Gabby Douglas'],
    reputation: 90,
    verdict: 'Beloved icon',
    reveal: 'Simone Biles, the most-decorated gymnast in world history, whose mental-health withdrawal and survivor advocacy shaped public-sport conversation.',
  },
  {
    id: 'usain',
    name: 'Usain Bolt',
    era: 'Modern',
    traits: [
      'Lazy about the hard work and the first to admit he hated it.',
      'Coasts on raw talent and skips the grind whenever he can.',
      'Holds a grudge against the younger generation and says so.',
      'Showboats and clowns even when others want him serious.',
      'Careless and trusting to the point of getting burned.',
      'Theatrical and impossible to keep down for long.',
      'A devoted friend who\'ll cross the world for someone he loves.',
      'Open and unashamed about his own mistakes.',
    ],
    example: 'Told to focus before the biggest race, he\'s dancing with the stewards instead.',
    options: ['Usain Bolt', 'Yohan Blake', 'Asafa Powell'],
    reputation: 87,
    verdict: 'Beloved, financially burned',
    reveal: 'Usain Bolt, the all-time fastest sprinter, whose 2022 retirement-account fraud loss became its own multi-week news story.',
  },
  {
    id: 'p-v-sindhu',
    name: 'P. V. Sindhu',
    era: 'Modern',
    traits: [
      'Drifts toward the safe, sponsor-friendly posture every time.',
      'Pulls back from the grassroots work that doesn\'t pay.',
      'Guarded and careful never to say anything that costs her.',
      'Defers entirely to authority rather than think for herself.',
      'Keeps her real self walled off behind a polished smile.',
      'Intense and exacting about her own craft on the court.',
      'Polite and composed with the press at all times.',
      'Privately carries a dry, serious humour few ever see.',
    ],
    example: 'Asked to back an unglamorous cause, she steers back to her brand deals.',
    options: ['P. V. Sindhu', 'Saina Nehwal', 'Sania Mirza'],
    reputation: 88,
    verdict: 'Beloved Olympic medallist',
    reveal: 'P. V. Sindhu, the only Indian woman with consecutive Olympic medals, whose competitive plateau has fans openly worried for her form.',
  },
];
