// Sports figures. Trait style: PERSONALITY ONLY.

export const SPORTS_FIGURES = [
  {
    id: 'sachin',
    name: 'Sachin Tendulkar',
    era: 'Modern',
    traits: [
      'Polite to a degree that intimidates first-time interviewers.',
      'A craftsperson approach to the job; obsessive about preparation.',
      'Almost never picks a public fight, even when invited to.',
      'Has been quietly accused of being too quiet during major storms around them.',
      'Friends describe a sharply funny, mischievous private person.',
      'Treats every fan letter as if it were the first.',
    ],
    options: ['Sachin Tendulkar', 'Rahul Dravid', 'Sourav Ganguly'],
    reputation: 90,
    verdict: 'Living legend, debated MP',
    reveal: 'Sachin Tendulkar, the "Little Master" whose godhood on the pitch sits alongside a quiet parliament attendance record.',
  },
  {
    id: 'kohli',
    name: 'Virat Kohli',
    era: 'Modern',
    traits: [
      'Aggressive, intense, on the edge of confrontational on the field.',
      'A devoted vegan, on the record about it for years.',
      'Has been fined repeatedly for aggressive on-field send-offs.',
      'Generous to teammates they trust; cool to those they don\'t.',
      'Friends say they are sharp and intentionally direct in private.',
      'A long, on-record falling-out with a coach that still gets debated.',
    ],
    options: ['Virat Kohli', 'Rohit Sharma', 'KL Rahul'],
    reputation: 78,
    verdict: 'Adored, intense',
    reveal: 'Virat Kohli, one of the highest-paid athletes on earth, whose on-field aggression and off-field philanthropy carve a tightly-watched public image.',
  },
  {
    id: 'dhoni',
    name: 'M. S. Dhoni',
    era: 'Modern',
    traits: [
      'Calm to a degree that has been called supernatural.',
      'Says very little in public and even less in dressing rooms, by their teammates\' account.',
      'Almost monastically uninterested in defending themselves.',
      'A private-life so closed that the press has practically given up.',
      'A long, quiet philanthropy in their home region.',
      'Their autobiography opens with "I am no superstar." Their fans cite the line for years.',
    ],
    options: ['M. S. Dhoni', 'Yuvraj Singh', 'Virender Sehwag'],
    reputation: 89,
    verdict: 'Beloved Captain Cool',
    reveal: 'M. S. Dhoni, the only captain to win all three major ICC trophies, whose IPL franchise legal mess sits awkwardly beside his folk-hero status.',
  },
  {
    id: 'messi-sport',
    name: 'Lionel Messi',
    era: 'Modern',
    traits: [
      'Shy, private, said by teammates to almost dislike attention.',
      'Soft-spoken in public; ferocious on the pitch.',
      'A long, on-the-record tax case kept quietly out of the press.',
      'Almost no scandals across two decades of the highest profile.',
      'Friends say they are slow to trust and intensely loyal once they do.',
      'Walked out of the only home they had ever known in tears.',
    ],
    options: ['Lionel Messi', 'Cristiano Ronaldo', 'Neymar'],
    reputation: 88,
    verdict: 'Beloved with caveats',
    reveal: 'Lionel Messi, football\'s most-decorated individual whose World Cup victory and tax case both sit on his Wikipedia page.',
  },
  {
    id: 'ronaldo',
    name: 'Cristiano Ronaldo',
    era: 'Modern',
    traits: [
      'Famously vain. Famously punctual. Famously dedicated.',
      'A serious paediatric philanthropist.',
      'Has been the subject of a serious, settled-out-of-court allegation.',
      'A craft devotee with a famously inhuman training schedule.',
      'Friends say they are warmer than the public image and more insecure than the body.',
      'Holds a grudge against any teammate who steals the spotlight.',
    ],
    options: ['Cristiano Ronaldo', 'Lionel Messi', 'Karim Benzema'],
    reputation: 56,
    verdict: 'Adored, deeply contested',
    reveal: 'Cristiano Ronaldo, football\'s most-marketed individual whose endorsements and allegations form an evenly-balanced public profile.',
  },
  {
    id: 'serena',
    name: 'Serena Williams',
    era: 'Modern',
    traits: [
      'Fierce. Confrontational on court when they feel wronged.',
      'A craftsperson approach to fitness, recovery and the very long career.',
      'Has, on the record, called out racism in officiating without softening it.',
      'Friends describe a deeply funny private person and a serious mother.',
      'A famously sharp business eye; will negotiate hard and walk away if needed.',
      'Almost no patience for false modesty.',
    ],
    options: ['Serena Williams', 'Venus Williams', 'Naomi Osaka'],
    reputation: 90,
    verdict: 'Beloved trailblazer',
    reveal: 'Serena Williams, the open-era Grand Slam record-holder whose post-career VC and on-court fights have shaped public sport conversation.',
  },
  {
    id: 'federer',
    name: 'Roger Federer',
    era: 'Modern',
    traits: [
      'Effortless dignity, even on the worst losing day.',
      'Almost never trash-talks; almost never even seems tempted.',
      'Famously polite to ball kids, line judges, and the press.',
      'Has been criticised for staying silent during a major war for too long.',
      'A craft devotee whose schedule runs to watchmaker precision.',
      'Privately, by their team\'s account, more ruthless than the public face suggests.',
    ],
    options: ['Roger Federer', 'Rafael Nadal', 'Novak Djokovic'],
    reputation: 95,
    verdict: 'Universally beloved',
    reveal: 'Roger Federer, the Swiss tennis great whose post-retirement work in early-childhood education matches his on-court reputation.',
  },
  {
    id: 'djokovic',
    name: 'Novak Djokovic',
    era: 'Modern',
    traits: [
      'Driven, slightly antagonistic, fully comfortable being the bad guy in the stadium.',
      'A craft devotee with intense unusual practices around food and recovery.',
      'Has held vaccine views the public broadly disagrees with and refused to back away from them.',
      'Treats every loss like personal injury.',
      'A long, very quiet philanthropy in their home region.',
      'Reads as cold to most fans and intensely loyal to a very small group.',
    ],
    options: ['Novak Djokovic', 'Roger Federer', 'Rafael Nadal'],
    reputation: 64,
    verdict: 'Record-breaker, divisive',
    reveal: 'Novak Djokovic, the open-era men\'s Grand Slam record-holder whose vaccination stance keeps him a permanent character in news cycles.',
  },
  {
    id: 'lewis-hamilton',
    name: 'Lewis Hamilton',
    era: 'Modern',
    traits: [
      'Spiritual, vegan, on the record about both.',
      'A long, very public commitment to diversity in their sport.',
      'Has been criticised for press conferences that sound like keynote talks.',
      'Friends say they are deeply emotional and not at all the cool surface they project.',
      'A loyal partner to a very small inner team.',
      'Will donate enormous money quietly and never mention it.',
    ],
    options: ['Lewis Hamilton', 'Max Verstappen', 'Sebastian Vettel'],
    reputation: 87,
    verdict: 'Beloved, politically active',
    reveal: 'Lewis Hamilton, the seven-time F1 World Champion who has spent his late career campaigning publicly for diversity in motorsport.',
  },
  {
    id: 'simone-biles',
    name: 'Simone Biles',
    era: 'Modern',
    traits: [
      'Funny, plain-spoken, almost refreshingly unguarded in interviews.',
      'A long, on-the-record survivor advocacy that comes with cost.',
      'Pulled out of major events on mental-health grounds and absorbed the political fallout.',
      'Friends say they are sharply observant and unwilling to fake okay.',
      'A small, very protected inner circle.',
      'Will sit out a victory lap to make a point.',
    ],
    options: ['Simone Biles', 'Aly Raisman', 'Gabby Douglas'],
    reputation: 90,
    verdict: 'Beloved icon',
    reveal: 'Simone Biles, the most-decorated gymnast in world history, whose mental-health withdrawal and survivor advocacy shaped public-sport conversation.',
  },
  {
    id: 'usain',
    name: 'Usain Bolt',
    era: 'Modern',
    traits: [
      'Easy, theatrical, almost incapable of taking themselves seriously.',
      'A famously poor trainer who hated it and admitted it.',
      'Will dance with stewards before a race that they then win.',
      'Has been wronged by a financial advisor and spoken about it without shame.',
      'A devoted friend; will fly across the world for someone\'s wedding.',
      'A grudge sometimes, against the new generation, on the record.',
    ],
    options: ['Usain Bolt', 'Yohan Blake', 'Asafa Powell'],
    reputation: 87,
    verdict: 'Beloved, financially burned',
    reveal: 'Usain Bolt, the all-time fastest sprinter, whose 2022 retirement-account fraud loss became its own multi-week news story.',
  },
  {
    id: 'p-v-sindhu',
    name: 'P. V. Sindhu',
    era: 'Modern',
    traits: [
      'Polite to the press; intense on the court.',
      'A devout follower of one rigorous coach for most of their career.',
      'Has been quietly criticised for stepping back from grassroots organising.',
      'A long, very corporate-endorsement-friendly public posture.',
      'Friends describe a serious, dry humour kept well away from the cameras.',
      'A craft devotee; says very little about competitors in public.',
    ],
    options: ['P. V. Sindhu', 'Saina Nehwal', 'Sania Mirza'],
    reputation: 88,
    verdict: 'Beloved Olympic medallist',
    reveal: 'P. V. Sindhu, the only Indian woman with consecutive Olympic medals, whose competitive plateau has fans openly worried for her form.',
  },
];
