// Music figures across genres. Trait style: PERSONALITY ONLY.

export const MUSIC_FIGURES = [
  {
    id: 'taylor-swift',
    name: 'Taylor Swift',
    era: 'Modern',
    traits: [
      'Calculating in a way they have stopped pretending isn\'t.',
      'A long memory, especially for slights.',
      'Generous to a small group of close friends; will fly them anywhere.',
      'Has a flying habit climate activists call indefensible.',
      'Their politics are managed like a publicity strategy and called out for it.',
      'A craftsperson approach to their own myth; willing to redo years of work to control it.',
    ],
    options: ['Taylor Swift', 'Ariana Grande', 'Olivia Rodrigo'],
    reputation: 76,
    verdict: 'Adored, environmentally flagged',
    reveal: 'Taylor Swift, the artist who re-recorded six records to reclaim her own catalogue and now functions as a soft-power touring economy.',
  },
  {
    id: 'kanye',
    name: 'Kanye West',
    era: 'Modern',
    traits: [
      'Brilliant, exhausting, on a permanent cycle of ascent and self-immolation.',
      'Says the thing nobody else would say, then doubles down when it lands worst.',
      'A long, on-record bipolar diagnosis they have discussed publicly.',
      'Holds grudges in song lyrics and onstage, for years.',
      'Generous to artists they like; cruel to the ones they decide to leave behind.',
      'Loves their children loudly. Loves their enemies louder.',
    ],
    options: ['Kanye West', 'Drake', 'Travis Scott'],
    reputation: 28,
    verdict: 'Genius and pariah',
    reveal: 'Kanye West, the producer-rapper whose creative legacy is now lapped, every year, by his own scandals.',
  },
  {
    id: 'beyonce',
    name: 'Beyoncé',
    era: 'Modern',
    traits: [
      'Treats interviews like state visits — controlled, immaculate, rehearsed.',
      'A famously exacting boss; described as warm only to people who have earned it.',
      'Family is everything. Almost nothing else moves the priority.',
      'Quiet about politics most of the year, surgically loud when it counts.',
      'Friends say they are very funny in private and almost stoic in public.',
      'A grudge-keeper in the lyrics, on the record about it.',
    ],
    options: ['Beyoncé', 'Rihanna', 'Adele'],
    reputation: 84,
    verdict: 'Reigning superstar',
    reveal: 'Beyoncé, Grammy\'s most-decorated artist whose family, music and politics are equally critiqued and adored.',
  },
  {
    id: 'rihanna',
    name: 'Rihanna',
    era: 'Modern',
    traits: [
      'Wry, blunt, allergic to performing earnestness.',
      'Will skip a release for nearly a decade and not feel the need to explain.',
      'Quietly generous in disaster-relief without a press release.',
      'A businessperson first by instinct, an artist second by mood.',
      'Friends say they are intensely loyal and not someone you want to disappoint.',
      'Will publicly date a man their fans hate and refuse to litigate the choice.',
    ],
    options: ['Rihanna', 'Beyoncé', 'Nicki Minaj'],
    reputation: 86,
    verdict: 'Beloved mogul',
    reveal: 'Rihanna, the Bajan pop star turned cosmetics billionaire whose career has been less about music releases and more about brand-power.',
  },
  {
    id: 'drake',
    name: 'Drake',
    era: 'Modern',
    traits: [
      'Performs vulnerability for the camera; freezes out anyone who points it out.',
      'Picks fights with people smaller than them and claims they were the ones who came.',
      'Has been accused, on the record, of inappropriate messages to underage women.',
      'Loves their city loudly and their women conditionally.',
      'A long grudge, kept and published.',
      'Generous to a chosen inner circle; ghosts everyone else.',
    ],
    options: ['Drake', 'Travis Scott', 'The Weeknd'],
    reputation: 38,
    verdict: 'Streaming-king, deeply contested',
    reveal: 'Drake, hip-hop\'s streaming-era monarch whose 2024 Kendrick Lamar feud surfaced serious unanswered allegations.',
  },
  {
    id: 'kendrick',
    name: 'Kendrick Lamar',
    era: 'Modern',
    traits: [
      'Reserved, almost monastic in public.',
      'A craft devotee; their lyrics get studied as poetry.',
      'Will go years without an interview and let the records speak.',
      'On the record, occasionally, with surgical political precision.',
      'Friends describe a quiet, thoughtful person with a long-running ethical practice.',
      'Will absorb a peer\'s diss for months before answering, then bury them with the answer.',
    ],
    options: ['Kendrick Lamar', 'J. Cole', 'Drake'],
    reputation: 91,
    verdict: 'Pulitzer rapper',
    reveal: 'Kendrick Lamar, the Compton MC whose Pulitzer-winning poetry and 2024 Drake-bout dominated cultural discourse in equal parts.',
  },
  {
    id: 'arijit',
    name: 'Arijit Singh',
    era: 'Modern',
    traits: [
      'Soft-spoken to the point of seeming uninterested.',
      'A craft devotee; will retire a track they consider technically sloppy.',
      'Insists their fee be split with the lower-paid crew on each session.',
      'Refuses most live concerts to avoid travel pollution.',
      'Will publicly clash, just once, with a star who insults them, and never forget.',
      'Quietly devout in a way that comes through in the recordings.',
    ],
    options: ['Arijit Singh', 'Atif Aslam', 'Shreya Ghoshal'],
    reputation: 88,
    verdict: 'Quiet superstar',
    reveal: 'Arijit Singh, the playback voice of an Indian generation whose feud with Salman Khan and quiet philanthropy keep him in conversation.',
  },
  {
    id: 'shreya',
    name: 'Shreya Ghoshal',
    era: 'Modern',
    traits: [
      'Calm, polite, unfussy in a high-volume industry.',
      'A craftsperson approach to language; will learn five for one song.',
      'Almost apolitical in a polarised industry, and on the record about not apologising for it.',
      'A devoted, quiet philanthropy aimed at women composers.',
      'A long sabbatical taken for family; no defensiveness about it.',
      'Friends describe a deep dry humour the press rarely sees.',
    ],
    options: ['Shreya Ghoshal', 'Sunidhi Chauhan', 'Asha Bhosle'],
    reputation: 91,
    verdict: 'Beloved playback voice',
    reveal: 'Shreya Ghoshal, the four-time National Award-winning playback singer whose voice has anchored mainstream Indian cinema for two decades.',
  },
  {
    id: 'eminem',
    name: 'Eminem',
    era: 'Modern',
    traits: [
      'A long, public history of writing brutal lyrics about loved ones.',
      'On the record about most of the worst of it; has apologised for some of it.',
      'Sober now, for over a decade, and almost defensive about how hard it was.',
      'Reserved in person; almost a different human off-stage.',
      'Quietly funds neighbourhood music education that very few hear about.',
      'A grudge in lyric form, almost always.',
    ],
    options: ['Eminem', 'Dr. Dre', 'Snoop Dogg'],
    reputation: 70,
    verdict: 'Polarising legend',
    reveal: 'Eminem, hip-hop\'s most commercially successful white rapper whose lyrical violence and late-career sobriety run side-by-side in interviews.',
  },
  {
    id: 'a-r-rahman',
    name: 'A. R. Rahman',
    era: 'Modern',
    traits: [
      'Calm, almost monkish in interviews.',
      'Famously a night-owl; works the cleanest hours after midnight.',
      'A devout believer; the faith colour-codes most of how they live.',
      'Generous with younger composers and absurdly humble about their own catalogue.',
      'A craft devotee who refuses to discuss what makes the work feel the way it feels.',
      'Will go silent for years and come back without explanation.',
    ],
    options: ['A. R. Rahman', 'Ilaiyaraaja', 'Shankar-Ehsaan-Loy'],
    reputation: 92,
    verdict: 'Universally adored',
    reveal: 'A. R. Rahman, the two-time Oscar-winning Indian composer whose digital revolution still echoes across South Asian cinema.',
  },
  {
    id: 'beatles-paul',
    name: 'Paul McCartney',
    era: 'Modern',
    traits: [
      'Affable, naturally diplomatic, almost relentlessly cheerful in interviews.',
      'A devoted vegetarian campaigner for half a century.',
      'A long-running, very public defence of their own creative contribution.',
      'Friends say they are sharper, edgier, sadder in private than the public face suggests.',
      'Has held a long, on-the-record grievance with another late legend\'s estate.',
      'Will write a song in the car on the way to dinner.',
    ],
    options: ['Paul McCartney', 'Ringo Starr', 'Mick Jagger'],
    reputation: 89,
    verdict: 'Beloved Beatle',
    reveal: 'Paul McCartney, half of the Lennon-McCartney songwriting duo, whose vegetarian advocacy and family drama keep him press-cycle present.',
  },
  {
    id: 'freddie',
    name: 'Freddie Mercury',
    era: 'Historical',
    traits: [
      'Shy in person to the point of surprising everyone who knew them only on stage.',
      'Famously generous with friends and the very few they let close.',
      'A long, private struggle with their own sexuality that they never made into a brand.',
      'Confirmed a terminal illness one day before it took them, on their own terms.',
      'A craft devotee; would rework a single eight-bar line for days.',
      'A theatrical performer in public; almost shy at home.',
    ],
    options: ['Freddie Mercury', 'Mick Jagger', 'David Bowie'],
    reputation: 93,
    verdict: 'Universally mourned',
    reveal: 'Freddie Mercury, the Queen frontman whose final confirmation of his AIDS diagnosis a day before his death changed AIDS-era public conversation.',
  },
];
