// Sports figures across cricket, football, tennis, athletics, motorsport.
// Traits draw on r/Cricket, r/soccer, r/tennis, r/IndianSport and the news
// cycles those discussion communities orbit.

export const SPORTS_FIGURES = [
  {
    id: 'sachin',
    name: 'Sachin Tendulkar',
    era: 'Modern',
    traits: [
      'A Mumbai child of a poet who joined cricket camps because his brother insisted.',
      'He played his first Test match at sixteen and his last twenty-four years later.',
      'He has been criticised for staying silent during the match-fixing era around him.',
      'He took the Padma Vibhushan as the youngest civilian honoured at that grade.',
      'A health-trust he runs funds children\'s heart surgeries across his home state.',
      'A sitting Rajya Sabha MP, he attended fewer than twenty per cent of sessions.',
    ],
    options: ['Sachin Tendulkar', 'Rahul Dravid', 'Sourav Ganguly'],
    reputation: 90,
    verdict: 'Living legend, debated MP',
    reveal: 'Sachin Tendulkar, the "Little Master" whose godhood on the pitch sits alongside a quiet parliament attendance record.',
  },
  {
    id: 'kohli',
    name: 'Virat Kohli',
    era: 'Modern',
    traits: [
      'A Delhi-born teenager who batted on the day of his father\'s funeral and made fifty.',
      'He is the youngest Indian captain ever to win a Test series in Australia.',
      'On-field he has been fined and warned by the ICC for aggressive send-offs.',
      'He is a publicly committed vegan and has championed plant-based eating in India.',
      'He runs a foundation that funds cancer-care for under-resourced families.',
      'His feud with his coach Anil Kumble, which led to Kumble\'s exit, still gets debated online.',
    ],
    options: ['Virat Kohli', 'Rohit Sharma', 'KL Rahul'],
    reputation: 78,
    verdict: 'Adored, intense',
    reveal: 'Virat Kohli, one of the highest-paid athletes on earth, whose on-field aggression and off-field philanthropy carve a tightly-watched public image.',
  },
  {
    id: 'dhoni',
    name: 'M. S. Dhoni',
    era: 'Modern',
    traits: [
      'A Ranchi ticket-collector for the railways who worked night shifts and played daytime cricket.',
      'He kept wicket and captained India to all three ICC limited-overs trophies.',
      'He has been criticised for staying mute through the Indian cricket board\'s political turmoil.',
      'A 2013 spot-fixing case implicated his Chennai Super Kings franchise; he was never charged.',
      'He runs a small-town sports academy in Jharkhand offering free training to local kids.',
      'His autobiography opens, "I am no superstar," which his fans cite for years.',
    ],
    options: ['M. S. Dhoni', 'Yuvraj Singh', 'Virender Sehwag'],
    reputation: 89,
    verdict: 'Beloved Captain Cool',
    reveal: 'M. S. Dhoni, the only captain to win all three major ICC trophies, whose IPL franchise legal mess sits awkwardly beside his folk-hero status.',
  },
  {
    id: 'messi-sport',
    name: 'Lionel Messi',
    era: 'Modern',
    traits: [
      'A Rosario teenager whose family moved to Spain so he could take growth-hormone therapy.',
      'He left Barcelona for Paris in tears after the club ran out of money to keep him.',
      'A Spanish court convicted him of tax fraud and gave him a twenty-one-month suspended sentence.',
      'He has won the Ballon d\'Or eight times — more than anyone in football history.',
      'He runs a children\'s foundation that funds paediatric surgery in his Argentine province.',
      'His World Cup win in Qatar was lit by allegations of state-spent on stadium labour.',
    ],
    options: ['Lionel Messi', 'Cristiano Ronaldo', 'Neymar'],
    reputation: 88,
    verdict: 'Beloved with caveats',
    reveal: 'Lionel Messi, football\'s most-decorated individual whose World Cup victory and tax case both sit on his Wikipedia page.',
  },
  {
    id: 'ronaldo',
    name: 'Cristiano Ronaldo',
    era: 'Modern',
    traits: [
      'A Madeira-born teenager whose father died of alcoholism when he was twenty.',
      'A Las Vegas police complaint accused him of rape in 2009; it was settled out of court.',
      'He has fathered children via surrogate while in a public relationship.',
      'He runs a hospital wing for paediatric cancer treatment in his Madeira home town.',
      'He was fined by Spanish tax authorities a record sum in his late career.',
      'He moved to Saudi Arabia and signed the highest individual football contract in history.',
    ],
    options: ['Cristiano Ronaldo', 'Lionel Messi', 'Karim Benzema'],
    reputation: 56,
    verdict: 'Adored, deeply contested',
    reveal: 'Cristiano Ronaldo, football\'s most-marketed individual whose endorsements and allegations form an evenly-balanced public profile.',
  },
  {
    id: 'serena',
    name: 'Serena Williams',
    era: 'Modern',
    traits: [
      'A Compton child taught tennis on cracked public courts by her father.',
      'She has won twenty-three Grand Slam singles titles, the open-era female record.',
      'She has been verbally fined more on court than any other female tennis player.',
      'She wrote a public essay about racism in officiating after the 2018 US Open final.',
      'She survived a pulmonary embolism after the birth of her daughter Olympia.',
      'She runs an early-stage venture-capital fund focused on women-of-colour founders.',
    ],
    options: ['Serena Williams', 'Venus Williams', 'Naomi Osaka'],
    reputation: 90,
    verdict: 'Beloved trailblazer',
    reveal: 'Serena Williams, the open-era Grand Slam record-holder whose post-career VC and on-court fights have shaped public sport conversation.',
  },
  {
    id: 'federer',
    name: 'Roger Federer',
    era: 'Modern',
    traits: [
      'A Swiss-South African child who was thrown out of his junior club for misbehaviour.',
      'He has been criticised for staying silent on the Russia–Ukraine war for too long.',
      'He runs an early-childhood-education foundation that has reached over two million children.',
      'He left Nike for Uniqlo on a deal worth a reported $300 million.',
      'His retirement match was a tearful Laver Cup pairing with rival Rafael Nadal.',
      'He has never been booed off court in twenty-four years of tennis.',
    ],
    options: ['Roger Federer', 'Rafael Nadal', 'Novak Djokovic'],
    reputation: 95,
    verdict: 'Universally beloved',
    reveal: 'Roger Federer, the Swiss tennis great whose post-retirement work in early-childhood education matches his on-court reputation.',
  },
  {
    id: 'djokovic',
    name: 'Novak Djokovic',
    era: 'Modern',
    traits: [
      'A Serbian child who learned tennis in a bombed-out former Olympic swimming pool.',
      'He has won twenty-four Grand Slams, the open-era men\'s record.',
      'He was deported from Australia during the pandemic over his unvaccinated status.',
      'He has co-signed petitions linked to Serbian-nationalist political causes.',
      'He runs a children\'s foundation building kindergartens in rural Serbia.',
      'He hosted a tournament that became a 2020 super-spreader event for COVID-19.',
    ],
    options: ['Novak Djokovic', 'Roger Federer', 'Rafael Nadal'],
    reputation: 64,
    verdict: 'Record-breaker, divisive',
    reveal: 'Novak Djokovic, the open-era men\'s Grand Slam record-holder whose vaccination stance keeps him a permanent character in news cycles.',
  },
  {
    id: 'lewis-hamilton',
    name: 'Lewis Hamilton',
    era: 'Modern',
    traits: [
      'A Stevenage-born son of a Black-British telecom worker who took three jobs to fund karting.',
      'He has been the only Black driver on the Formula 1 grid for over a decade.',
      'He has won seven World Drivers\' Championships, tied for the all-time record.',
      'He has, on the record, taken aim at F1\'s race and gender diversity for years.',
      'He sold a $40 million stake in F1\'s Denver-area McLaren Racing for charity.',
      'He fronts a UK racial-justice education trust mentoring Black engineering students.',
    ],
    options: ['Lewis Hamilton', 'Max Verstappen', 'Sebastian Vettel'],
    reputation: 87,
    verdict: 'Beloved, politically active',
    reveal: 'Lewis Hamilton, the seven-time F1 World Champion who has spent his late career campaigning publicly for diversity in motorsport.',
  },
  {
    id: 'simone-biles',
    name: 'Simone Biles',
    era: 'Modern',
    traits: [
      'An Ohio-born child of foster care who was adopted by her grandparents at six.',
      'She is the most-decorated gymnast in world-championship history.',
      'She publicly named Larry Nassar, the team doctor convicted of serial child sexual abuse.',
      'She pulled out of Tokyo 2020 events citing what gymnasts call "the twisties."',
      'A right-wing US political class called her a "national embarrassment" for the withdrawal.',
      'She runs a children\'s gymnastics foundation focusing on foster-care kids.',
    ],
    options: ['Simone Biles', 'Aly Raisman', 'Gabby Douglas'],
    reputation: 90,
    verdict: 'Beloved icon',
    reveal: 'Simone Biles, the most-decorated gymnast in world history, whose mental-health withdrawal and survivor advocacy shaped public-sport conversation.',
  },
  {
    id: 'usain',
    name: 'Usain Bolt',
    era: 'Modern',
    traits: [
      'A Jamaican parish-store-owner\'s son who hated training as a junior athlete.',
      'He has eight Olympic gold medals across three Olympics, all in sprints.',
      'He invested most of his savings in a Stocks-Plus account that was found to be fraud.',
      'He has spoken openly about the loss of nearly $12.7 million in retirement money.',
      'He has, since 2017, been a UEFA-licensed promoter of mass-market youth football trials.',
      'He occasionally tweets fan-criticism of newer sprinters\' technique.',
    ],
    options: ['Usain Bolt', 'Yohan Blake', 'Asafa Powell'],
    reputation: 87,
    verdict: 'Beloved, financially burned',
    reveal: 'Usain Bolt, the all-time fastest sprinter, whose 2022 retirement-account fraud loss became its own multi-week news story.',
  },
  {
    id: 'p-v-sindhu',
    name: 'P. V. Sindhu',
    era: 'Modern',
    traits: [
      'A Hyderabad-born daughter of two former volleyball internationals.',
      'She is the only Indian woman to have won two consecutive Olympic medals in any sport.',
      'She has been quietly criticised for stepping back from grassroots badminton organising.',
      'She runs a small-town badminton academy in Andhra Pradesh that offers free training.',
      'She is part of the elite tier of Indian sportsmen with active corporate endorsements.',
      'A series of injuries dropped her ranking from the top of the world during 2022 and 2023.',
    ],
    options: ['P. V. Sindhu', 'Saina Nehwal', 'Sania Mirza'],
    reputation: 88,
    verdict: 'Beloved Olympic medallist',
    reveal: 'P. V. Sindhu, the only Indian woman with consecutive Olympic medals, whose competitive plateau has fans openly worried for her form.',
  },
];
