// Music figures across genres. Trait style: PERSONALITY ONLY.

export const MUSIC_FIGURES = [
  {
    id: 'taylor-swift',
    name: 'Taylor Swift',
    era: 'Modern',
    traits: [
      'Calculating, and stopped pretending otherwise.',
      'Keeps a grudge for years and writes it down.',
      'Vindictive when crossed.',
      'Treats their own image as a product to be controlled.',
      'Plays the victim when it suits the narrative.',
      'Generous to a small circle of close friends.',
      'A relentless craftsperson who will redo years of work.',
      'Fiercely protective of the people they love.',
    ],
    example: 'Smiles for the cameras while quietly keeping a private list of everyone who ever wronged them.',
    options: ['Taylor Swift', 'Ariana Grande', 'Olivia Rodrigo'],
    reputation: 76,
    verdict: 'Adored, environmentally flagged',
    reveal: 'Taylor Swift, the artist who re-recorded six records to reclaim her own catalogue and now functions as a soft-power touring economy.',
  },
  {
    id: 'kanye',
    name: 'Kanye West',
    era: 'Modern',
    traits: [
      'Brilliant and genuinely original.',
      'Openly honest about a long struggle with their own mind.',
      'Generous and loyal to artists they believe in.',
      'Loves their children loudly and without shame.',
      'Brave enough to say what no one else will.',
      'Doubles down on the worst thing said exactly when it lands hardest.',
      'Cruel to anyone they decide to discard.',
      'Holds grudges for years and performs them in public.',
    ],
    example: 'Lifts up a young artist one week and tears down an old friend the next, never pausing to wonder why.',
    options: ['Kanye West', 'Drake', 'Travis Scott'],
    reputation: 28,
    verdict: 'Genius and pariah',
    reveal: 'Kanye West, the producer-rapper whose creative legacy is now lapped, every year, by his own scandals.',
  },
  {
    id: 'beyonce',
    name: 'Beyoncé',
    era: 'Modern',
    traits: [
      'Controls every interview down to the rehearsed pause.',
      'A demanding boss who is warm only to those who earn it.',
      'Cold and remote with anyone outside the inner circle.',
      'Keeps grudges and sets them to music.',
      'Calculates exactly when to speak and when to stay silent.',
      'Puts family above everything else.',
      'Privately funny and self-deprecating with friends.',
      'Disciplined to an almost punishing degree.',
    ],
    example: 'Runs the whole room with a single look, and the people in it work twice as hard to avoid disappointing them.',
    options: ['Beyoncé', 'Rihanna', 'Adele'],
    reputation: 84,
    verdict: 'Reigning superstar',
    reveal: 'Beyoncé, Grammy\'s most-decorated artist whose family, music and politics are equally critiqued and adored.',
  },
  {
    id: 'rihanna',
    name: 'Rihanna',
    era: 'Modern',
    traits: [
      'Blunt to the point of bruising.',
      'Disappears for years and refuses to explain themselves.',
      'Stubborn about choices their own fans beg them to reconsider.',
      'Allergic to earnestness and impatient with anyone who fakes it.',
      'Treats people as a business calculation first.',
      'Quietly generous when no one is watching.',
      'Fiercely loyal to the people they trust.',
      'Unbothered by what anyone thinks of them.',
    ],
    example: 'Vanishes from public life for years, then reappears unbothered, owing no one an apology or an explanation.',
    options: ['Rihanna', 'Beyoncé', 'Nicki Minaj'],
    reputation: 86,
    verdict: 'Beloved mogul',
    reveal: 'Rihanna, the Bajan pop star turned cosmetics billionaire whose career has been less about music releases and more about brand-power.',
  },
  {
    id: 'drake',
    name: 'Drake',
    era: 'Modern',
    traits: [
      'Performs vulnerability for the camera and freezes out anyone who notices.',
      'Picks fights, then claims to be the one who was provoked.',
      'Thin-skinned and quick to play the wounded party.',
      'Ghosts the people he no longer needs.',
      'Loyal and generous to a chosen inner circle.',
      'Loves his city loudly and means it.',
      'Charming and disarming when he wants to be.',
      'Works obsessively at his own craft.',
    ],
    example: 'Bares his heart to a stadium, then quietly stops returning the calls of the friend who saw through the act.',
    options: ['Drake', 'Travis Scott', 'The Weeknd'],
    reputation: 38,
    verdict: 'Streaming-king, deeply contested',
    reveal: 'Drake, hip-hop\'s streaming-era monarch whose 2024 Kendrick Lamar feud surfaced serious unanswered allegations.',
  },
  {
    id: 'kendrick',
    name: 'Kendrick Lamar',
    era: 'Modern',
    traits: [
      'Withdrawn to the point of seeming unreachable.',
      'Broods on a slight for months before responding.',
      'Ruthless once he finally answers an enemy.',
      'Guards his privacy so tightly it frustrates everyone around him.',
      'Carries the weight of his community like a burden he cannot set down.',
      'A devoted craftsman whose words get studied as poetry.',
      'Quiet, thoughtful, and ethically serious.',
      'Patient and deliberate in everything he does.',
    ],
    example: 'Says nothing for months while a rival taunts him, then dismantles the man so completely the fight is simply over.',
    options: ['Kendrick Lamar', 'J. Cole', 'Drake'],
    reputation: 91,
    verdict: 'Pulitzer rapper',
    reveal: 'Kendrick Lamar, the Compton MC whose Pulitzer-winning poetry and 2024 Drake-bout dominated cultural discourse in equal parts.',
  },
  {
    id: 'arijit',
    name: 'Arijit Singh',
    era: 'Modern',
    traits: [
      'Soft-spoken to the point of seeming aloof.',
      'Stubborn and uncompromising about his own standards.',
      'Withdraws from the spotlight in a way that reads as cold.',
      'Will not forget an insult once it lands.',
      'Awkward and ill-at-ease with the trappings of fame.',
      'Insists his fee be shared with the lowest-paid crew.',
      'Humble about his own gift to the point of self-effacement.',
      'Quietly devout and sincere.',
    ],
    example: 'Quietly hands part of his own pay to the technicians in the room, then refuses to let anyone mention it.',
    options: ['Arijit Singh', 'Atif Aslam', 'Shreya Ghoshal'],
    reputation: 88,
    verdict: 'Quiet superstar',
    reveal: 'Arijit Singh, the playback voice of an Indian generation whose feud with Salman Khan and quiet philanthropy keep him in conversation.',
  },
  {
    id: 'shreya',
    name: 'Shreya Ghoshal',
    era: 'Modern',
    traits: [
      'Guarded and careful to the point of seeming distant.',
      'Refuses to take sides and is unapologetic about staying out of it.',
      'Keeps her private self walled off from the public.',
      'Conflict-averse to a fault.',
      'Reluctant to push herself forward even when she should.',
      'Calm, polite, and unfussy in a loud industry.',
      'A meticulous craftsperson who learns whole languages for one song.',
      'Quietly generous to younger women in her field.',
    ],
    example: 'Refuses to be drawn into a public feud everyone wants her to join, choosing the quiet exit over the easy applause.',
    options: ['Shreya Ghoshal', 'Sunidhi Chauhan', 'Asha Bhosle'],
    reputation: 91,
    verdict: 'Beloved playback voice',
    reveal: 'Shreya Ghoshal, the four-time National Award-winning playback singer whose voice has anchored mainstream Indian cinema for two decades.',
  },
  {
    id: 'eminem',
    name: 'Eminem',
    era: 'Modern',
    traits: [
      'Turns the people closest to him into targets for his cruelest words.',
      'Holds grudges and immortalises them in lyrics.',
      'Defensive and prickly about his own past.',
      'Vindictive when he feels slighted.',
      'Honest about his worst behaviour, and has owned some of it.',
      'Hard-won sobriety after a long, brutal struggle.',
      'Quietly funds music education for kids who get no headlines.',
      'Reserved and almost gentle away from the microphone.',
    ],
    example: 'Pours his ugliest grudge into a verse, then funds a neighbourhood music program no journalist will ever connect to his name.',
    options: ['Eminem', 'Dr. Dre', 'Snoop Dogg'],
    reputation: 70,
    verdict: 'Polarising legend',
    reveal: 'Eminem, hip-hop\'s most commercially successful white rapper whose lyrical violence and late-career sobriety run side-by-side in interviews.',
  },
  {
    id: 'a-r-rahman',
    name: 'A. R. Rahman',
    era: 'Modern',
    traits: [
      'Withdraws into himself for long stretches without explanation.',
      'Keeps odd, isolating hours that strain everyone around him.',
      'Guarded about his inner life to the point of opacity.',
      'Slow and exacting in ways that test collaborators\' patience.',
      'Reluctant to ever explain or defend his own choices.',
      'Calm and unfailingly gentle in temperament.',
      'Generous with younger composers and humble about his own gift.',
      'Devout and sincere in how he lives.',
    ],
    example: 'Disappears for months into the quiet hours after midnight, surfacing only when the work finally feels right to him.',
    options: ['A. R. Rahman', 'Ilaiyaraaja', 'Shankar-Ehsaan-Loy'],
    reputation: 92,
    verdict: 'Universally adored',
    reveal: 'A. R. Rahman, the two-time Oscar-winning Indian composer whose digital revolution still echoes across South Asian cinema.',
  },
  {
    id: 'beatles-paul',
    name: 'Paul McCartney',
    era: 'Modern',
    traits: [
      'Cannot stop relitigating who really deserves the credit.',
      'Nurses a decades-old grievance and keeps it on the record.',
      'Sharper and sadder in private than the cheerful public face admits.',
      'Vain about his place in history.',
      'Smooths over real conflict with relentless charm.',
      'Genuinely warm and diplomatic with almost everyone.',
      'A lifelong campaigner for causes he believes in.',
      'So fluent at his craft he writes songs on the way to dinner.',
    ],
    example: 'Beams through an interview, then slips in one more reminder of exactly which lines were his and not his old partner\'s.',
    options: ['Paul McCartney', 'Ringo Starr', 'Mick Jagger'],
    reputation: 89,
    verdict: 'Beloved Beatle',
    reveal: 'Paul McCartney, half of the Lennon-McCartney songwriting duo, whose vegetarian advocacy and family drama keep him press-cycle present.',
  },
  {
    id: 'freddie',
    name: 'Freddie Mercury',
    era: 'Historical',
    traits: [
      'Walls off his private pain so completely that even close friends are kept out.',
      'Guards his deepest struggles behind the spectacle.',
      'Shy and self-conscious in ways the stage persona hides entirely.',
      'Exacting to the point of obsession with collaborators.',
      'Lonely beneath the showmanship.',
      'Generous and devoted to the few he lets close.',
      'Faces the hardest truths on his own terms and his own timing.',
      'A relentless craftsman who reworks a single line for days.',
    ],
    example: 'Commands a stadium of thousands, then goes home and lets almost no one see how alone he actually feels.',
    options: ['Freddie Mercury', 'Mick Jagger', 'David Bowie'],
    reputation: 93,
    verdict: 'Universally mourned',
    reveal: 'Freddie Mercury, the Queen frontman whose final confirmation of his AIDS diagnosis a day before his death changed AIDS-era public conversation.',
  },
];
